### ISSUE TITLE
卸载hids_driver内核模块失败，需要重启主机

### ISSUE THREAD

**Issue by 297242448** [bytedance/Elkeid#113]
**Describe the bug**
卸载hids_driver内核模块失败，需要重启主机
找不到/proc/hids_driver/1文件
driver 进程已经退出
**To Reproduce**
1. rmmod hids_driver

lsmod |grep hids
hids_driver           106032  0 
Switch_Center:/proc # rmmod hids_driver
rmmod: ERROR: could not remove 'hids_driver': Device or resource busy
rmmod: ERROR: could not remove module hids_driver: Device or resource busy
Switch_Center:/proc # ls /proc/

**Comment by EBWi11** [comment]
发一下kernel version呢

**Comment by 297242448** [comment]
> 发一下kernel version呢

3.10.0-862.14.4

**Comment by EBWi11** [comment]
麻烦贴下 `dmesg | grep gcc` 和 `gcc -v` 的结果看看

**Comment by mattwuq** [comment]
还能提供完整的dmesg？之前都做了什么操作？CentOS 7.5及对应内核版本均验证通过

**Comment by shenping-bd** [comment]
还能提供完整的dmesg？之前都做了什么操作？
CentOS 7.5及对应内核版本均验证通过，这个问题跟本地环境相关的可能更大
