### ISSUE TITLE
mongo按照安装默认27017端口能够正常启动和创建用户，但是按照教程更改conf后无法成功启动，kill对应进程与删除mongod.log都没有用

### ISSUE THREAD

**Issue by makabakaM** [bytedance/Elkeid#129]
**Describe the bug**
刚安装mongodb时数据库可以正常启动，可以成功创建管理员用户。后按照教程更改conf文件，端口也改为了27000，出现了问题

terminal中输入mongo --port 27000能够启动mongo，但是创建管理员失败

![截图1](https://user-images.githubusercontent.com/65537387/133567892-1118a4c3-fe69-4114-a8cc-efe5788c6d6e.png)

注释掉mongod.conf中authorization: enabled后仍无法成功创建。

想要重新启动mongodb，执行/usr/bin/mongod -f /etc/mongod.conf --auth，但是也出现了错误

![截图2](https://user-images.githubusercontent.com/65537387/133570358-20a2069f-e2ea-4472-b098-100d20b21c21.png)

将mongod.conf改回原来的默认配置后，又能够成功创建管理员用户了

![截图3](https://user-images.githubusercontent.com/65537387/133570548-88086032-799c-4e13-8f11-d595f04429d0.png)

为什么按照教程对mongod.conf操作后mongodb无法正常启动了。

**Comment by Hackerl** [comment]
这个问题你应该问mongodb社区，或者自己使用搜索引擎，错误描述都在你发的图片里。
https://stackoverflow.com/questions/41783700/when-creating-first-admin-user-on-mongdb-cluster-getting-error-couldnt-add-use/41789745

**Comment by hugebomb** [comment]
管理员用户的创建不影响elkeid的部署，只需要创建一个普通用户给elkeid就可以了。另外mongodb部署问题，建议参考的官方文档。
