### ISSUE TITLE
agent运行提示NO NETWORK IS available

### ISSUE THREAD

**Issue by LLZachary** [bytedance/Elkeid#142]
/Elkeid/agent# cd /etc/elkeid && /etc/elkeid/elkeid-agent &
[1] 15038
root@debian:~/Elkeid/agent# panic: No network is available

goroutine 23 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00037c000, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*SugaredLogger).log(0xc0000a83d8, 0x4, 0x0, 0x0, 0xc00032bfc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panic(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:123
github.com/bytedance/Elkeid/agent/transport.Run()
	/root/Elkeid/agent/transport/client.go:30 +0x488
created by main.main
	/root/Elkeid/agent/main.go:75 +0xc05
^C
[1]+  退出 2                cd /etc/elkeid && /etc/elkeid/elkeid-agent

**Comment by LLZachary** [comment]
检查并调整了server和agent的时钟，确认一致后还是不行，agent仍然提示无可用网络

**Comment by Serinalice** [comment]
Agent配置和证书更新了吗？

**Comment by LLZachary** [comment]
我从server里把build生成的三个证书文件复制到agent里了，但是还是不行。是我证书和配置有问题吗？我是按照文档里的步骤配置的agent product.go和复制证书的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月10日(星期三) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytedance/Elkeid] agent运行提示NO NETWORK IS available (Issue #142)





 
Agent配置和证书更新了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Serinalice** [comment]
生成证书时改elkeid.com这个域名了吗？如果修改了，也需要对应修改Agent中的Host。

**Comment by Serinalice** [comment]
telnet 一下 priLB中的端口和地址，看看通不通。

**Comment by LLZachary** [comment]
没有修改域名。telnet之后sd_host的8088端口显示connected to sd_host。

**Comment by LLZachary** [comment]
另外把sd服务机上生成的证书拷贝在agent端上也不行。我刚刚读了main.go文件，我在想，会不会是agent与github或者go的网站连接不好？我看import里站点似乎都没有通过proxy。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/Elkeid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/Elkeid] agent运行提示NO NETWORK IS available (Issue #142)





 
telnet 一下 priLB中的端口和地址，看看通不通。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Serinalice** [comment]
先别配置sd 把agent_center的 IP和端口填写到 priLB里面 再试试看

**Comment by Serinalice** [comment]
发一下product.go文件吧

**Comment by LLZachary** [comment]
product.go这个应该是没问题的，你看一下：
连个地址和端口在agent端都可以telnet通

package connection

import _ "embed"

//go:embed client.key
var ClientKey []byte

//go:embed client.crt
var ClientCert []byte

//go:embed ca.crt
var CaCert []byte

func init() {
        sd["sd"] = "10.1.112.95:8088"
        priLB["ac"] = "10.1.112.26:6751"  
        //这里"elkeid.com"需要与生成证书时使用的域名一致，如果生成时不是默认配置需要在这里一起修改
        setDialOptions(CaCert, ClientKey, ClientCert, "elkeid.com")
}

**Comment by LLZachary** [comment]
> 发一下product.go文件吧

我仔细看了一下，应该是跟go语言有关，您看一下相关代码：

goroutine 10 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0003600c0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*SugaredLogger).log(0xc0000103e8, 0x4, 0x0, 0x0, 0xc000409fc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panic(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:123
github.com/bytedance/Elkeid/agent/transport.Run()
	/root/Elkeid/agent/transport/client.go:30 +0x488
created by main.main
	/root/Elkeid/agent/main.go:75 +0xc05

**Comment by LLZachary** [comment]
问题已经解决，我仔细读了一下agent下的go文件，发现所有import的第三方工程都存在路径风险。比如shirou/gopsutil/v3路径已经更新，而global.go文件中没有修改。此外，类似uuid等第三方工程也存在套用其他第三方库，我在检查时发现也存在类似问题。所以我建议能不能直接指导读者在go里手动下载安装这些第三方库，然后在.go文件里把import的地址写成绝对路径。。。修改依赖真的太痛苦了。。。

**Comment by Serinalice** [comment]
和这个无关，import只影响编译的依赖。
https://github.com/bytedance/Elkeid/blob/main/agent/test/main.go
替换证书，修改地址，编译，然后执行，看有无报错。

**Comment by LLZachary** [comment]
重新clone了项目，在test目录下编译执行均无报错，但agent目录下执行依旧no network。。。。

**Comment by LLZachary** [comment]
重新clone了项目，重新build了server，然后将agent-center的conf目录中生成的证书复制到test目录下，在test目录下编译执行同样报no network。。。将新证书替换agent/transport/connection中的三个证书，agent目录下编译执行，依旧报错。。。
