### ISSUE TITLE
Driver 性能测试报告

### ISSUE THREAD

**Issue by qqhao523** [bytedance/Elkeid#145]
<img width="974" alt="截屏2021-11-15 上午10 58 43" src="https://user-images.githubusercontent.com/2986708/141715333-fb5458d9-c8cf-4de2-a838-210f3e67b48a.png">
能介绍一下你们是如果获得Average Delay 和TP99的delay数据的Benchmark Data吗？谢谢

https://github.com/bytedance/Elkeid/blob/main/driver/benchmark_data/handler/bind_handler_data

**Comment by EBWi11** [comment]
压力是通过 https://github.com/linux-test-project/ltp 来模拟，delay数据是通过trace-cmd，如：
```trace-cmd record -p function_graph -l udp_recvmsg_handler -o  udp_recvmsg_handler_data sleep 180```

**Comment by ciphersaw** [comment]
可参考「[Elkeid Driver 性能测试操作指引](https://ciphersaw.me/2023/05/02/operational-guide-of-elkeid-driver-performance-test/)」
