### ISSUE TITLE
Considering add LD_LIBRARY_PATH to envp check

### ISSUE THREAD

**Issue by chriskaliX** [bytedance/Elkeid#156]
我看目前对于 env 的采集，做了 ssh_connection 和 ld_preload 的
LD_LIBRARY_PATH 这个是否也需要添加进来呢

**Comment by EBWi11** [comment]
good point

**Comment by chriskaliX** [comment]
OK～我晚点尝试写个 pr

**Comment by chriskaliX** [comment]
related: [pr-157](https://github.com/bytedance/Elkeid/pull/157)
