### ISSUE TITLE
JVMProbe 存在无法捕获的 包异常

### ISSUE THREAD

**Issue by HsinTsao** [bytedance/Elkeid#161]
**Is your feature request related to a problem? Please describe.**
JVMProbe 作为java agent注入到对应的程序中时，大部分可能执行异常的操作都有了try catch，可输出到日志文件中。但是有一些集成的依赖发生异常，没有尝试捕获，所以日志无法检查异常堆栈，也不会报给目标进程。比如说我在使用的过程中，SmithMethodVisitor一直无法响应事件，也没有报错信息。最后，调试发现发生了异常，走到了异常类NoClassDefFoundError，错误信息：org/objectweb/asm/commons/AdviceAdapter。

**Describe the solution you'd like**
我已经通过检查自己的agent jar来解决该问题。但是，请问这种异常未报到日志或者标准输出，是java机制的问题吗？因为这种，什么错误信息都看不到的情况，会造成很大的困扰。Elkeid是否会在这方面做出优化，来提高健壮性？

**Suggestion**
Elkeid增加对异常链监控，在异常处理类中捕获异常并反馈到日志中，防止有些异常未处理未发现。
我还是一名新手，未能实现这样的功能，但是根据浅薄的知识，agent应该是可以做到这样的功能的。
这是似乎可用的方法：[https://github.com/EagleJin/java-agent](https://github.com/EagleJin/java-agent)

**Comment by Hackerl** [comment]
你需要将所有依赖以及java agent打包成一个jar包。
https://github.com/bytedance/Elkeid/blob/main/rasp/jvm/JVMProbe/build.gradle#L101

**Comment by HsinTsao** [comment]
> 
是的，我已经解决了这个问题。我只是想说，似乎存在未捕获的异常。

**Comment by Hackerl** [comment]
你要使用java agent，至少要保证java agent的依赖已经打包了，而不是要求java agent检测异常。

**Comment by HsinTsao** [comment]
好的
