### ISSUE TITLE
There was a problem during deployment

### ISSUE THREAD

**Issue by quail2333** [bytedance/Elkeid#186]
**Describe the bug**
[ERRO]  2022-01-28T22:13:18+08:00       when deploying, an error occurred: Checker installed faield: exec check cmd failed when pre check host, err: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 -i /root/.ssh/id_rsa root@192.168.1.64 /tmp/elkeid_check -n 1643379191 failed, err: exit status 1, stderr: 2022/01/28 22:13:18 ElkeidCheckErr:Failed to execute clock check, local time is 1643379191, remote time is 1643379198
2022/01/28 22:13:18 clock check error,  2022/01/28 22:13:18 ElkeidCheckErr:Failed to execute clock check, local time is 1643379191, remote time is 1643379198
2022/01/28 22:13:18 clock check error

**To Reproduce**
1. ./elkeidup deploy --package package_community/ --config ./elkeid_server.yaml

**elkeid_server.yaml**
redis:
  install: true
  ssh_host:
    - 192.168.1.64

mongodb:
  install: true
  ssh_host:
    - 192.168.1.64

kafka:
  install: true
  ssh_host:
    - 192.168.1.64

nginx:
  install: true
  ssh_host: 192.168.1.64
  domain:
  public_addr:

service_discovery:
  install: true
  ssh_host:
    - 192.168.1.64

hub:
  install: true
  ssh_host: 192.168.1.64

manager:
  install: true
  ssh_host:
    - 192.168.1.64

agent_center:
  install: true
  ssh_host:
    - 192.168.1.64

**Deployment mode**
Local deployment

**OS information (please complete the following information):**
 - Distribution: CentOS
 - Version 7.6
 - Kernel info 3.10.0-957.el7.x86_64

**Comment by TaeRoen** [comment]
The timeout is 3 second when elkeidup execute ssh command.
Maybe there is something wrong in your PAM default configuration, you can refer to [https://serverfault.com/questions/815538/long-delay-when-logging-in-with-centos7](https://serverfault.com/questions/815538/long-delay-when-logging-in-with-centos7) 
Or you can add the following content to your ~/.ssh/config 
```
Host *
    ControlMaster auto
    ControlPath /tmp/ssh_mux_%h_%p_%r
    ControlPersist 600
```

**Comment by bigger-boss** [comment]
> The timeout is 3 second when elkeidup execute ssh command. Maybe there is something wrong in your PAM default configuration, you can refer to https://serverfault.com/questions/815538/long-delay-when-logging-in-with-centos7 Or you can add the following content to your ~/.ssh/config
> 
> ```
> Host *
>     ControlMaster auto
>     ControlPath /tmp/ssh_mux_%h_%p_%r
>     ControlPersist 600
> ```

很有用！
