### ISSUE TITLE
自动部署组件redis出错

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#190]
执行./elkeidup deploy --package package_community/ --config ./elkeid_server.yaml 命令后

在安装redis的时候报错，环境是在本地一台机器上进行部署

![image](https://user-images.githubusercontent.com/99782519/154196272-8df3f3c1-e212-4f4d-91f0-3d1ecdf84507.png)

**Comment by TaeRoen** [comment]
@h253518892 麻烦分别执行下
systemctl status elkeid_redis
journalctl -fu elkeid_redis 
ps auxf | grep redis
ss -antp | grep 6379
看下为什么redis安装失败了

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154210596-8dae88e5-4743-4fc2-9ae4-78c6b9368f6c.png)

**Comment by TaeRoen** [comment]
@h253518892  看下 package_community/redis 和 /elkeid/redis 下面有没有 redis-server这个二进制文件。
package_community 文件夹是不是不完整，重新解压一遍看下?

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154212351-7b4a9ea7-8cd5-4cfe-9ee2-6354d0f8045b.png)
![image](https://user-images.githubusercontent.com/99782519/154212532-7d36b109-8563-42b8-b287-910e3f1920d8.png)
文件我看都是有的，我重新拉一下试试

**Comment by TaeRoen** [comment]
@h253518892 直接执行 /elkeid/redis/redis-server /elkeid/redis/redis.conf 看下报错吗？

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154213821-df5b09f3-d925-4885-9d6e-cebe8eef50f6.png)

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154215309-58d8ab63-24eb-42cf-a9e0-0f2cd0f87af2.png)

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154217271-3ce53dc7-8425-410a-aebf-cb90d37e3f19.png)

**Comment by TaeRoen** [comment]
@h253518892 现在systemctl restart elkeid_redis 试一下呢，看下redis这个服务能否正常？
目前不清楚systemd为什么在/elkeid/redis/redis-server文件正常的情况下依然报文件不存在，把系统信息贴一下吧，我们看下能否复现

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/154221289-aefcb0f8-3945-4f58-8eeb-f2406ec73b69.png)


系统信息：CentOS Linux release 7.9.2009 (Core)

**Comment by samcode123** [comment]
我也碰到这个问题了

**Comment by TaeRoen** [comment]
@samcode123  
麻烦看下systemctl status elkeid_redis 的错误提示，也是找不到redis-server可执行文件吗？
同时 ls -al /elkeid/redis 看下文件大小及权限。

**Comment by samcode123** [comment]
提示eb 17 18:39:54 localhost.localdomain systemd[25820]: Failed at step CHDIR spawning /elkeid/redis/redis-server: No such file or directory

[root@localhost system]# ls -al /elkeid/redis
total 28156
drwxr-xr-x  2 redis redis     297 Feb 17 18:39 .
drwxr-xr-x. 4 root  root       53 Feb 17 18:39 ..
-rwxr-xr-x  1 redis redis     286 Feb 17 18:39 install_sentinel.sh
-rwxr-xr-x  1 redis redis     404 Feb 17 18:39 install.sh
-rwxr-xr-x  1 redis redis 4830000 Feb 17 18:39 redis-benchmark
-rwxr-xr-x  1 redis redis 5002840 Feb 17 18:39 redis-cli
-rwxr-xr-x  1 redis redis    1846 Feb 17 18:39 redis.conf
-rwxr-xr-x  1 redis redis    1846 Feb 17 18:39 redis.confn
-rwxr-xr-x  1 redis redis 9478136 Feb 17 18:39 redis-sentinel
-rwxr-xr-x  1 redis redis     512 Feb 17 18:39 redis_sentinel.conf
-rwxr-xr-x  1 redis redis     555 Feb 17 18:39 redis_sentinel.service
-rwxr-xr-x  1 redis redis 9478136 Feb 17 18:39 redis-server
-rwxr-xr-x  1 redis redis     528 Feb 17 18:39 redis.service
-rwxr-xr-x  1 redis redis     231 Feb 17 18:39 uninstall_sentinel.sh
-rwxr-xr-x  1 redis redis     221 Feb 17 18:39 uninstall.sh

**Comment by UgOrange** [comment]
如果出现这个问题，可以尝试该临时解决方案：
在安装前修改package目录下redis/redis.service，将如下两行去掉
`ProtectHome=yes
ProtectSystem=true`
重新安装即可。
