### ISSUE TITLE
Red Hat 8.2 系统下通过ElkeidUP自动化部署报错

### ISSUE THREAD

**Issue by charlesren** [bytedance/Elkeid#192]
报错日志如下：

[ERRO]	2022-02-18T08:36:17+08:00	when deploying, an error occurred: Checker installed faield: check failed when check node, err: %!w(<nil>), start check os
unknown centos version Linux, exit...
cannot fix for os
ElkeidCheckFailed os
start check selinux
start check selinux
selinux is Disabled, check success
start check swap
swap is opened, size 8388604 kB, need to close...
try fix check for swap
start fix swap
fix success for swap
start check ulimit
the maximum number of open fd is 1024, less then 65536, need to fix
try fix check for ulimit
start fix ulimit
fix success for ulimit
start check firewall
Unit ufw.service could not be found.
not detected firewall daemon, continue...
start check command 

Elkeidup 部署说明里有如下提示：
The backend server used for deployment can only be used: Centos7 and above; Ubuntu16 and above; Debian9 and above

支持centos7及以上，请问支持redhat 8 吗？

**Comment by TaeRoen** [comment]
@charlesren 麻烦cat下 /etc/redhat-release  这个文件看下
我们支持redhat 8，但是测试的时候没有redhat 8，应该是版本描述文件解释的不对

**Comment by charlesren** [comment]
@TaeRoen 
[root@redhat82 data]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.2 (Ootpa)
[root@redhat82 data]#

**Comment by TaeRoen** [comment]
@charlesren 
先临时把 package_community/checker/os_check.sh 的 22行的 awk '{print $4}' 改为 awk '{print $6}' 吧，可以跳过检查

**Comment by charlesren** [comment]
跳过后，能够安装完成，但 elkeid_hub是inactive 状态

[root@redhat82 data]# ./elkeidup status
[INFO]	2022-02-18T17:07:10+08:00	Used ElkeidUP home dir :/root/.elkeidup
[INFO]	2022-02-18T17:07:10+08:00	elkeid has been deployed, using config file: /root/.elkeidup/elkeid_server.yaml
[INFO]	2022-02-18T17:07:10+08:00	Start to check the Checker configuration
[SUCC]	2022-02-18T17:07:10+08:00	The Checker pass the test.
[INFO]	2022-02-18T17:07:10+08:00	Start to check the Redis configuration
[INFO]	2022-02-18T17:07:11+08:00	create random redis password: ir170edesf9k934m35
[SUCC]	2022-02-18T17:07:14+08:00	The Redis pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Kafka configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Kafka pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Mongodb configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Mongodb pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Service Discovery configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Service Discovery pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Manager configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Manager pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Agent Center configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Agent Center pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the HUB configuration
[SUCC]	2022-02-18T17:07:14+08:00	The HUB pass the test.
[INFO]	2022-02-18T17:07:14+08:00	Start to check the Nginx configuration
[SUCC]	2022-02-18T17:07:14+08:00	The Nginx pass the test.
[WARN]	2022-02-18T17:07:14+08:00	The password file is in /root/.elkeidup/elkeid_passwd, please be sure to transfer, save and delete the file!
[INFO]	2022-02-18T17:07:14+08:00	Redis:
[SUCC]	2022-02-18T17:07:14+08:00		10.193.84.94 elkeid_redis active
[INFO]	2022-02-18T17:07:14+08:00	Mongodb:
[SUCC]	2022-02-18T17:07:15+08:00		10.193.84.94 elkeid_mongodb active
[INFO]	2022-02-18T17:07:15+08:00	Zookeeper:
[SUCC]	2022-02-18T17:07:15+08:00		10.193.84.94 elkeid_zk active
[INFO]	2022-02-18T17:07:15+08:00	Kafka:
[SUCC]	2022-02-18T17:07:16+08:00		10.193.84.94 elkeid_kafka active
[INFO]	2022-02-18T17:07:16+08:00	Nginx:
[SUCC]	2022-02-18T17:07:16+08:00		10.193.84.94 elkeid_nginx active
[INFO]	2022-02-18T17:07:16+08:00	Agent Center:
[SUCC]	2022-02-18T17:07:17+08:00		10.193.84.94 elkeid_ac active
[INFO]	2022-02-18T17:07:17+08:00	Agent Center:
[SUCC]	2022-02-18T17:07:17+08:00		10.193.84.94 elkeid_manager active
[INFO]	2022-02-18T17:07:17+08:00	Service Discovery:
[SUCC]	2022-02-18T17:07:18+08:00		10.193.84.94 elkeid_sd active
[ERRO]	2022-02-18T17:07:18+08:00		10.193.84.94 elkeid_hub SSH Connect Error: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 -i /root/.ssh/id_rsa root@10.193.84.94 systemctl is-active elkeid_hub failed, err: exit status 3, stderr: 
[INFO]	2022-02-18T17:07:18+08:00	Nginx:
[SUCC]	2022-02-18T17:07:19+08:00		10.193.84.94 elkeid_nginx active
[root@redhat82 data]# systemctl is-active elkeid_hub
inactive
[root@redhat82 data]#

**Comment by charlesren** [comment]
[root@redhat82 hub]# pwd
/data/package_community/hub
[root@redhat82 hub]# ls
bootstrap.sh  bootstrap.shn  config  elkeid_hub.service  hub.zip  install.sh  smith.yml  smith.ymln  uninstall.sh  update.sh  zip
[root@redhat82 hub]# sh ./install.sh 
unknow
./install.sh: line 37: [: ==: unary operator expected
./install.sh: line 39: [: ==: unary operator expected
Error: 未找到 apt 与 yum 命令
[root@redhat82 hub]#

[root@redhat82 hub]# cat install.sh
...
INSTALL_GCC(){
  if [ $PM == 'apt' ]; then
      apt-get -y install gcc > /dev/null
  elif [ $PM == 'yum' ]; then
      yum install -y gcc > /dev/null
  else
      echo "Error: 未找到 apt 与 yum 命令" >&2;
      exit 1;
  fi
}
...

**报错原因为安装hub时需要检查安装gcc、sqlite-devel等依赖，可根据情况修改脚本跳过**
通过如下命令安装成功
[root@redhat82 hub]# command -v gcc &>/dev/null
[root@redhat82 hub]# echo $?
1
[root@redhat82 hub]# command -v zip &>/dev/null
[root@redhat82 hub]# echo $?
0
[root@redhat82 hub]# cp /elkeid/hub/zip /usr/local/bin/
[root@redhat82 hub]# chmod +x /elkeid/hub/bin/elkeid_hub
[root@redhat82 hub]# chmod +x /elkeid/hub/bootstrap.sh
[root@redhat82 hub]# rm -f /etc/systemd/system/elkeid_hub.service
[root@redhat82 hub]# cp /elkeid/hub/elkeid_hub.service /etc/systemd/system/elkeid_hub.service
[root@redhat82 hub]# systemctl daemon-reload
[root@redhat82 hub]# systemctl enable elkeid_hub
Created symlink /etc/systemd/system/multi-user.target.wants/elkeid_hub.service → /etc/systemd/system/elkeid_hub.service.
[root@redhat82 hub]# systemctl start elkeid_hub
[root@redhat82 hub]# systemctl status elkeid_hub
● elkeid_hub.service - Elkeid HUB
   Loaded: loaded (/etc/systemd/system/elkeid_hub.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-02-18 17:30:57 CST; 12s ago
 Main PID: 4073453 (bash)
    Tasks: 14 (limit: 100687)
   Memory: 83.7M
   CGroup: /system.slice/elkeid_hub.service
           ├─4073453 /bin/bash /elkeid/hub/bootstrap.sh
           └─4073463 /elkeid/hub/bin/elkeid_hub -c /elkeid/hub/config/ -p 8091

Feb 18 17:30:57 redhat82 systemd[1]: Started Elkeid HUB.
Feb 18 17:30:57 redhat82 bash[4073453]: [AgentSmith] SMITH START
[root@redhat82 hub]# 


问题已解决，谢谢！！！
