### ISSUE TITLE
agent_center在启动时报错kafka报错

### ISSUE THREAD

**Issue by haolipeng** [bytedance/Elkeid#193]
使用systemctl start elkeid_ac启动服务
查看 /opt/Elkeid_AC/log/svr.log 文件，有如下错误

{"level":"info","ts":1645589215.0774703,"msg":"InitComponents","info":"KAFKA Producer: [127.0.0.1:9092] - hids_svr"}
{"level":"error","ts":1645589215.8380973,"msg":"KAFKA","info":"NewClient error:kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
{"level":"fatal","ts":1645589215.838166,"msg":"InitComponents","info":"[127.0.0.1:9092] hids_svr CONNECT_KAFKA_ERROR: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
请教下是因为什么原因导致的？

1、kafka是否启动成功？
使用发送消息和接受消息的方法来测试kafa是否工作正常，kafka是ok的！！
发送消息
bin/kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic hids_svr
> {"info":"test"}

接收消息
bin/kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic hids_svr --from-beginning

![image](https://user-images.githubusercontent.com/6583143/155260717-573bcd5d-70af-403b-b9a1-78eea42000a5.png)
![image](https://user-images.githubusercontent.com/6583143/155260735-f5d491d7-8beb-4ec9-b4ba-7859b8e76ef4.png)

2、agent_center配置问题？
conf/svr.yml配置文件内容如下

manage:
  addrs:
    - 192.168.101.84:6701

sd:
  name: hids_svr
  addrs:
    - 192.168.101.84:8088
  auth:
    ak: 91728dc875a94ae2
    sk: 5208f7426cf34234ba200b9111fcd4a8

############################# Kafka Settings #############################
kafka:
  addrs:
    - 127.0.0.1:9092
  topic: hids_svr
  sasl:
    enable: true
    username: user
    password: password
  logpath: ./log/sarama.log

server:
  log:
    applog:
      path: ./log/svr.log
      loglevel: 0

  ssl:
    keyfile: ./conf/server.key
    certfile: ./conf/server.crt
    cafile: ./conf/ca.crt

  grpc:
    port: 6751
    connlimit: 1500

  http:
    port: 6752
    auth:
      enable: true
      aksk:
        888025e5cc0a4142: e01a7f78be1747e2bb41286cb80c3249
    ssl:
      enable: true

  pprof:
    enable: true
    port: 6753

**Comment by EBWi11** [comment]
elkeid_server.yaml 中kafka是127.0.0.1么

**Comment by haolipeng** [comment]
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.3505294,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.3505764,"msg":"Sarama","info":"client/metadata retrying after 250ms... (2 attempts remaining)\n"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.601314,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6053958,"msg":"Sarama","info":"Invalid SASL Mechanism : kafka server: Request is not valid given the current SASL>
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6055863,"msg":"Sarama","info":"Error while performing SASL handshake 127.0.0.1:9092\n"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.605728,"msg":"Sarama","info":"Closed connection to broker 127.0.0.1:9092\n"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6059043,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: kafka server: Re>
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6059623,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6060705,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
2月 23 13:49:47 ubuntu agent_center[7660]: {"level":"info","ts":1645595387.6061194,"msg":"Sarama","info":"client/metadata retrying after 250ms... (1 attempts remaining)\n"}
感觉和SASL鉴权有关

**Comment by haolipeng** [comment]
> 

是的，kafka的地址是填写的127.0.0.1

**Comment by kelpiezqc** [comment]
> > 
> 
> 是的，kafka的地址是填写的127.0.0.1

请问问题解决了吗？我也遇到了同样的问题
