### ISSUE TITLE
关于rasp中jvm agent更新与卸载的问题

### ISSUE THREAD

**Issue by HsinTsao** [bytedance/Elkeid#199]
您好，感谢作者们的辛勤付出！目前正在阅读和学习该开源项目。

想请教几个问题，对于rasp中jvm agent注入：

1. 是否支持卸载该agent，或者更新agent？

2. 以下防止重复注入的代码逻辑，是否也会防止agent的更新？

```
        String probe = System.getProperty("rasp.probe");

        if (probe != null) {
            SmithLogger.logger.info("probe running");
            return;
        }
```

3. 目前以下代码可以控制agent是否生效，请问可以完全卸载这个jar吗？
```
public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) {
        if (disable)
            return null;
```

**Comment by Hackerl** [comment]
1. 不支持卸载和升级，但可以自行实现，可以封装一层 wrapper 进行注入，wrapper 使用 classloader 加载实际的 agent，并控制升级
2. 没有更新功能，只是防止重复注入
3. 可以通过协议卸载所有 hook 点，无法卸载 jar

**Comment by HsinTsao** [comment]
感谢解答！
很赞同你的建议，agent不应该频繁变动。若需要更新规则，应当通过配置的方法。
