### ISSUE TITLE
Protect your self

### ISSUE THREAD

**Issue by rdwnsjjd** [bytedance/Elkeid#200]
How does your program protect itself?
do you perform a self-protection method?

**Comment by EBWi11** [comment]
The driver module has EXIT_PROTECT define to protect the driver module from being unloaded, it is disabled by default. Considering that the large-scale deployment of the production environment also needs to consider cooperation with teams such as devops, protecting yourself by any means of hacking may make it difficult for other teams to work, such as troubleshooting problems and need to quickly close HIDS
