### ISSUE TITLE
更改manager前端 nginx访问端口后无法启动nginx

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid#201]
把manager前端访问端口8082 更改为 80后，nginx服务无法启动，有如下报错
```
[root@iZ2z nginx]# /elkeid/nginx/nginx/nginx -c /elkeid/nginx/nginx/nginx.conf
nginx: [emerg] getpwnam("nobody") disabled for static build (38: Function not implemented)
```
![image](https://user-images.githubusercontent.com/8515198/157210198-33dc259f-7c96-4e7f-b758-9989bd630358.png)

**OS information (please complete the following information):**
 - Distribution: [e.g. centos 7]
 - Kernel info [3.10.0-1160.53.1.el7.x86_64]

**Comment by EBWi11** [comment]
请不要修改任何默认配置，这个问题是由于该静态编译的Nginx无法使用root启动导致的，请用systemd restart elkeid_nginx来进行重启。另请不要轻易修改任何配置，除非你非常清楚整个自动化部署的细节，谢谢
