### ISSUE TITLE
elkeid_manage和elkeid_nginx未放在一个服务器导致跨域问题

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid#202]
manage server :10.x.x.44
nginx server     :10.x.x.14

已知：
* elkeid_manage 服务器地址 硬编码在elkeid_console 中
* elkeid_console 访问端口是8082
* 我司只开放80、443给外访

基于以上条件 ，我通过在elkeid_nginx的服务器又安装了一个nginx，用来做转发配置如下：
```
load_module /usr/lib64/nginx/modules/ngx_stream_module.so;
worker_processes  4;

events {
    worker_connections  4096;
}

http {
   server{
          listen 80;
          listen [::]:80;
          server_name 10.x.x.14;
          location / {
                  proxy_pass http://10.x.x.14:8082/;
                  add_header Access-Control-Allow-Origin *;
                  add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
                  add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
          }
   }
}
```

测试发现无法访问manage相关接口，如下图
![微信图片_20220309122011](https://user-images.githubusercontent.com/8515198/157372089-bd3d4622-ff5a-4c0c-80bf-8ed100e237b7.png)

在elkeid_manager上测试接口是正常可访问的：
```
[root@iZze conf]# curl -X POST -d '{"username":"1123","password":"123"}' http://10.x.x.44:6701/api/v1/user/login
{"code":1,"msg":"auth failed","data":null}
```

问题：
在此种情况下要怎么实现elkeid_console正常访问elkeid_manager接口呢？

**Comment by hugebomb** [comment]
这里看到有2个问题：

**Comment by hugebomb** [comment]
manager监听再6701端口，也需要用nginx将其转发出来。并且把elkeid_console前端代码里面所有的x.x.x.x:6701(旧的manger地址)替换成你的新地址。

**Comment by EBWi11** [comment]
可以试下把elkeid_nginx conf(我记着是在 /elkeid/nginx/nginx/nginx.conf) 里的8082 改成80，然后systemctl restar elkeid_nginx

**Comment by 0xlwoe21k** [comment]
fix
