### ISSUE TITLE
cgroup方式管理agent超内存直接kill是否合理

### ISSUE THREAD

**Issue by hz-kelpie** [bytedance/Elkeid#204]
目前在试用deloy中的cgroup方式，发现当service内存OOM就会kill 占用最高的进程

是否有办法让服务full of memery运行 而不是触发out of memery

**Comment by hz-kelpie** [comment]
MemoryHigh 是否比MemoryLimit/MemoryMax 更合理

**Comment by Serinalice** [comment]
MemoryHigh 只是控制在内存达到一定程度后促进内存释放给系统
而MemoryLimit是为了设置最后一道防线，防止发生内存泄漏等异常case的时候影响到正常业务
MemoryHigh可以按需设置，但意义不是很大，但MemoryLimit必须设置
换句话说，当因为MemoryLimit被OOM Killer杀死的时候，就需要排查具体原因了，属于异常case
