### ISSUE TITLE
elkeid安装成功后，异常

### ISSUE THREAD

**Issue by edubob** [bytedance/Elkeid#205]
通过elkeidup快速安装后，./elkeidup status状态全部正常。
打开server_ip:8082，直接进入overview页面不会自动跳转/user/login页面，手动打开/user/login页面，输入账号密码也无法登录。
通过manager接口，可以获取用户token，目前不知道是哪里的问题。

出问题的操作操作系统是:redhat 7.6，我在redhat7.4安装成功并可以正常运行。

查看hub日志，有如下异常：
{"level": "info","ip":"","flags": ("Prefix": "[FOR SIGNCHAN] "}, "time": "2022-03-21T10:11:02+08:00", "message": "wait"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}

**Comment by edubob** [comment]
补充：打开server_ip:8088，直接进入overview页面不会自动跳转/user/login页面，手动打开/user/login页面，输入账号密码也无法登录。

**Comment by edubob** [comment]
查看hub日志，有如下异常：
{"level": "info","ip":"","flags": ("Prefix": "[FOR SIGNCHAN] "}, "time": "2022-03-21T10:11:02+08:00", "message": "wait"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}
{"level": "error", "ip";"", "flags": ("Prefix": "[kafka consumer[: example_rule;asset_to manager|Input|hids] "} "time": "2022-03-21T10:11:03+08:00", "message":"
subscribed topic not available: hids_svr: Broker: Unknown topic or partition"}

**Comment by edubob** [comment]
补充下：是8082端口，不是8088哈

**Comment by EBWi11** [comment]
不会自动跳转/user/login的问题是前后端分离导致需要可以访问到 manager:6701

**Comment by edubob** [comment]
> 不会自动跳转/user/login的问题是前后端分离导致，需要可以访问到 manager:6701，麻烦F12看下是否存在网络问题无法访问到后端API

由于是在公司内网部署的，有水印，不方便提供图片。F12中查看，Login请求没有收到返回，response处为“Failed to load response data”
elkeid是在单台主机上部署的，前后端应该没有防火墙的限制。
终端的话，只开了浏览器所在终端到elkeid服务端的8082，跟终端到服务端的防火墙有关系吗？

**Comment by EBWi11** [comment]
你再PC上curl下server_ip:6701看下是否通的，如果不通先按公司内网络策略，服务器默认网络策略来排查

**Comment by TaeRoen** [comment]
@edubob 可能是kafka有问题 systemctl status elkeid_kafka 看下

**Comment by edubob** [comment]
> 你再PC上curl下server_ip:6701看下是否通的，如果不通先按公司内网络策略，服务器默认网络策略来排查

@EBWi11 开通PC机到server_ip:6701的网络策略后，可以正常访问了。
但是理解不了，前后端分离，Nginx和Manger在同一台服务器上，怎么会跟PC机到server_ip:6701的防火墙策略有关呢，可否解答下，谢谢

**Comment by edubob** [comment]
> @edubob 可能是kafka有问题 systemctl status elkeid_kafka 看下

你好，问题已解决，
