### ISSUE TITLE
安装部署

### ISSUE THREAD

**Issue by YunZezzZ** [bytedance/Elkeid#212]
你好,请问有没有编译安装的手册,在虚拟机上使用elkeidup安装,提示格式错误,目前使用的系统 ubuntu-linux-20-04-desktop  aarch64

**Comment by EBWi11** [comment]
@YunZezzZ 麻烦提供具体报错，否则无法定位问题

**Comment by YunZezzZ** [comment]
![image](https://user-images.githubusercontent.com/44561725/162695431-0f7053f4-39b9-4981-af4f-3defd75ee5f4.png)
这个是错误的具体信息,麻烦帮忙解决一下,谢谢

> @YunZezzZ提供具体报错，否则无法解决问题

**Comment by EBWi11** [comment]
你这个elkeidup都不是elf，哪里下载的？

**Comment by YunZezzZ** [comment]
> 你这个elkeidup都不是elf，哪里下载的？

通过文档中快速部署的wget https://github.com/bytedance/Elkeid/releases/download/v1.7/elkeidup下载的文件

**Comment by EBWi11** [comment]
看下md5是不是6cba2bcc3ab594381418a1ac42efdd2e，如果不是重新下载下

**Comment by YunZezzZ** [comment]
> 看下md5是不是6cba2bcc3ab594381418a1ac42efdd2e，如果不是重新下载下

![image](https://user-images.githubusercontent.com/44561725/162853531-d4318628-b740-4528-801a-c515de785a0c.png)
6cba2bcc3ab594381418a1ac42efdd2e  elkeidup
md5值是相同的

**Comment by Hackerl** [comment]
> ![image](https://user-images.githubusercontent.com/44561725/162695431-0f7053f4-39b9-4981-af4f-3defd75ee5f4.png) 这个是错误的具体信息,麻烦帮忙解决一下,谢谢
> 
> > @YunZezzZ提供具体报错，否则无法解决问题

你这是 aarch64，elkeidup是x64的

**Comment by YunZezzZ** [comment]
所以我最开始的问题是有没有编译安装的手册呀 @Hackerl

**Comment by EBWi11** [comment]
没有 @YunZezzZ
