### ISSUE TITLE
不支持cgroup的机器被舍弃了吗？

### ISSUE THREAD

**Issue by hz-kelpie** [bytedance/Elkeid#218]
按照1.7的安装脚本，如果cgroup mount失败会直接exit ，是策略上放弃了这部分机器吗？

**Comment by Serinalice** [comment]
目前是的，为了保证elkeid在生产环境开箱即用，所以目前必须依赖cgroup进行性能兜底。
如果有需要，也可以自行去除相关限制逻辑。
