### ISSUE TITLE
Got a wrong short file path

### ISSUE THREAD

**Issue by bestplay** [bytedance/Elkeid#225]
when I created a file at /tmp/test.txt, i got a wrong short file path: /test.tx.

我单独运行 driver 的内核模块，然后从 /proc/elkeid-endpoint 读取消息。
结果所有的创建文件的路径都变短了。
创建文件：/home/user/test.txt ，日志中路径变成：/user/test.txt
创建文件：/tmp/test.txt ，日志中路径变成：/test.txt

是的，我有注意到最后一个字段 sb_id 跟文件系统关联，但我不知道怎么把 sb_id 转换成文件系统的挂载路径（我需要组装完整的路径）希望得到解答，感谢

**Comment by EBWi11** [comment]
sb_id 是super_block->s_id，这个目前会重复且不能代表具体的super_block信息。目前没有好的办法，需要自行修改driver security_inode_create_pre_handler 部分修改获取路径的方式，可以使用d_absolute_path替换现有的dentry_path_raw，不过该函数需要导出。
