### ISSUE TITLE
elkeid_console可以监测到agent的心跳并更新，但获取不到资产数据包

### ISSUE THREAD

**Issue by dongfangliuyihong** [bytedance/Elkeid#227]
**Describe the bug**
agent中的心跳包可以监测到并更新，但无法获取到agent的collector组件采集的数据包

**To Reproduce**
1. 使用elkeidup部署elkeid架构，两台AC,两台SD，两台Manager,一台agent,其余的hub、kafka、mongodb、redis、nginx都在一台上。成功部署后，在console的web界面上，可以看到agent的在线状态，并周期性更新的活跃时间。此外，确保各项服务都正常开启，组件都正常运行。
2. 点击该agent可查看该主机概览信息，点击资产指纹，【等待了一段时间】却没有任何数据。经查collector组件日志，发现已经正常采集到数据。
3. 
![image](https://user-images.githubusercontent.com/20365580/164392343-ea717a7c-8e4e-49ac-99ec-614d00edb273.png)
![image](https://user-images.githubusercontent.com/20365580/164392817-a25d93fb-614a-40f6-b17b-dc1f28fa1b91.png)
![image](https://user-images.githubusercontent.com/20365580/164393630-76d9012d-2fc7-4f64-b513-b843d58ab1e0.png)

4. 此外，经检查，ac和manager日志中也均为info正常记录，无错误。经查kafka中可解析获得其他类型数据包
![image](https://user-images.githubusercontent.com/20365580/164393953-31462802-41e6-423a-8b0a-d75f695334bb.png)

5.sarama日志中也均为info
![ZOp7DzXp6Q](https://user-images.githubusercontent.com/20365580/164394211-9d1eb187-de96-4574-be39-5004d82ff3f6.png)

**Comment by EBWi11** [comment]
1. 是全部机器都没有资产数据还是部分机器没有资产数据，可否装几台较新的机器看下是否可以看到资产数据
2. 告警数据可以正常看到吗？建议在部署agent的机器上进行真实的bash -i反弹shell查看是否有告警
3. 查看下hub的日志是否存在报错

**Comment by dongfangliuyihong** [comment]
![image](https://user-images.githubusercontent.com/20365580/164624529-b995492f-4a2a-49d9-b497-f0fcc145f2e4.png)
![image](https://user-images.githubusercontent.com/20365580/164624598-99ae622b-1038-46ed-a114-61929d698ee4.png)
![image](https://user-images.githubusercontent.com/20365580/164624644-a07eac81-b81a-4ffd-96ad-18f287fa6d39.png)
![image](https://user-images.githubusercontent.com/20365580/164624713-d674190f-37c3-47a1-915d-539eda1122ce.png)
1：可以检测到agent心跳更新，无法获取资产指纹，所有的agent都一样
2：agent上主机登录等操作也能在kafka中获取到
3：hub中貌似有几个error,应该是初始化的运行超时问题。
![image](https://user-images.githubusercontent.com/20365580/164625611-1a81e8c3-6d4a-45ca-a76d-2a44cb96057a.png)

**Comment by TaeRoen** [comment]
@dongfangliuyihong 看下有 /elkeid/hub/py/plugin.stdout 这个文件吗? 或者在/elkeid/hub目录下搜一下有没有 plugin.stdout 这个文件, 看下文件内容

**Comment by dongfangliuyihong** [comment]
![image](https://user-images.githubusercontent.com/20365580/164627110-c69487a0-72a5-48ff-ac45-31622067220b.png)
对了，还有个这个错误
