### ISSUE TITLE
@dongfangliuyihong 看下有 /elkeid/hub/py/plugin.stdout 这个文件吗? 或者在/elkeid/hub目录下搜一下有没有 plugin.stdout 这个文件, 看下文件内容

### ISSUE THREAD

**Issue by dongfangliuyihong** [bytedance/Elkeid#228]
@dongfangliuyihong 看下有 /elkeid/hub/py/plugin.stdout 这个文件吗? 或者在/elkeid/hub目录下搜一下有没有 plugin.stdout 这个文件, 看下文件内容

_Originally posted by @TaeRoen in https://github.com/bytedance/Elkeid/issues/227#issuecomment-1106100924_

有这个文件，稍等我贴出来

**Comment by dongfangliuyihong** [comment]
![image](https://user-images.githubusercontent.com/20365580/164627753-a98afd27-1221-48b4-aefe-c939e4387575.png)

**Comment by dongfangliuyihong** [comment]
我貌似发现问题，缺少了elkeid.sock文件
![image](https://user-images.githubusercontent.com/20365580/164628020-8c916db6-dc19-492c-84b7-c57d8ba0ab31.png)
正常的应该是
![image](https://user-images.githubusercontent.com/20365580/164628104-40513802-d3f1-40e9-8201-b16505f36c77.png)

**Comment by TaeRoen** [comment]
@dongfangliuyihong 这个文件是hub进程和python进程通信的socket文件, 没有这个文件一般是python进程启动报错了, 所以看下plugin.stdout这个文件, 这个是python文件的标准输出, 看下威慑报错

**Comment by dongfangliuyihong** [comment]
![image](https://user-images.githubusercontent.com/20365580/164628644-70bbe917-51de-4305-98ab-cabee9c8a87e.png)
这个是不是应为gcc不存在的问题

**Comment by TaeRoen** [comment]
@dongfangliuyihong 可能是, 安装hub的时候会尝试安装gcc等编译工具链的, 是不是包管理当时不可用

**Comment by dongfangliuyihong** [comment]
应该是，系统是新装的。更新一下软件源应该就可以了。我重新安装一下试试。
