### ISSUE TITLE
agent部署

### ISSUE THREAD

**Issue by minYangFu** [bytedance/Elkeid#229]
![jjHTEKZsFw](https://user-images.githubusercontent.com/100768772/164628923-0fda6b02-6782-4380-b679-aa4cafbef217.png)
在主机1部署完成后

然后在主机2部署agent，按照我图里选中的步骤，而且提示成功

但在web端却看不到，只有主机1的列表

请问在 elkeid_server.yaml中要填的ip是主机1的还是主机2的？

谢谢～

**Comment by Serinalice** [comment]
> 在主机1部署完成后
部署指的是安装Agent？那直接在主机2上翘命令安装Agent即可。
后端只用部署一次，不用管elkeid_server.yaml了

**Comment by minYangFu** [comment]
主机1部署了全部步骤，主机2只部署了我选中的步骤

**Comment by Serinalice** [comment]
这个是部署后端组件的流程，只用执行一次。后续Agent部署，在Console上找一下安装命令，在其他主机上执行命令即可。

**Comment by minYangFu** [comment]
> 这个是部署后端组件的流程，只用执行一次。后续Agent部署，在Console上找一下安装命令，在其他主机上执行命令即可。

![image](https://user-images.githubusercontent.com/100768772/164639998-6894c4c1-cd56-49fc-a0ea-f814c2045b67.png)
agent只要这一步就可以吗，不需要./elkeidup agent build --package package_community/这一步的编译是吧？

另外如果只要bash -c "if (command -v curl); then (curl -sS 10.81.134.110:8080/agent/install.sh | bash);else (wget -q -O - 10.81.134.110:8080/agent/install.sh | bash); fi"这么安装agent，那其他插件是不是不会安装？

**Comment by Serinalice** [comment]
* 不需要
* 会安装

**Comment by minYangFu** [comment]
可是我在其他的机器上执行bash -c "if (command -v curl); then (curl -sS 10.81.134.110:8080/agent/install.sh | bash);else (wget -q -O - 10.81.134.110:8080/agent/install.sh | bash); fi"agent安装，能安装成功，服务也正常启动，但在web上没有找到相关agent。

![image](https://user-images.githubusercontent.com/100768772/164650550-07031cb0-aad2-419e-9d37-a5f248e625d1.png)
![image](https://user-images.githubusercontent.com/100768772/164650696-fc69946f-e8f0-4b9c-b64a-53d63b3ea9b0.png)

**Comment by Serinalice** [comment]
cat /etc/elkeid/log/elkeid-agent.log

**Comment by minYangFu** [comment]
![image](https://user-images.githubusercontent.com/100768772/164658810-31e70cb7-351b-40cd-b81b-3f251e7a5d00.png)

**Comment by Serinalice** [comment]
后端是部署在10.81.134.110上的吗？

**Comment by minYangFu** [comment]
是的

**Comment by minYangFu** [comment]
所以请问下我应该agent机器上做什么其他操作？

**Comment by Serinalice** [comment]
看起来是证书的问题，但比较奇怪的是一台可以，一台不可以
两台机器安装命令一致吗？

**Comment by minYangFu** [comment]
是一样的，不过node79是执行过了ElkeidUP，因为它同时也部署了后端。所以agent安装除了只执行bash -c "if (command -v curl); then (curl -sS 10.81.134.110:8080/agent/install.sh | bash);else (wget -q -O - 10.81.134.110:8080/agent/install.sh | bash); fi"这一步，还需要做证书处理吗？

**Comment by Serinalice** [comment]
node79的IP是10.81.146.110 但是上面说过后端部署在10.81.134.110
所以现在看来是你部署了两套后端？

**Comment by minYangFu** [comment]
后端值部署了一套就是110（node79）。但同时我也在110上面安装了agent。

我想在其他机器上安装agent，就出现了上面的问题。

**Comment by Serinalice** [comment]
那应该执行的是下面这个吧？
```
bash -c "if (command -v curl); then (curl -sS 10.81.146.110:8080/agent/install.sh | bash);else (wget -q -O - 10.81.134.110:8080/agent/install.sh | bash);
```

**Comment by minYangFu** [comment]
是的。
![image](https://user-images.githubusercontent.com/100768772/164953431-2574e45d-7890-435d-b499-3af22c86b500.png)

**Comment by minYangFu** [comment]
![image](https://user-images.githubusercontent.com/100768772/164953497-326a9971-6326-4886-9999-09b75b92869e.png)
![image](https://user-images.githubusercontent.com/100768772/164953509-459aa07f-30d7-41fd-bc10-2495238d1c02.png)

**Comment by Serinalice** [comment]
你仔细看下，两个110的IP不一样的

**Comment by minYangFu** [comment]
> node79的IP是10.81.146.110 但是上面说过后端部署在10.81.134.110 所以现在看来是你部署了两套后端？

node79的IP是10.81.134.110。sorry

**Comment by Serinalice** [comment]
了解，可以再找一台机器确认一下能否跑起来吗？

**Comment by Serinalice** [comment]
或者尝试卸载掉node79的agent，然后用相同命令重装，看下有无异常

**Comment by minYangFu** [comment]
好的，我试一下。node79有两个ip，但我在node79安装后端和agent的时候都是用的10.81.134.110
![image](https://user-images.githubusercontent.com/100768772/164953857-b6807504-c6cc-428d-8f19-c2eba6140d3c.png)

请问下我在node79上面卸载agent之后，多久之后在页面上会消失？谢谢

![image](https://user-images.githubusercontent.com/100768772/164954019-938e54bc-a668-4e52-b062-e618616b2f0c.png)

**Comment by minYangFu** [comment]
我换了台机器测试重新部署就没啥问题，所以这个就先不管了。

辛苦你这两天的及时反馈，多谢字节老哥！

**Comment by Serinalice** [comment]
嗯嗯 考虑是不是机器自身证书链什么的没安装。
