### ISSUE TITLE
通过elkeidup自动化部署的如何卸载

### ISSUE THREAD

**Issue by minYangFu** [bytedance/Elkeid#230]
因为安装有问题，想重新部署，但部署时提示已经elkeid has been deployed，请问该如何卸载重新安装？

**Comment by EBWi11** [comment]
elkeidup undeploy
可以通过elkeidup help查看更多功能

**Comment by haolipeng** [comment]
虽然官方指南中说明了，安装图中不能强行中断，这种情况如何卸载

**Comment by EBWi11** [comment]
cp 你自己的配置文件 到  /root/.elkeidup/elkeid_server.yaml 然后再 elkeidup undeploy
