### ISSUE TITLE
功能测试

### ISSUE THREAD

**Issue by minYangFu** [bytedance/Elkeid#233]
想问下通过elkeidup自动安装的模块插件客户端具备哪些安全检测功能。

有功能测试的步骤吗（如挖矿、爆破之类），如果有请提供一下，万分感谢！

**Comment by EBWi11** [comment]
暂不提供，目前开源策略位于：https://github.com/bytedance/Elkeid-HUB/tree/main/config/elkeid_hids/ruleset
