### ISSUE TITLE
VPS部署elkeid server后无法登录

### ISSUE THREAD

**Issue by warcraft23** [bytedance/Elkeid#235]
公有云的VPS主机，其安全域放开了6701与8082端口访问，在部署了elkeid server后无法登录Console，F12查看确认为向内网IP提交了认证请求。

请问如何修改配置，可以通过公网IP提交认证请求

**Comment by UgOrange** [comment]
麻烦在安装nginx组件的机器，执行如下命令：（需要把对应地方改一下）
`sed -i 's|http://'内网ip:6701'|http://'公网ip:6701'|g' /elkeid/nginx/ElkeidConsole/*.js`
然后刷新一下页面就可以了

**Comment by warcraft23** [comment]
> 麻烦在安装nginx组件的机器，执行如下命令：（需要把对应地方改一下） `sed -i 's|http://'内网ip:6701'|http://'公网ip:6701'|g' /elkeid/nginx/ElkeidConsole/*.js` 然后刷新一下页面就可以了

此方案可行，感谢大佬。
修改后可登录系统，可查看已部署的Agent。
