### ISSUE TITLE
关于B类私有地址范围为172.16.0.0-172.31.255.255

### ISSUE THREAD

**Issue by dongfangliuyihong** [bytedance/Elkeid#237]
https://github.com/bytedance/Elkeid/blob/fa1e79f3ac6491b2d4a415bb03cb90545df571fb/agent/host/host.go#L43

ip4[1]&0x10 == 0x10 将包含16-255网段，此处判别条件应该是：ip4[1]&0xF0 == 0x10 如此才可以将网络段限制在16-31

**Comment by Serinalice** [comment]
Thanks for you report!
There should be:
```
(ip4[0] == 172 && ip4[1] > 15 && ip4[1] < 32)
```
Will fix in next version.

**Comment by dongfangliuyihong** [comment]
nice~

**Comment by Serinalice** [comment]
reopen until resolve this bug.
