### ISSUE TITLE
driver 在不同内核版本兼容性上的使用问题

### ISSUE THREAD

**Issue by ciphersaw** [bytedance/Elkeid#238]
## 背景

1）部署环境内的主机，存在上百种不同的 `$(uname -r)` 内核版本 。

2）根据实际场景，需二次开发调整 driver 功能。

## 问题

1）内核版本前三组数字相同的主机，能否统一使用相同的 hids_driver.ko 文件？

例如，部署环境内的主机，存在以下内核版本，能否统一使用 2.6.32-131.2.1.el6.x86_64_amd64 内核对应的 hids_driver.ko 文件？

```
2.6.32-131.2.1.el6.x86_64_amd64
2.6.32-220.17.1.el6.x86_64_amd64
2.6.32-279.22.1.el6.x86_64_amd64
2.6.32-754.25.1.el6.x86_64_amd64
```

2）若 hids_driver.ko 文件必须与内核版本严格对应，那么自定义修改过 driver 代码后，如何快速编译上百种内核版本对应的 hids_driver.ko 文件？

driver/ko_list.md 内包含上千种内核版本，假如需要到每种内核版本的主机上编译对应的 hids_driver.ko 文件，难免效率低下，不利于二次开发后的使用与维护。

**Comment by EBWi11** [comment]
1. 不可以需要严格匹配
2. 需要自己构建自动化CD流程或者使用DKMS

**Comment by ciphersaw** [comment]
> 1. 不可以，需要严格匹配
> 2. 需要自己构建自动化CD流程或者使用DKMS

1）driver 源码里的条件编译只用到了内核版本的前三组数字，如 `#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 19, 0)`，未体现其余版本信息。请教一下，第四组补丁版本若有差异，可能会有什么影响？

2）建议能在 driver/README.md 中补充介绍一下，自动化编译不同版本内核对应 hids_driver.ko 文件的具体流程，谢谢。

**Comment by EBWi11** [comment]
1. 安装Driver是通过Driver插件控制的，会做精确判断，Driver中的条件编译不需要那么精细既可以“条件编译”的目的，所以不是一个概念。可能会出现地址错误导致的crash等恶劣情况，虽然否会出现该问题需要review对应patch来确定，也可能不会有什么影响（大概率都可以使用，因为Elkeid Hook都相对底层，轻易不会变化），但是实在不建议做这种冒险行为
2. 需要自己收集对应的source文件然后做批量make

**Comment by ciphersaw** [comment]
明白了，谢谢大佬解答。
