### ISSUE TITLE
print_event.h 应该如何看

### ISSUE THREAD

**Issue by rockingl** [bytedance/Elkeid#243]
如下图所示：
<img width="993" alt="image" src="https://user-images.githubusercontent.com/20380742/167601564-b3f0bd73-19db-4a29-9571-2800180ac959.png">

stage1、 stage2、stage3 分别代表什么意思呢？

**Comment by shenping-bd** [comment]
是将同一个宏做不同的宏展开（即gcc -E）：

stage 1： 将宏PRINT_EVENT_DEFINE展开后就是一个struct的定义（struct print_event_data_offsets_##name），只处理不定长_string类型，每个域表示这个字串相对于data的偏移值

state 2: 将同一个宏展开成一个函数，即print_event_get_offsets_##name，用于计算所有的不定长字串的总长，因为每次调用的输入字串是不同的

 state 3: 更复杂一些，主要是生成两个函数，1） name##_format_event 用于消费过程，将ringbuffer中的数据转换成字符串 2）__do_##name##_print： 将要打印输出的数据写至ringbuffer

**Comment by rockingl** [comment]
> 是将同一个宏做不同的宏展开（即gcc -E）：
> 
> stage 1： 将宏PRINT_EVENT_DEFINE展开后就是一个struct的定义（struct print_event_data_offsets_##name），只处理不定长_string类型，每个域表示这个字串相对于data的偏移值
> 
> state 2: 将同一个宏展开成一个函数，即print_event_get_offsets_##name，用于计算所有的不定长字串的总长，因为每次调用的输入字串是不同的
> 
> state 3: 更复杂一些，主要是生成两个函数，1） name##_format_event 用于消费过程，将ringbuffer中的数据转换成字符串 2）__do_##name##_print： 将要打印输出的数据写至ringbuffer

那为啥要不同展开呢 怎么使用这个呢

**Comment by shenping-bd** [comment]
一次性展开会涉及宏嵌套的问题，但宏定义不能嵌套，虽然有办法可以避开，但对编译器有更多的要求

具体为什么要这么用以及怎么使用均要取决于具体的编码场景，使用宏可以避免重复/类似的代码，不然为每一个监控点都要定义多个结构体及函数
