### ISSUE TITLE
打开前端页面不需要登录

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#244]
打开前端页面不需要登录，可以直接打开，并且里面没有已经部署的终端以及用户，告警等信息
![image](https://user-images.githubusercontent.com/99782519/167758720-c25b5a3a-4c6e-4dc9-bfba-de8f67f4bb1d.png)
![image](https://user-images.githubusercontent.com/99782519/167758750-31cb70d8-ed8a-4630-8937-54c1708aec38.png)

**Comment by Serinalice** [comment]
只是前端没跳转，可以看下请求是否有异常。

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/167814391-9d4f1162-0b8c-457f-9ae4-0cde4f9bb2ba.png)

**Comment by Serinalice** [comment]
对啊，这些接口都访问不到，所以也不会泄露数据。
