### ISSUE TITLE
获取主机详情信息失败

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid#245]
如图所示，在告警业面点击主机名进入主机详情面显示【获取主机详情信息失败，数据库操作失败】
![image](https://user-images.githubusercontent.com/8515198/168750537-16eb58c5-c75c-42a2-b21e-e4195b48395b.png)

![image](https://user-images.githubusercontent.com/8515198/168750734-6d90cda0-f473-4985-b499-dbb155eab1fa.png)

**Comment by 0xlwoe21k** [comment]
跟业务确诊了一下这台机器只开了两到三分钟就下线了。有没有可能是agent端数据还没同步到服务端就关机了，导致服务端无法读取相关数据

**Comment by Serinalice** [comment]
看一下原始请求中的错误消息是什么哈

**Comment by Serinalice** [comment]
在主机列表tab能看到这台机器吗？

**Comment by 0xlwoe21k** [comment]
没有，看不到

**Comment by 0xlwoe21k** [comment]
reinstall
