### ISSUE TITLE
Manager代码编译存在问题

### ISSUE THREAD

**Issue by 0xlwoe21k** [bytedance/Elkeid#247]
如下图所示，编译发现提示错误，【len()】  对应格式化类型是【%s】。想问一下是我本机编译环境的问题，还是开源版本的代码存在错误？
![S3zaLJM2fs](https://user-images.githubusercontent.com/8515198/170444952-45eca7e5-2798-43cb-a676-3702f2757ea2.jpg)

**Comment by hugebomb** [comment]
这确实是个coding错误，但应该不会影响编译。相关的修改已经更新main分支了，感谢指出。
