### ISSUE TITLE
资产采集插件netlink socket方式缺少采集tcp6的端口信息

### ISSUE THREAD

**Issue by thleen** [bytedance/Elkeid#249]
**Describe the bug**
资产采集插件netlink socket方式缺少采集tcp6的端口信息

(https://github.com/bytedance/Elkeid/tree/main/plugins/collector)/socket.go
这个文件函数fromNetlink()，由于
tcp6Sockets, err = parseNetlink(unix.AF_INET6, unix.IPPROTO_TCP)
	if err == nil {
		return
	}
	sockets = append(sockets, tcp6Sockets...)
判断err 错误导致直接返回，缺少了补充tcp6的端口信息，应该是
if err != nil {
		return
	}

具体原来函数如下：
func fromNetlink() (sockets []Socket, err error) {
	var udpSockets, udp6Sockets, tcpSockets, tcp6Sockets []Socket
	udpSockets, err = parseNetlink(unix.AF_INET, unix.IPPROTO_UDP)
	if err != nil {
		return
	}
	sockets = append(sockets, udpSockets...)
	udp6Sockets, err = parseNetlink(unix.AF_INET6, unix.IPPROTO_UDP)
	if err != nil {
		return
	}
	sockets = append(sockets, udp6Sockets...)
	tcpSockets, err = parseNetlink(unix.AF_INET, unix.IPPROTO_TCP)
	if err != nil {
		return
	}
	sockets = append(sockets, tcpSockets...)
	tcp6Sockets, err = parseNetlink(unix.AF_INET6, unix.IPPROTO_TCP)
	if err == nil {
		return
	}
	sockets = append(sockets, tcp6Sockets...)
	return
}

**Comment by Serinalice** [comment]
Thanks! This issue has been confirmed as a bug.
Thanks again, we will fix it in next version.
