### ISSUE TITLE
compat_execveat  hook问题

### ISSUE THREAD

**Issue by sh1xo** [bytedance/Elkeid#266]
https://github.com/bytedance/Elkeid/blob/bff43a7632ff5f015b5d44787688d27e2fab0b6a/driver/LKM/src/smith_hook.c#L3374

```c
.kp.symbol_name = P_GET_COMPAT_SYSCALL_NAME(execveat) 
```

**Comment by EBWi11** [comment]
已知问题，正在解决，预计下个版本修复，感谢反馈

**Comment by shenping-bd** [comment]
Fixed with https://github.com/bytedance/Elkeid/pull/333
