### ISSUE TITLE
agent 环境变量 SPECIFIED_AGENT_ID 设置不生效

### ISSUE THREAD

**Issue by kinboyw** [bytedance/Elkeid#267]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS information (please complete the following information):**
 - Distribution: [e.g. Ubuntu]
 - Version [e.g. 18.04.1]
 - Kernel info [e.g. 5.4.0-56-generic]

**Hardware info (if you think it's helpful)
 - CPU: [e.g. Intel i7 8700k]
 - Motherboard: [e.g. AORUS Z370]

**Additional context**

环境变量传递过程中，变量名出现不一致，导致内部读取不到
https://github.dev/bytedance/Elkeid/blob/main/agent/deploy/scripts/postinstall.sh#L72-L74
https://github.dev/bytedance/Elkeid/blob/main/agent/deploy/control/cmd/set.go#L40-L41
https://github.dev/bytedance/Elkeid/blob/main/agent/agent/id.go#L47-L48

**Comment by Serinalice** [comment]
Thanks for your report, will fix in next version.
