### ISSUE TITLE
部署后端时报错，when deploying, an error occurred: Redis installed faield

### ISSUE THREAD

**Issue by pubsecpub** [bytedance/Elkeid#274]
部署命令：./elkeidup deploy --package package_community/ --config ./elkeid_server.yaml
报错内容：[ERRO]  2022-08-09T16:10:11+08:00       when deploying, an error occurred: Redis installed faield: redis validate [192.168.2.31:6379](http://192.168.2.31:6379/) error: dial tcp [192.168.2.31:6379](http://192.168.2.31:6379/)

**Comment by EBWi11** [comment]
这个步骤是安装Redis失败或者安装Redis后无法成功连接，麻烦遇到该报错后先暂时不要操作，通过 `systemctl status elkeid_redis` 查看redis状况，并通过相关日志排查失败原因

**Comment by UgOrange** [comment]
可以先看一下这个 #190  里面提到的解决方法

**Comment by pubsecpub** [comment]
经查为自动安装时所选目录权限问题所致，已解决。
