### ISSUE TITLE
在连续下发任务的时候，manager中会报一个subtask错误.

### ISSUE THREAD

**Issue by dongfangliuyihong** [bytedance/Elkeid#279]
**Describe the bug**
在连续下发任务的时候，如果第一个任务只是创建，并不执行。此时创建第二个任务的话，manager中会报一个subtask错误，此错误源于，agent_subtask集合中有一个token_1的索引为唯一导致。该字段只有在执行后被填充。该错误将会导致第二次任务的subtask创建失败

**To Reproduce**
1. 下发一个任务，不执行
2. 再下发一个任务，不执行
3. agent_subtask集合将不会产生第二个文档

**Expected behavior**
agent_subtask应该产生第二个文档

**Screenshots**
![oeTiRTorma](https://user-images.githubusercontent.com/20365580/184856513-57970520-8f31-4a2f-bd46-e6a6e1c6b30d.jpg)

**Comment by hugebomb** [comment]
subtask的token索引应该设置为非unique。相关的初始化已经修复 https://github.com/bytedance/Elkeid/pull/293
