### ISSUE TITLE
cronJobManage中 job初始化存在不确定性时许问题，会导致manage()函数空转

### ISSUE THREAD

**Issue by dongfangliuyihong** [bytedance/Elkeid#285]
**Describe the bug**
项目中，distribute/job/manage.go#79代码 for _, cj := range cm.jobs 这个地方是无法保证一定是存在数据的。会导致manage()函数空转。

**Screenshots**
![TUjC1NDjRB](https://user-images.githubusercontent.com/20365580/185552713-02fa631d-38e1-45f0-8264-36888871562c.jpg)
![mRRsdkur6B](https://user-images.githubusercontent.com/20365580/185552726-b3bfe259-a66d-4eea-9b6e-867572f7bb62.jpg)

**Additional context**
这里的CM.add并不能保证一定会在go mamane()之前运行，由于go的协程特性

**Comment by hugebomb** [comment]
感谢指出，相关问题已经fix在 https://github.com/bytedance/Elkeid/pull/292
