### ISSUE TITLE
v1.7.3与v1.7.1安装包差异

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#298]
问题：v1.7.3与v1.7.1安装包中的plugins-source.tar.gz存在差异

**v1.7.3**
<img width="546" alt="image" src="https://user-images.githubusercontent.com/44428568/187896791-236c4f63-5ae1-4002-a01c-0efaceb206dd.png">
<img width="665" alt="image" src="https://user-images.githubusercontent.com/44428568/187897179-1a50dd75-9a0e-4443-9eec-e8e3a3269b16.png">

**v1.7.1**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/44428568/187896941-008bd320-2e56-4a85-b294-513c875f0a7b.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/44428568/187897238-79d9c461-6494-4192-a8fa-ba2bb64f5454.png">

**Comment by Serinalice** [comment]
plugin-source根据最新github代码合并，的确存在版本间不一致的情况

**Comment by bigbrobro** [comment]
那如何通过./elkeidup agent build 进行编译

**Comment by Serinalice** [comment]
这部分逻辑是保持一致的，更换package参数到新版本package路径即可

**Comment by bigbrobro** [comment]
plugin-source.tar.gz的目录结构不一样，这个有影响么
