### ISSUE TITLE
建议在agent上增加简单过滤机制

### ISSUE THREAD

**Issue by pubsecpub** [bytedance/Elkeid#300]
在使用中发现，部分机器（的部分进程）产生大量无用日志，故建议在agent上增加简单过滤机制。

**Comment by Serinalice** [comment]
driver插件提供了几种filter配置，可根据需要进行修改：
https://github.com/bytedance/Elkeid/blob/main/plugins/driver/src/config.rs#L39

**Comment by bigbrobro** [comment]
602的数据类型要怎么过滤，想过滤掉不需要监控的路径，config.rs#L39 内置的filter配置只支持 EXE_WHITELIST 和 ARGV_WHITELIST

> driver插件提供了几种filter配置，可根据需要进行修改： https://github.com/bytedance/Elkeid/blob/main/plugins/driver/src/config.rs#L39
