### ISSUE TITLE
执行service elkeid-agent status问题

### ISSUE THREAD

**Issue by ppd520** [bytedance/Elkeid#310]
**描述：**
执行service elkeid-agent status时，显示agent is dead。但是进程都存在。
已编译hids_driver, 并正常加载。

**环境：**
**/etc/redhat-release**: Red Hat Enterprise Linux Server release 6.4 (Santiago)
**uname -r**: 3.10.108-1.el6.elrepo.x86_64

**截图**
![image](https://user-images.githubusercontent.com/43989361/191465449-d05525ca-85de-4577-a35d-1048073a0ce6.png)
![image](https://user-images.githubusercontent.com/43989361/191465825-23671fb5-9bd6-435a-9dd1-102421fab7f4.png)

**Comment by Serinalice** [comment]
Thank you for reporting. It's a known issue. Will fix in next version.
