### ISSUE TITLE
mount cgroup在install脚本里，重启失效

### ISSUE THREAD

**Issue by hz-kelpie** [bytedance/Elkeid#319]
https://github.com/bytedance/Elkeid/blob/main/agent/deploy/scripts/postinstall.sh#L53

**Comment by hz-kelpie** [comment]
顺便咨询下 mount到elkeid的安装目录下 而不是/sys/fs/cgroup是出于什么考虑？

**Comment by Serinalice** [comment]
已知问题，在下个版本会被修复。
CentOS 6下，无法mount到/sys/fs/cgroup
