### ISSUE TITLE
目录读写监测的判断存在匹配问题

### ISSUE THREAD

**Issue by guomsh** [bytedance/Elkeid#321]
描述：
虽然在file_permission_handler函数中通过S_ISDIR判断不再监测目录读写权限，但是ReadMe未更新，另外file_notify_check(smith_query_sb_uuid(self->d_sb), parent->d_inode->i_ino, "*", 1, mask)判断与添加白名单时不匹配，导致目录读写永远无法匹配。
![image](https://user-images.githubusercontent.com/8085964/194735982-5ede755f-eb02-4d08-bc0e-b78d025b075d.png)
解决措施：
需要将file_notify_check(smith_query_sb_uuid(self->d_sb), parent->d_inode->i_ino, "*", 1, mask)改为file_notify_check(smith_query_sb_uuid(self->d_sb), self->d_inode->i_ino, "*", 1, mask)

**Comment by shenping-bd** [comment]
不支持目录自身的改写通知，"*"的情况对应是此目录下的所有文件（不包含子目录），在判断时也是以目录的ino为索引以进行文件名的比较
