### ISSUE TITLE
文件/目录删除行为无法监测

### ISSUE THREAD

**Issue by guomsh** [bytedance/Elkeid#322]
描述：
驱动部分代码在security_path_unlink和security_path_rmdir中判断IS_PRIVATE传入的参数不正确，参数1为struct path*类型，而代码中作为struct inode*转换后使用，导致IS_PRIVATE判断为true，导致无法监测到文件和目录的删除行为。
![image](https://user-images.githubusercontent.com/8085964/194741922-2012fe31-ac44-428f-9a87-358f76fde17a.png)

解决方式：
以下代码
 if (IS_PRIVATE((struct inode *)p_regs_get_arg1(regs)))
        return 0;
修改为：
struct path* dir = NULL;
dir = (struct path *)p_regs_get_arg1(regs);
if (IS_ERR_OR_NULL(dir)) {
    return 0;
}
if (IS_PRIVATE(dir->dentry->d_inode)) {
    return 0;
}

**Comment by shenping-bd** [comment]
Fixed: https://github.com/bytedance/Elkeid/compare/main...b_IS_PRIVATE_github
