### ISSUE TITLE
[RASP]Go Inspect little bug

### ISSUE THREAD

**Issue by turn1tup** [bytedance/Elkeid#324]
**Describe the bug**
librasp 代码的 go探测有个panic错误

**Screenshots**
![image](https://user-images.githubusercontent.com/41148379/195000430-e2e78ca9-22bc-43a9-b9ad-79caaa7af8e6.png)

**OS information (please complete the following information):**
 - Distribution: Ubuntu
 - Version [20.04.2 LTS]
 - Kernel info [5.4.0-74-generic]

**Additional context**

**Comment by Hackerl** [comment]
你的目标 ELF 格式有问题？麻烦贴一下信息：
```sh
readelf -h file
```

**Comment by turn1tup** [comment]
不知道是探测了哪个进程，没用go  ， - -

**Comment by turn1tup** [comment]
readelf: Error: 'go-app' : No such file

我这边没go，不知道探测哪个进程出问题，我把这个inspect 暂时先去掉了 - -

**Comment by AlkenePan** [comment]
如果知道是 inspect 哪个二进制的话，烦请提供下，谢谢。

**Comment by AlkenePan** [comment]
解决方案是：
在 https://github.com/bytedance/Elkeid/blob/main/rasp/librasp/src/golang.rs#L141 对异常作处理。
晚点即会有修复。

感谢提交 Issue 。

**Comment by AlkenePan** [comment]
PR: https://github.com/bytedance/Elkeid/pull/325

**Comment by turn1tup** [comment]
resolved
