### ISSUE TITLE
[RASP] Send Message to Probe

### ISSUE THREAD

**Issue by turn1tup** [bytedance/Elkeid#326]
**Describe the bug**
有个疑问，目前控制台发送插件指令，然后被RASP Probe接收的流程没有走通 或是 代码不完整吗，还是说我阅读理解得不正确。
原本的 MISSING WAIT_ATTACH 分支代码都不是发信息给Probe的，这里我添加了一个CONIFG分支，RASP Probe才收到控制台发送的消息，还请指正。

![image](https://user-images.githubusercontent.com/41148379/195238325-3bbf961c-a33a-4562-87a6-ce7489cce0bb.png)

我控制台发送的消息
datat_type 2995
{"name":"test", commands":[{"pid":"xxxxx", "probe_message":"unicode编码数据", "state":"CONFIG", "runtime":"" }] }

unicode编码数据: [{"pid":"xxxxx", "message_type":6, "data":{"uuid":"1", "filters":[] }}]

**Comment by AlkenePan** [comment]
self.send_probe_message message 要符合 rasp server 部分定义的结构。

**Comment by turn1tup** [comment]
> self.send_probe_message message 要符合 rasp server 部分定义的结构。

我有成功发送消息..只是表达疑惑。

**Comment by AlkenePan** [comment]
https://github.com/bytedance/Elkeid/blob/main/rasp/plugin/src/operation.rs#L142

在 WAIT_ATTACH 里，第一次注入指令即可伴随探针配置。后续也可以使用 WAIT_ATTACH 下发。
