### ISSUE TITLE
使用elkeidup部署报错

### ISSUE THREAD

**Issue by L-1-q** [bytedance/Elkeid#328]
使用时ubuntu20.04部署的这个，但是爆了时间的错误，请问一下这个该如何解决呀 谢谢
[ERRO]	2022-10-18T06:37:33Z	when deploying, an error occurred: Checker installed faield: exec check cmd failed when pre check host, err: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 -i /root/.ssh/id_rsa root@192.168.64.11 /tmp/elkeid_check -n 1666075048 failed, err: exit status 1, stderr: 2022/10/18 06:37:33 ElkeidCheckErr:Failed to execute clock check, local time is 1666075048, remote time is 1666075053
2022/10/18 06:37:33 clock check error,  2022/10/18 06:37:33 ElkeidCheckErr:Failed to execute clock check, local time is 1666075048, remote time is 1666075053
2022/10/18 06:37:33 clock check error

**Comment by TaeRoen** [comment]
是ssh的本机吗？ssh的时候是不是会卡主几秒，不会立即登录成功。

猜测是GSSAPIAuthentication这个sshd配置的问题，导致每次ssh都要等一个超时，不能立即登录成功。关掉GSSAPIAuthentication或许可以解决。或者用其他办法，保证ssh登录时等待时间小于1s即可。
