### ISSUE TITLE
搭建好管理端了使用nc触发不了告警

### ISSUE THREAD

**Issue by bbg8cody** [bytedance/Elkeid#329]
![image](https://user-images.githubusercontent.com/45092826/196369648-7eb4c3bc-372b-4a37-9c2d-83498aba494a.png)
![image](https://user-images.githubusercontent.com/45092826/196369968-2387bb14-2cf1-48b0-9dd9-a579eed7254e.png)

**Comment by whitelez** [comment]
您好，

我们当前提供的策略仅仅只是商业策略的很小一部分，用于指引感兴趣的同学进行策略开发使用的
您如果感兴趣可以参考reverse_shell_detect 编写类似的规则检测 nc -e /bin/bash
或者等待后续开源进展

Elkeid Team
