### ISSUE TITLE
scanner升级之后，启动失败

### ISSUE THREAD

**Issue by ppd520** [bytedance/Elkeid#342]
**Describe the bug**
scanner插件升级之后，scanner插件启动失败；且重新安装agent后，scanner插件也未启动，agent依旧去找升级失败的插件。

**To Reproduce**
1. 【任务管理】->【组件列表】-> 【新建组件】添加插件压缩包类型scanner组件。
2. 【资产中心】-> 【主机列表】-> 任意选择一台机器【插件管理】->scanner升级。
3. 【任务列表】->执行刚才的升级任务。
4.  任务执行成功， scanner插件启动失败。报错：`when load plugin scanner:3.1.9.1, an error occurred: fork/exec /etc/elkeid/plugin/scanner`， 用file命令查看scanner文件，是gzip data。

**Expected behavior**
升级任务执行成功后， scanner 插件正常启动，且为升级后的版本。

**截图**
![image](https://user-images.githubusercontent.com/43989361/200992244-44eac7fe-8005-48f6-a099-106cb151169e.png)

**OS information (please complete the following information):**
 - Distribution: [CentOS Linux release 7.6.1810]
 - Version [7.6.1810]
 - Kernel info [3.10.0-957.27.2.el7.x86_64]

**Comment by kulukami** [comment]
@ppd520 请提供完整上下文，包括并不限于：
* 后端 ac / manager 对应版本（分支）
* ac 下发给 agent 的完整 配置 数据
* agent 完整上下文日志

**Comment by kulukami** [comment]
1.7.3 可能没有适配 1.9.1 的 tar.gz 插件
推测 agent 接受到的 task 结构体中没有  type=tar.gz 字段，可以尝试以下方法确认：

1.为 agent 添加 log 打印出接收到的 task。 https://github.com/bytedance/Elkeid/blob/v1.7.3/agent/plugin/plugin_linux.go#L43
2.检查下 mongodb 中 agent_heartbeat 表的 对应 agent_id 数据， config 是否一致（type 字段是否漏掉）

同时建议等待 1.9.1 正式 release 后配合后端一同升级
