### ISSUE TITLE
Elkeid/rasp/php/  编译失败

### ISSUE THREAD

**Issue by weaweawe01** [bytedance/Elkeid#343]
```c
-- Using the single-header code from /Elkeid/rasp/php/build/_deps/json-src/single_include/
-- 
--         ---( Libevent 2.1.12-stable )---
-- 
-- Available event backends: 
-- CMAKE_BINARY_DIR:         /Elkeid/rasp/php/build
-- CMAKE_CURRENT_BINARY_DIR: /Elkeid/rasp/php/build/_deps/libevent-build
-- CMAKE_SOURCE_DIR:         /Elkeid/rasp/php
-- CMAKE_CURRENT_SOURCE_DIR: /Elkeid/rasp/php/build/_deps/libevent-src
-- PROJECT_BINARY_DIR:       /Elkeid/rasp/php/build/_deps/libevent-build
-- PROJECT_SOURCE_DIR:       /Elkeid/rasp/php/build/_deps/libevent-src
-- CMAKE_MODULE_PATH:        cmake;/Elkeid/rasp/php/build/_deps/libevent-src/cmake/
-- CMAKE_COMMAND:            /usr/bin/cmake
-- CMAKE_ROOT:               /usr/share/cmake
-- CMAKE_SYSTEM:             Linux-4.18.0-348.7.1.el8_5.x86_64
-- CMAKE_SYSTEM_NAME:        Linux
-- CMAKE_SYSTEM_VERSION:     4.18.0-348.7.1.el8_5.x86_64
-- CMAKE_SYSTEM_PROCESSOR:   x86_64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:             -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -Wstrict-prototypes -fno-strict-aliasing -Wmissing-prototypes -Winit-self -Wmissing-field-initializers -Wdeclaration-after-statement -Waddress -Wnormalized=id -Woverride-init -Wlogical-op -Wwrite-strings
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         /usr/bin/gcc (id GNU, clang 0, GNUC 1)
-- CMAKE_AR:                 /usr/bin/ar
-- CMAKE_RANLIB:             /usr/bin/ranlib
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /Elkeid/rasp/php/build
Consolidate compiler generated dependencies of target c_runtime
Consolidate compiler generated dependencies of target zero
Consolidate compiler generated dependencies of target event_core_static
[  9%] Built target c_runtime
[ 21%] Built target zero
[ 48%] Built target event_core_static
Consolidate compiler generated dependencies of target event_pthreads_static
Consolidate compiler generated dependencies of target event_extra_static
Consolidate compiler generated dependencies of target event_static
[ 50%] Built target event_pthreads_static
[ 57%] Built target event_extra_static
Consolidate compiler generated dependencies of target php_probe
[ 89%] Built target event_static
[ 90%] Linking CXX shared library ../lib/libphp_probe.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/php_probe.dir/build.make:198: ../lib/libphp_probe.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:191: CMakeFiles/php_probe.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

查看了一下CMakeFiles/php_probe.dir/build.make  198 
```php
php_probe_EXTERNAL_OBJECTS =

../lib/libphp_probe.so: CMakeFiles/php_probe.dir/library.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/php/api.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/php/hash.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/client/smith_client.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/client/smith_message.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/client/smith_probe.cpp.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/tiny-regex-c/re.c.o
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/build.make
../lib/libphp_probe.so: ../lib/libzero.a
../lib/libphp_probe.so: ../lib/libc_runtime.a
../lib/libphp_probe.so: ../lib/libevent_core.a
../lib/libphp_probe.so: ../lib/libevent_pthreads.a
../lib/libphp_probe.so: ../lib/libevent_core.a
../lib/libphp_probe.so: CMakeFiles/php_probe.dir/link.txt

```

好像是libphp_probe.so 没有生成成功。感觉像是lib的目录原因。暂时没有找到原因

**Comment by Hackerl** [comment]
> /usr/bin/ld: cannot find -lstdc++

错误已经显示了，没有找到 libstdc++.so，请检查以下机器上是否有该文件

**Comment by Hackerl** [comment]
建议使用我们的 docker 镜像编译。

```sh
curl -fsSL https://lf3-static.bytednsdoc.com/obj/eden-cn/laahweh7uhwbps/php-headers.tar.gz | tar -xz -C rasp/php

docker run --rm -v $(pwd):/Elkeid \
    -v /tmp/cache/gradle:/root/.gradle \
    -v /tmp/cache/librasp:/Elkeid/rasp/librasp/target \
    -v /tmp/cache/rasp_server:/Elkeid/rasp/rasp_server/target \
    -v /tmp/cache/plugin:/Elkeid/rasp/plugin/target \
    -e MAKEFLAGS="-j$(nproc)" hackerl/rasp-toolchain \
    make -C /Elkeid/rasp build \
    STATIC=TRUE \
    PY_PREBUILT=TRUE \
    CC=/opt/x86_64-linux-musl-1.2.2/bin/x86_64-linux-musl-gcc \
    CXX=/opt/x86_64-linux-musl-1.2.2/bin/x86_64-linux-musl-g++ \
    LD=/opt/x86_64-linux-musl-1.2.2/bin/x86_64-linux-musl-ld \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=/opt/x86_64-linux-musl-1.2.2/bin/x86_64-linux-musl-ld \
    GNU_CC=/opt/gcc-10.4.0/bin/gcc GNU_CXX=/opt/gcc-10.4.0/bin/g++ \
    PHP_HEADERS=/Elkeid/rasp/php/php-headers \
    PYTHON2_INCLUDE=/usr/local/include/python2.7 \
    PYTHON3_INCLUDE=/usr/local/include/python3 \
    VERSION=0.0.0.1
```

或者直接下载 release 产物进行试用。

**Comment by weaweawe01** [comment]
Docker 已经测试了。直接卡死了一个小时了

**Comment by weaweawe01** [comment]
release 我测试中。php 模块已经安装上了。但是访问一丁点效果都没有。

**Comment by weaweawe01** [comment]
命令行中如下：
[root@localhost php]# php56 -d 'extension=libphp_probe-5.6.so' -r "system(ls);"
PHP Warning:  Module 'php probe' already loaded in Unknown on line 0
build
client
cmake
CMakeLists.txt
lib
library.cpp
library.h
output
php
README.md
tiny-regex-c
[root@localhost php]# 

可以有警告。但是我放到php.ini 中
[libphp]
extension=/www/server/php/56/lib/php/extensions/no-debug-non-zts-20131226/libphp_probe-5.6.so

测试system("ls")

```php
[root@localhost 192.168.1.72]# cat 2.php 
<?php system("ls");

?>
[root@localhost 192.168.1.72]# curl 192.168.1.72/2.php
2.php
404.html
index.html
[root@localhost 192.168.1.72]# 

```

**Comment by weaweawe01** [comment]
还有另外一个问题。使用release  版本中我调试的为php  但是返回的给我的是JVM的
![QQ截图20221109115615](https://user-images.githubusercontent.com/111571429/200734845-90ede941-bb0d-458f-9195-e8941427ed52.png)

**Comment by Hackerl** [comment]
> Docker 已经测试了。直接卡死了一个小时了

卡在哪里，开网络代理试试

**Comment by weaweawe01** [comment]
> > Docker 已经测试了。直接卡死了一个小时了
> 
> 在哪里，开网络代理尝试卡

Docker 的话卡在编译了
![37f58c59a9fa59751f658000bc41ae8](https://user-images.githubusercontent.com/111571429/200735300-984e56fa-b033-46ea-94ec-00bed494a7bc.jpg)

如图直接卡了一个小时。我后直接放弃了。选择手动编译了

**Comment by weaweawe01** [comment]
测试了一下。使用PHP5.6 以下的才会产生警告

7.0 以上没有警告。
![image](https://user-images.githubusercontent.com/111571429/200735622-961a9405-8d67-40b6-b382-357c8000e714.png)

不知道这个是不是一个bug 。然后php.ini 写入之后。注入进程好像是没啥效果的。

**Comment by Hackerl** [comment]
> > > Docker 已经测试了。直接卡死了一个小时了
> 
> > 
> 
> > 在哪里，开网络代理尝试卡
> 
> 
> 
> Docker 的话卡在编译了
> 
> ![37f58c59a9fa59751f658000bc41ae8](https://user-images.githubusercontent.com/111571429/200735300-984e56fa-b033-46ea-94ec-00bed494a7bc.jpg)
> 
> 
> 
> 如图直接卡了一个小时。我后直接放弃了。选择手动编译了

项目里存在大量的 github 依赖，如果没有开启代理的话的确会很慢。

**Comment by weaweawe01** [comment]
> > > > Docker 已经测试了。直接卡死了一个小时了
> > 
> > 
> > > 
> > 
> > 
> > > 在哪里，开网络代理尝试卡
> > 
> > 
> > Docker的话卡在编译了
> > ![37f58c59a9fa59751f658000bc41ae8](https://user-images.githubusercontent.com/111571429/200735300-984e56fa-b033-46ea-94ec-00bed494a7bc.jpg)
> > 我直接选择手动编译了一个小时。
> 
> 项目里存在大量的github依赖，如果没有开启代理的话会很慢。

能看看我其他的问题吗

**Comment by Hackerl** [comment]
1. 确认使用与 php 对应版本的 so
2. 先使用命令行测试是否加载成功

```sh
socat UNIX-LISTEN:"/var/run/smith_agent.sock" -
php -d 'extension=$(pwd)/lib/libphp_probe.so' -r "shell_exec('ls'); sleep(60);"
```
请保留 `sleep(60)`，因为 `PHP RASP` 使用的双进程通信架构，如果主进程快速退出，通信进程还没来得及发送消息就被杀死。
3. 使用 `php-fpm` 加载插件后，请确认是否加载成功。
```sh
cat /proc/$(pid)/maps | grep php_probe
```
如果加载成功却没有消息传递出来，查看 /tmp/php_probe*.log 并贴上日志内容。

**Comment by weaweawe01** [comment]
> 1. 确认使用与 php 对应版本的 so
> 2. 先使用命令行测试是否加载成功
> 
> ```shell
> socat UNIX-LISTEN:"/var/run/smith_agent.sock" -
> php -d 'extension=$(pwd)/lib/libphp_probe.so' -r "shell_exec('ls'); sleep(60);"
> ```
> 
> 请保留 `sleep(60)`，因为 `PHP RASP` 使用的双进程通信架构，如果主进程快速退出，通信进程还没来得及发送消息就被杀死。
> 
> 3. 使用 `php-fpm` 加载插件后，请确认是否加载成功。
> 
> ```shell
> cat /proc/$(pid)/maps | grep php_probe
> ```
> 
> 如果加载成功却没有消息传递出来，查看 /tmp/php_probe*.log 并贴上日志内容。


![image](https://user-images.githubusercontent.com/111571429/200739311-63d6d24f-bb28-4952-a1a1-8427fcb3b4b3.png)


如上

**Comment by Hackerl** [comment]
> 测试了一下。使用PHP5.6 以下的才会产生警告
> 
> 7.0 以上没有警告。 ![image](https://user-images.githubusercontent.com/111571429/200735622-961a9405-8d67-40b6-b382-357c8000e714.png)
> 
> 不知道这个是不是一个bug 。然后php.ini 写入之后。注入进程好像是没啥效果的。

请先移除相关的配置文件，再使用 -d 参数测试，如果配置文件里已经配置了 `RASP` 拓展，会有冲突。

**Comment by Hackerl** [comment]
> ```shell
> /var/run/smith_agent.sock
> ```

现在你的问题是，用命令行测试有消息输出，但是 php-fpm 没有吗？/var/run/smith_agent.sock 是你手动监听的还是 rasp_server？

**Comment by Hackerl** [comment]
> > 1. 确认使用与 php 对应版本的 so
> > 2. 先使用命令行测试是否加载成功
> > 
> > ```shell
> > socat UNIX-LISTEN:"/var/run/smith_agent.sock" -
> > php -d 'extension=$(pwd)/lib/libphp_probe.so' -r "shell_exec('ls'); sleep(60);"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请保留 `sleep(60)`，因为 `PHP RASP` 使用的双进程通信架构，如果主进程快速退出，通信进程还没来得及发送消息就被杀死。
> > 
> > 3. 使用 `php-fpm` 加载插件后，请确认是否加载成功。
> > 
> > ```shell
> > cat /proc/$(pid)/maps | grep php_probe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果加载成功却没有消息传递出来，查看 /tmp/php_probe*.log 并贴上日志内容。
> 
> ![image](https://user-images.githubusercontent.com/111571429/200739311-63d6d24f-bb28-4952-a1a1-8427fcb3b4b3.png)
> 
> 如上

现在你的问题是，用命令行测试有消息输出，但是 php-fpm 没有吗？/var/run/smith_agent.sock 是你手动监听的还是 rasp_server？

**Comment by AlkenePan** [comment]
> 还有另外一个问题。使用release 版本中我调试的为php 但是返回的给我的是JVM的 ![QQ截图20221109115615](https://user-images.githubusercontent.com/111571429/200734845-90ede941-bb0d-458f-9195-e8941427ed52.png)

看起来是另一个JVM进程的探针连回了sock, 所以数据也打印出来。

**Comment by Hackerl** [comment]
忘了说， PHP 的消息不是即时发送，因为使用的无锁丢列，每次都使用条件变量通知会浪费性能，现在的逻辑是消息达到 N 条或者超过 30s，即刻发送消息到 unix server。

**Comment by weaweawe01** [comment]
> 测试了一下。使用PHP5.6 以下的才会产生警告

我的Cli 配置文件和web 的是分开的。所以不存在冲突。

**Comment by weaweawe01** [comment]
> rasp_server



> > 还有另外一个问题。使用release 版本中我调试的为php 但是返回的给我的是JVM的 ![QQ截图20221109115615](https://user-images.githubusercontent.com/111571429/200734845-90ede941-bb0d-458f-9195-e8941427ed52.png)
> 
> 看起来是另一个JVM进程的探针连回了sock, 所以数据也打印出来。

我现在是手动执行 是存在警告信息的。手动执行的cli 配置文件和php-fpm web 是分开的。
命令是有警告信息。php-fpm 是没有信息。
/var/run/smith_agent.sock  这个是客户端启动的

**Comment by weaweawe01** [comment]
> > > 1. 确认使用与 php 对应版本的 so
> > > 2. 先使用命令行测试是否加载成功
> > > 
> > > ```shell
> > > socat UNIX-LISTEN:"/var/run/smith_agent.sock" -
> > > php -d 'extension=$(pwd)/lib/libphp_probe.so' -r "shell_exec('ls'); sleep(60);"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请保留 `sleep(60)`，因为 `PHP RASP` 使用的双进程通信架构，如果主进程快速退出，通信进程还没来得及发送消息就被杀死。
> > > 
> > > 3. 使用 `php-fpm` 加载插件后，请确认是否加载成功。
> > > 
> > > ```shell
> > > cat /proc/$(pid)/maps | grep php_probe
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果加载成功却没有消息传递出来，查看 /tmp/php_probe*.log 并贴上日志内容。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/111571429/200739311-63d6d24f-bb28-4952-a1a1-8427fcb3b4b3.png)
> > 如上
> 
> 现在你的问题是，用命令行测试有消息输出，但是 php-fpm 没有吗？/var/run/smith_agent.sock 是你手动监听的还是 rasp_server？

我现在是手动执行 是存在警告信息的。手动执行的cli 配置文件和php-fpm web 是分开的。
命令是有警告信息。php-fpm 是没有信息。
/var/run/smith_agent.sock 这个是客户端启动的

**Comment by weaweawe01** [comment]
> 忘了说， PHP 的消息不是即时发送，因为使用的无锁队列，每次都使用条件变量通知会浪费性能，现在的逻辑是消息达到 N 条或者超过 30s 就立刻发送消息到 unix server。
> 
> ![image](https://user-images.githubusercontent.com/15811751/200749632-c8d170b6-f1cf-4f63-91ab-9b71ee5c6ffd.png)

这个是发到Elkeid_server端的信息吗？

我现在Agent 都没有加载到rasp 这个插件。
![image](https://user-images.githubusercontent.com/111571429/200752871-067b662e-6c3a-4b9c-8ca4-47d2a013529c.png)

**Comment by Hackerl** [comment]
> 

发送到 unix socket:/var/run/smith_agent.sock。

**Comment by AlkenePan** [comment]
默认情况下，植入到进程中的探针（包括PHP和JVM）都会连接 `/var/run/smith_agent.sock`，并传输Hook信息。
请确认 php/php_fpm 有没有自动/手工植入探针：
`cat /proc/$(pid)/maps | grep php_probe`
如果确认植入后，可以通过以下方式受到Hook数据：（从易到难，且不要重复)
1. 手工监听 `/var/run/smith_agent.sock`
2. 使用 elkeid_rasp -p <pid>，自动植入探针且监听，消息打印到终端。
3. 通过 elkeid server - agent 启动 rasp 插件，也会根据配置植入探针且监听数据上报到服务端。

**Comment by Hackerl** [comment]
> > 忘了说， PHP 的消息不是即时发送，因为使用的无锁队列，每次都使用条件变量通知会浪费性能，现在的逻辑是消息达到 N 条或者超过 30s 就立刻发送消息到 unix server。
> > ![image](https://user-images.githubusercontent.com/15811751/200749632-c8d170b6-f1cf-4f63-91ab-9b71ee5c6ffd.png)
> 
> 这个是发到Elkeid_server端的信息吗？
> 
> 我现在Agent 都没有加载到rasp 这个插件。 ![image](https://user-images.githubusercontent.com/111571429/200752871-067b662e-6c3a-4b9c-8ca4-47d2a013529c.png)

你可以先不要用 rasp 插件测试，手动测试 libphp_probe.so 模块。

![image](https://user-images.githubusercontent.com/15811751/200754411-7308e10d-c512-4d8f-9d48-12ae5136eeaa.png)

```sh=
echo "extension=/path/to/libphp_probe.so" > /etc/php/7.3/fpm/conf.d/z-probe.ini

cat > /etc/nginx/conf.d/php.conf << EOF
server {
        listen 7878;

        location ~ \.php$ {
                root /var/www/html;
                fastcgi_pass unix:/run/php/php7.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
EOF

cat > /var/www/html/index.php << EOF
<?php system("ls");

?>
EOF

curl 127.0.0.1:7878/index.php
```
把 php7.3 替换为对应版本，访问 index.php 后等待一分钟，看 socat 是否有消息输出。

**Comment by AlkenePan** [comment]
> 默认情况下，植入到进程中的探针（包括PHP和JVM）都会连接 `/var/run/smith_agent.sock`，并传输Hook信息。 请确认 php/php_fpm 有没有自动/手工植入探针： `cat /proc/$(pid)/maps | grep php_probe` 如果确认植入后，可以通过以下方式受到Hook数据：（从易到难，且不要重复)
> 
> 1. 手工监听 `/var/run/smith_agent.sock`
> 2. 使用 `elkeid_rasp -p <pid>`，自动植入探针且监听，消息打印到终端。
> 3. 通过 elkeid server - agent 启动 rasp 插件，也会根据配置植入探针且监听数据上报到服务端。

如果遇到同一次监听下，不同进程都上报了数据，这是正常的，因为探针都连接同一地址。

**Comment by weaweawe01** [comment]
> > > 忘了说， PHP 的消息不是即时发送，因为使用的无锁队列，每次都使用条件变量通知会浪费性能，现在的逻辑是消息达到 N 条或者超过 30s 就立刻发送消息到 unix server。
> > > ![image](https://user-images.githubusercontent.com/15811751/200749632-c8d170b6-f1cf-4f63-91ab-9b71ee5c6ffd.png)
> > 
> > 
> > 这个是发到Elkeid_server端的信息吗？
> > 我现在Agent 都没有加载到rasp 这个插件。 ![image](https://user-images.githubusercontent.com/111571429/200752871-067b662e-6c3a-4b9c-8ca4-47d2a013529c.png)
> 
> 你可以先不要用 rasp 插件测试，手动测试 libphp_probe.so 模块。
> 
> ![image](https://user-images.githubusercontent.com/15811751/200754411-7308e10d-c512-4d8f-9d48-12ae5136eeaa.png)
> 
> ```
> echo "extension=/path/to/libphp_probe.so" > /etc/php/7.3/fpm/conf.d/z-probe.ini
> 
> cat > /etc/nginx/conf.d/php.conf << EOF
> server {
>         listen 7878;
> 
>         location ~ \.php$ {
>                 root /var/www/html;
>                 fastcgi_pass unix:/run/php/php7.3-fpm.sock;
>                 fastcgi_index index.php;
>                 fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>                 include fastcgi_params;
>         }
> }
> EOF
> 
> cat > /var/www/html/index.php << EOF
> <?php system("ls");
> 
> ?>
> EOF
> 
> sudo socat UNIX-LISTEN:/var/run/smith_agent.sock -
> curl 127.0.0.1:7878/index.php
> ```
> 
> 把 php7.3 替换为对应版本，访问 index.php 后等待一分钟，看 socat 是否有消息输出。

结果如下：
![image](https://user-images.githubusercontent.com/111571429/200758008-be5c0546-13be-4de9-8d6b-150c43a2d7ee.png)

具体的php70 的信息如下：
![image](https://user-images.githubusercontent.com/111571429/200759444-11e871d4-83c6-440d-93b2-bb0b2facc1f0.png)

**Comment by AlkenePan** [comment]
> > > > 忘了说， PHP 的消息不是即时发送，因为使用的无锁队列，每次都使用条件变量通知会浪费性能，现在的逻辑是消息达到 N 条或者超过 30s 就立刻发送消息到 unix server。
> > > > ![image](https://user-images.githubusercontent.com/15811751/200749632-c8d170b6-f1cf-4f63-91ab-9b71ee5c6ffd.png)
> > > 
> > > 
> > > 这个是发到Elkeid_server端的信息吗？
> > > 我现在Agent 都没有加载到rasp 这个插件。 ![image](https://user-images.githubusercontent.com/111571429/200752871-067b662e-6c3a-4b9c-8ca4-47d2a013529c.png)
> > 
> > 
> > 你可以先不要用 rasp 插件测试，手动测试 libphp_probe.so 模块。
> > ![image](https://user-images.githubusercontent.com/15811751/200754411-7308e10d-c512-4d8f-9d48-12ae5136eeaa.png)
> > ```
> > echo "extension=/path/to/libphp_probe.so" > /etc/php/7.3/fpm/conf.d/z-probe.ini
> > 
> > cat > /etc/nginx/conf.d/php.conf << EOF
> > server {
> >         listen 7878;
> > 
> >         location ~ \.php$ {
> >                 root /var/www/html;
> >                 fastcgi_pass unix:/run/php/php7.3-fpm.sock;
> >                 fastcgi_index index.php;
> >                 fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
> >                 include fastcgi_params;
> >         }
> > }
> > EOF
> > 
> > cat > /var/www/html/index.php << EOF
> > <?php system("ls");
> > 
> > ?>
> > EOF
> > 
> > sudo socat UNIX-LISTEN:/var/run/smith_agent.sock -
> > curl 127.0.0.1:7878/index.php
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 把 php7.3 替换为对应版本，访问 index.php 后等待一分钟，看 socat 是否有消息输出。
> 
> 结果如下： ![image](https://user-images.githubusercontent.com/111571429/200758008-be5c0546-13be-4de9-8d6b-150c43a2d7ee.png)
> 
> 具体的php70 的信息如下： ![image](https://user-images.githubusercontent.com/111571429/200759444-11e871d4-83c6-440d-93b2-bb0b2facc1f0.png)

`sudo rm /var/run/smith_agent.sock;sudo socat UNIX-LISTEN:/var/run/smith_agent.sock -`

**Comment by weaweawe01** [comment]
php5.6 的信息
![image](https://user-images.githubusercontent.com/111571429/200763943-a6e00276-1b73-4d87-aea9-0e3446357ff6.png)

执行ls命令的时候
![image](https://user-images.githubusercontent.com/111571429/200764134-9f7711aa-e8fc-4f5b-926b-707d1e62070e.png)

手工执行的方式
![image](https://user-images.githubusercontent.com/111571429/200764744-b22fb40e-a106-401c-a819-e0db24770a77.png)

**Comment by Hackerl** [comment]
方便加一下 elkeid 的飞书群吗，现在在 github 上不好排查。

**Comment by Hackerl** [comment]
https://github.com/bytedance/Elkeid/pull/345

1. php module 依赖没有正确设置，导致 rasp 启动在标准库初始化之前，无法正确 hook 函数
2. 由于 fpm 使用了 --daemonize 参数，导致在启动后会 fork 到后台，导致消息进程被杀
