### ISSUE TITLE
driver编译失败，提示trace_handle_return未定义

### ISSUE THREAD

**Issue by goldboy123** [bytedance/Elkeid#344]
错误提示如下：
|-----------------------------------|
| building HIDS kernel module       |
|-----------------------------------|
make -C /usr/src/kernels/5.4.18-53-generic M=/root/driver/LKM modules
make[1]: 进入目录“/usr/src/linux-headers-5.4.18-53-generic”
  Building modules, stage 2.
  MODPOST 1 modules
ERROR: "trace_handle_return" [/root/driver/LKM/hids_driver.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:94：__modpost] 错误 1
make[1]: *** [Makefile:1655：modules] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.4.18-53-generic”
make: *** [Makefile:63：all] 错误 2

**Comment by shenping-bd** [comment]
问一下这个是什么发行版？麒麟？

看报错应该是trace_handle_return没有导出的原因，你能否检查下内核symbol里有没有此函数：grep trace_handle_return /proc/kallsyms ?

**Comment by goldboy123** [comment]
> 问一下这个是什么发行版？麒麟？
> 
> 看报错应该是trace_handle_return没有导出的原因，你能否检查下内核symbol里有没有此函数：grep trace_handle_return /proc/kallsyms ?

确实没有这个内核函数，那我需要单独导出下trace_handle_return这个函数吗？

**Comment by shenping-bd** [comment]
可以尝试将trace_handle_return的实现代码复制过来，但要注意其调用的函数有无导出：
https://elixir.bootlin.com/linux/v5.4.18/source/kernel/trace/trace.c#L2325

如果只是想测试驱动的话，可以用v1.8-rc分支，此为下一版本，内部正在测试中，即将替换现有的main分支

**Comment by goldboy123** [comment]
> 可以尝试将trace_handle_return的实现代码复制过来，但要注意其调用的函数有无导出： https://elixir.bootlin.com/linux/v5.4.18/source/kernel/trace/trace.c#L2325
> 
> 如果只是想测试驱动的话，可以用v1.8-rc分支，此为下一版本，内部正在测试中，即将替换现有的main分支

好的，感谢
