### ISSUE TITLE
agent全部离线，网络正常，服务正常

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#349]
agent全部离线，可以新部署agent，但是仍是无法上线。
前端显示所有agent全部离线
![image](https://user-images.githubusercontent.com/99782519/202147708-9e100d06-c811-4c46-b8a1-d1c13db5c3a4.png)
查看server服务
![image](https://user-images.githubusercontent.com/99782519/202147807-e0e4d8df-b485-49b4-8c05-c2c16e468e6f.png)
服务正常，查看agent日志
![image](https://user-images.githubusercontent.com/99782519/202148238-c52b1be2-dd2d-4be1-a166-eb7c78212053.png)
查看agent到server的端口是否正常
![image](https://user-images.githubusercontent.com/99782519/202148666-6939ecfb-837b-4762-a28d-8477e20ace12.png)
抓包查看agent与server是否有数据通信
![image](https://user-images.githubusercontent.com/99782519/202148985-ef00c69f-b984-44b9-abd9-315519c73359.png)

**Comment by hugebomb** [comment]
麻烦在agent所在机器上 curl http://192.168.5.201:8089/registry/summary 看看

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/202414882-842e5e06-c418-4e67-b6df-4cbba4c05b8e.png)

**Comment by hugebomb** [comment]
报错显示是AgentCenter没有注册到服务发现。麻烦登录192.168.5.203，贴一下AgentCenter相关的error日志，路径应该是在 /elkeid/agent_center/log/*

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/202946732-b2abe5fe-9b14-4f66-8ff5-11cda4e0900a.png)
![image](https://user-images.githubusercontent.com/99782519/202946787-643d71fa-4661-4944-948c-365e7e76ca84.png)

**Comment by hugebomb** [comment]
麻烦确认下 192.168.5.203这台机器到192.168.5.201这台机器的链路是不是通的。这里报错限制ac所在机器访问不到sd

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/203027762-6a3d565d-71ec-462c-a432-c76004e84f7d.png)
这边网络是正常的

**Comment by hugebomb** [comment]
报错显示的机器之间网络互通有问题。麻烦贴一下这三台机器的网卡信息，可以用 ip addrs 或者 ifconfig
