### ISSUE TITLE
命中大量告警下，前端页面无法处理告警

### ISSUE THREAD

**Issue by bbg8cody** [bytedance/Elkeid#353]
![image](https://user-images.githubusercontent.com/45092826/202604938-bb7689d9-4bba-4166-a5f6-1efa7f527d57.png)
![image](https://user-images.githubusercontent.com/45092826/202605043-f3264425-92e7-41d1-a0a7-62335ff51034.png)
前端页面的告警在告警栏显示为空
我是分开部署在两台机器上，一台部署的redis、MongoDB、nginx,另一台部署的其他组件
磁盘告警后看kafka占得最多，删除/elkeid/kafka/kafka-logs这个路径下的东西，但是看还是没清理完，想问下怎么删掉告警的数据
![image](https://user-images.githubusercontent.com/45092826/202607512-029a24e0-3ffa-43df-82a8-dfdafdbdb594.png)

**Comment by Smartuu** [comment]
@bbg8cody 能方便提供下mongodb所在机器的CPU和内存配置吗？根据你的截图初步判断是告警数据量非常大，估计是是这个导致monogdb的查询太慢导致前端一直卡住没法查询出结果。建议你可以直接上mongodb上删除告警数据，大概操作如下

**Comment by bbg8cody** [comment]
mongodb机器的配置是4C8G200G，我在/elkeid/mongodb/db这个目录下把所有collection都删了还是不行
![image](https://user-images.githubusercontent.com/45092826/202631291-51f55bcf-663a-4419-bffa-0090dd2addb0.png)
我进这个mongodb也连接不成功
![image](https://user-images.githubusercontent.com/45092826/202632260-fec2c66f-d475-4472-acd6-91c4ce9311b9.png)

**Comment by Smartuu** [comment]
> mongodb机器的配置是4C8G200G，我在/elkeid/mongodb/db这个目录下把所有collection都删了还是不行 ![image](https://user-images.githubusercontent.com/45092826/202631291-51f55bcf-663a-4419-bffa-0090dd2addb0.png) 我进这个mongodb也连接不成功 ![image](https://user-images.githubusercontent.com/45092826/202632260-fec2c66f-d475-4472-acd6-91c4ce9311b9.png)

@bbg8cody 删除所有的collection会导致后续系统运行不正常，建议你重新部署安装。另外你的mongo命令没办法连上mongodb是因为默认情况下mongodb应该没有监听在127.0.0.1，你的mongo命令需要加上“--host {监听的IP地址}”才能正确连接到mongodb。如果不清楚具体mongodb监听的IP地址，可以到mongodb所在主机执行netstat -ltnp|grep 27017|awk '{print $4}'|awk -F":" '{print $1}'查看下。

**Comment by bbg8cody** [comment]
可以了 谢谢
