### ISSUE TITLE
开启文件读写监控

### ISSUE THREAD

**Issue by Murasame-nc** [bytedance/Elkeid#361]
文件读写监控默认是关闭的，如何开启文件监控？直接把smith_hook.c文件中对应的全局变量置1，之后重新编译并且加载ko文件吗？
之后还需要在控制台上指定对哪些文件进行监控吗？

**Comment by EBWi11** [comment]
开启FILE_PERMISSION_HOOK后通过 https://github.com/bytedance/Elkeid/tree/main/driver#about-driver-filter 这里的ADD_WRITE_NOTIFI、DEL_WRITE_NOTIFI、ADD_READ_NOTIFI、DEL_READ_NOTIFI、DEL_ALL_NOTIFI 来控制监控列表。该功能由于极端情况下性能问题已不再维护。
