### ISSUE TITLE
开启文件监控之后someone_allowlist如何指定

### ISSUE THREAD

**Issue by Murasame-nc** [bytedance/Elkeid#362]
1:开启FILE_PERMISSION_HOOK，通过ADD_WRITE_NOTIFI、DEL_WRITE_NOTIFI、ADD_READ_NOTIFI、DEL_READ_NOTIFI、DEL_ALL_NOTIFI 来控制监控列表。
2:执行这个命令的时候:echo W/etc/passwd > /dev/someone_allowlist or echo W/etc/ssh/ > /dev/someone_allowlist support dir   这个someone_allowlist设备文件可以随意指定吗？比如说test_allowlist可以吗？

**Comment by EBWi11** [comment]
allowlist driver is in: /dev/hids_driver_allowlist
