### ISSUE TITLE
allowlist driver is in: /dev/hids_driver_allowlist

### ISSUE THREAD

**Issue by Murasame-nc** [bytedance/Elkeid#363]
allowlist driver is in: /dev/hids_driver_allowlist

_Originally posted by @EBWi11 in https://github.com/bytedance/Elkeid/issues/362#issuecomment-1324644807_

**Comment by Murasame-nc** [comment]
我可以理解为，在开启了文件读写监控点之后，执行echo W/etc/passwd > /dev/hids_driver__allowlist  就能达到对/etc/passwd文件读写的监控吗？

**Comment by EBWi11** [comment]
ADD_WRITE_NOTIFI :W(87)
ADD_READ_NOTIFI : R(82)

**Comment by Murasame-nc** [comment]
我之前测试过了，没有监控到相关的事件。我的测试方式:
1:开启file_permisson HOOK
2:重新编译ko文件
3:加载ko文件
4:编译plugin->driver插件
5:编译好的插件替换plugin目录下原有的插件，之后执行新编译的driver插件
6:对目标文件进行写操作
但是没有发现产生对应类型的事件

**Comment by EBWi11** [comment]
![screenshot-20221123-180506](https://user-images.githubusercontent.com/20244029/203519734-2a937669-a713-41ad-82b9-bd56f1ed5208.png)
