### ISSUE TITLE
v1.9.1 部署失败，卡在HUB运行

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#371]
单机非Docker部署，报错如下

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/44428568/205116534-e323f2aa-b63b-4a0d-96cb-6eb2e8c6393c.png">

手动运行Hub显示错误如下
<img width="818" alt="image" src="https://user-images.githubusercontent.com/44428568/205116436-522cf5b0-a683-49f4-9fe8-47a6f7264b6f.png">

查看6701端口存在，但是Curl失败
<img width="736" alt="image" src="https://user-images.githubusercontent.com/44428568/205117430-789d8d0c-ce5c-4748-811a-13bd603e59e3.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/44428568/205117486-a5d22cdc-ca5e-4593-812e-3197a2ba82cb.png">

**Comment by TaeRoen** [comment]
应该是manager没有正常运行，麻烦看下manager的log
journalctl -fu elkeid_manager 和 tail -f /elkeid/log/manager.log 
v1.9.1 目前我们还没正式对外release，还卡在某些流程，只是github上被设置成release了。

**Comment by bigbrobro** [comment]
> 应该是manager没有正常运行，麻烦看下manager的log journalctl -fu elkeid_manager 和 tail -f /elkeid/log/manager.log v1.9.1 目前我们还没正式对外release，还卡在某些流程，只是github上被设置成release了。

manager日志
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/44428568/205205969-7b74c449-2134-41b4-bf97-f0ad5be81c14.png">

**Comment by TaeRoen** [comment]
可以 curl -v 192.168.31.162:6701 看下吗？ manager是自己编译的，还是用的预编译的二进制？

**Comment by bigbrobro** [comment]
> 查看6701端口存在，但是Curl失败

6701端口存在，但是Curl失败
![image](https://user-images.githubusercontent.com/44428568/205229431-a9f521f2-c89a-449c-953e-3d167cbe2025.png)

安装包直接下载release版本通过elkeidup部署
wget https://github.com/bytedance/Elkeid/releases/download/v1.9.1/elkeidup_package_v1.9.1.tar.gz.00
wget https://github.com/bytedance/Elkeid/releases/download/v1.9.1/elkeidup_package_v1.9.1.tar.gz.01
wget https://github.com/bytedance/Elkeid/releases/download/v1.9.1/elkeidup_package_v1.9.1.tar.gz.02
cat elkeidup_package_v1.9.1.tar.gz.* > elkeidup_package_v1.9.1.tar.gz

**Comment by TaeRoen** [comment]
目前猜测是manager启动后一段时间会推出，可以systemctl status elkeid_manager 确认下，看下运行时间是不是只有几分钟。如果是的话，能否同时在/elkeid/log/manager.log里捕捉一下manager退出时的log吗？
