### ISSUE TITLE
arm环境下/proc/elkeid-endpoint无数据

### ISSUE THREAD

**Issue by goldboy123** [bytedance/Elkeid#376]
arm安装driver后，采集不到驱动数据。
系统内核版本：5.4.18-53-generic
经debug，内核函数可以hook成功，hook函数中可打印日志。
![image](https://user-images.githubusercontent.com/16534511/205486838-d01c09af-7f2e-423f-ae1a-2dcf65aa30a5.png)
在读数据时，返回非-EBUSY
`static ssize_t trace_read_pipe(struct file *filp, char __user * ubuf,
                               size_t cnt, loff_t * ppos)
{
    ssize_t sret;
    struct print_event_iterator *iter = filp->private_data;
    static DEFINE_MUTEX(access_lock);
    /*
     * Avoid more than one consumer on a single file descriptor
    * This is just a matter of traces coherency, the ring buffer itself
    * is protected.
    */
    mutex_lock(&iter->mutex);

    sret = trace_seq_to_user_sym(&iter->seq, ubuf, cnt);
    if (sret != -EBUSY){
       goto out;
    }

`
/proc/elkeid-endpoint是非阻塞的，怀疑数据没有写入成功。

**Comment by goldboy123** [comment]
> sret 返回值是什么 ？
sret 返回值为 0

**Comment by shenping-bd** [comment]
确认和Kylin的内核定制不兼容所致，内核没有导出 trace_seq_to_user：

root@Kylin10SP1:/bd/elkeid/driver/LKM/src# cat /proc/modules  | grep hids
hids_driver 151552 0 - Live 0xffffffc00911d000 (OE)
root@Kylin10SP1:/bd/elkeid/driver/LKM/src# dmesg | grep trace_seq_to_user
[ 3129.108068] trace_seq_to_user: trace_seq_to_user+0x0/0x8 [hids_driver] at ffffffc00911d000.

另外trace_handle_return()亦没有导出，但很容易替代，但此方式只能用于实验。Kylin arm64 的总体支持需要下一版本的规划，

**Comment by goldboy123** [comment]
测试环境下，我直接使用https://elixir.bootlin.com/linux/v5.4.18/source/kernel/trace/trace_seq.c#L373 这个里面的源码替换trace_seq_to_user，好像还是不行，替换后第一个ebus不会卡了，cat /proc/elkeid-endpoint成为阻塞状态了

**Comment by goldboy123** [comment]
> 确认和Kylin的内核定制不兼容所致，内核没有导出 trace_seq_to_user：
> 
> root@Kylin10SP1:/bd/elkeid/driver/LKM/src# cat /proc/modules | grep hids hids_driver 151552 0 - Live 0xffffffc00911d000 (OE) root@Kylin10SP1:/bd/elkeid/driver/LKM/src# dmesg | grep trace_seq_to_user [ 3129.108068] trace_seq_to_user: trace_seq_to_user+0x0/0x8 [hids_driver] at ffffffc00911d000.
> 
> 另外trace_handle_return()亦没有导出，但很容易替代，但此方式只能用于实验。Kylin arm64 的总体支持需要下一版本的规划，

还有一个疑问，trace_handle_return没有导出，所以在编译的时候会报错，trace_seq_to_user在编译的时候并没有报错，可以编译成功，这是说trace_seq_to_user函数其实是存在的吗？

**Comment by shenping-bd** [comment]
> 

trace_seq_to_user存在在hids_driver中，并且还是个空函数，所以smith_kallsyms_lookup_name能定位到此符号，导致此情形的原因在于Kylin这个桌面内核有点残废，CONFIG_TRACING没有配置(虽然配置了CONFIG_TRACING_SUPPORT)，但前者没有定义致trace_seq_to_user被定义成了inline，从而编译到hids_driver.ko中，可参考include/linux/trace_seq.h

**Comment by goldboy123** [comment]
> > 
> 
> trace_seq_to_user存在在hids_driver中，并且还是个空函数，所以smith_kallsyms_lookup_name能定位到此符号，导致此情形的原因在于Kylin这个桌面内核有点残废，CONFIG_TRACING没有配置(虽然配置了CONFIG_TRACING_SUPPORT)，但前者没有定义致trace_seq_to_user被定义成了inline，从而编译到hids_driver.ko中，可参考include/linux/trace_seq.h

了解，但我理解这里应该不止trace_seq_to_user一个函数问题，应该还存在ubuf为空另外一个问题吧？ubuf为空，所以也不会产生数据
