### ISSUE TITLE
v1.9.1 frontend创建输出源报错

### ISSUE THREAD

**Issue by scarleast** [bytedance/Elkeid#379]
**Describe the bug**
v1.9.1 frontend创建输出源

**To Reproduce**
frontend创建输出源报错

**Screenshots**
![image](https://user-images.githubusercontent.com/14150292/205802768-e4d98635-2a37-4d42-99c1-e58a63e71a08.png)

**Additional context**
通过配置文件导入输出没有问题，但通过frontend创建输出源报错。

**Comment by UgOrange** [comment]
目前[1.9.1.1](https://github.com/bytedance/Elkeid/releases/tag/v1.9.1.1)版本已经解决该问题，可以升级体验下
