### ISSUE TITLE
v1.7.2 升级 v1.9.1 要如何操作

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#380]
如题，已安装的 v1.7.2 升级到 v1.9.1 要怎么配置、操作，v1.7.2 agent 上线到 v1.9.1 manager 后怎么关闭自动更新agent及插件（需要按需逐步升级Agent，避免出问题）

**Comment by hugebomb** [comment]
文档已更新到 https://elkeid.bytedance.com/Chinese/ElkeidUp/update.html

**Comment by UgOrange** [comment]
由于长期没有回复，关闭此issue，如仍有问题欢迎提issue
