### ISSUE TITLE
V1.9.1 规则测试功能，测试结果无法解压

### ISSUE THREAD

**Issue by scarleast** [bytedance/Elkeid#381]
**Describe the bug**
规则测试功能，测试的结果下载以后无法解压

**Screenshots**
![image](https://user-images.githubusercontent.com/14150292/205835666-edd2aad3-e10f-4976-a185-afc1eccc40a1.png)

![image](https://user-images.githubusercontent.com/14150292/205835706-dcb6d059-4144-4884-bf02-b0d6e84bfcd8.png)

**Comment by chiselX** [comment]
你好,该问题下次更新会一起fix,谢谢反馈

**Comment by chiselX** [comment]
> **Describe the bug** 规则测试功能，测试的结果下载以后无法解压
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/14150292/205835666-edd2aad3-e10f-4976-a185-afc1eccc40a1.png)
> 
> ![image](https://user-images.githubusercontent.com/14150292/205835706-dcb6d059-4144-4884-bf02-b0d6e84bfcd8.png)

你好,该问题下次更新会一起fix,谢谢反馈

**Comment by UgOrange** [comment]
经测试该功能在最新版本已经解决，感谢反馈
