### ISSUE TITLE
验证环境用不了

### ISSUE THREAD

**Issue by fwxiong** [bytedance/Elkeid#382]
![image](https://user-images.githubusercontent.com/17467689/205868926-cd644885-825e-40e4-aec9-d9b7789ce49e.png)

**Comment by hugebomb** [comment]
麻烦浏览器上 F12，选择到 Network ，然后重新刷新下页面，看看相关接口的报错。
类似这样
![image](https://user-images.githubusercontent.com/77203039/206075117-9b92bd88-7662-4440-99b0-b52ef71b575d.png)

**Comment by UgOrange** [comment]
此环境已经不可用，如有问题欢迎再次提问
