### ISSUE TITLE
yum install 安装软件告警变形木马

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#384]
木马检查的逻辑是什么，我yum install了一个程序，提示变形木马，这是命中什么规则了
![image](https://user-images.githubusercontent.com/99782519/206065686-1839dfd9-559f-48e7-b6fb-19743104158e.png)
![image](https://user-images.githubusercontent.com/99782519/206065727-3c4adf81-f0e5-481e-9ac8-7689fa6d6536.png)
![image](https://user-images.githubusercontent.com/99782519/206065785-689ca181-82d7-4f0f-844e-f66a99671238.png)

**Comment by EBWi11** [comment]
目前社区版本规则均在：https://github.com/bytedance/Elkeid-HUB/tree/main/config/elkeid_hids/ruleset
你触发的这条策略是：https://github.com/bytedance/Elkeid-HUB/blob/main/config/elkeid_hids/ruleset/hids_detect.xml 的binary_file_hijack_detect2 这一条，含义是的在move 文件到 /usr/sbin/，/usr/bin/ 等目录下。
另社区版本策略仅作为实例使用，不保证准确性，请注意。
