### ISSUE TITLE
离线的主机，我想从平台删除掉，没看到可以操作的地方，能给指导下吗，谢谢

### ISSUE THREAD

**Issue by lipengxin** [bytedance/Elkeid#387]
问下，已经卸载了agent的离线主机，我想从平台删除掉，没看到可以操作的地方，能给指导下吗，谢谢。
![飞书20221208-111110](https://user-images.githubusercontent.com/30541245/206347174-8fa716ca-e75b-4405-8619-6c671d7eee81.jpeg)

**Comment by EBWi11** [comment]
![image](https://user-images.githubusercontent.com/20244029/206352485-1aa4e913-2a63-4e06-881c-8e529c1717c0.png)

**Comment by lipengxin** [comment]
> ![image](https://user-images.githubusercontent.com/20244029/206352485-1aa4e913-2a63-4e06-881c-8e529c1717c0.png)

我点击过的，但离线主机还一直存在，agent也是通过卸载指令卸载的，
![image](https://user-images.githubusercontent.com/30541245/206363208-018f40e1-def0-48f1-bb3c-d8ade7c343bc.png)

**Comment by h253518892** [comment]
同问，我也是，并且点击清理离线数据并没有发送request

**Comment by Serinalice** [comment]
目前不支持从前端删除离线主机，辛苦直接从后端db删除离线数据，参考mongoshell如下：
```
db.agent_heartbeat.deleteMany({last_heartbeat_time:{$lt:1672110000}})
```
在执行时，根据实际时间把1672110000替换为`当前Unix秒时间戳-3600`
