### ISSUE TITLE
主机内的JAVA程序已被rasp识别到，但一直没显示注入成功

### ISSUE THREAD

**Issue by shigithubs** [bytedance/Elkeid#390]
平台版本：Community Edition v1.9.1
Agent版本：1.7.0.24
应用语言：JAVA

请问，主机内的JAVA程序已被rasp识别到，也新建配置了，但一直没显示注入成功。
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/49743346/206614903-0ecfdf2a-2092-4543-8070-a7965df514fe.png">
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/49743346/206615427-f51c4257-1519-40f8-bb31-874775a79696.png">
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/49743346/206615458-b088f06f-b248-4f6d-a111-4fd73c0dfb4c.png">

**Comment by AlkenePan** [comment]
尝试升级下 1.9.1.* 的最新版本 RASP插件： https://github.com/bytedance/Elkeid/releases/tag/rasp-v1.9.1.70

**Comment by shigithubs** [comment]
好的，我升级试试，谢谢～～

**Comment by shigithubs** [comment]
额，我将rasp版本更新到1.9.1.70了，也发布了，目前JAVA程序已经注入进去了，但我看组件策略还是1.44的，这个有影响嘛，需不需要要进行手动更新？
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/49743346/206618142-346925bd-790e-4810-8357-c0fa655384cc.png">
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/49743346/206617294-c60d9fdd-e826-4e79-8f95-d51839af619b.png">
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/49743346/206617387-5fc2cffb-ada0-47f0-bbe5-edbdb545181c.png">

**Comment by AlkenePan** [comment]
一般来说，组建列表决定了有哪些组建可用，组建策略决定了端上组建的版本，如果需要同步的话可以下发任务来同步策略。

RASP 发现进程到注入进程过程中需要一段时间，如果没有同步过组建版本，应该是旧版完成了注入。

**Comment by shigithubs** [comment]
哦哦，好的

**Comment by shigithubs** [comment]
额，你好，我这边尝试新增一条rasp新版本的组件策略但是报错了，这个是啥原因，需要把之前低版本的策略删掉嘛
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/49743346/206632526-e8c8dcf3-fec9-4b7c-be90-063bb8ca4f55.png">

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/49743346/206632773-39c51411-4913-4d70-87cd-af29bf7a33bc.png">

**Comment by AlkenePan** [comment]
是的 要删除旧策略

**Comment by shigithubs** [comment]
好的～
