### ISSUE TITLE
v1.18.6集群已采集 Audit Logs 到系统后端，但根据“插件安装指引”5个步骤执行完成，安全组件状态一直显示“未安装”

### ISSUE THREAD

**Issue by Gragonlee** [bytedance/Elkeid#391]
平台版本：Community Edition v1.9.1
k8s集群版本：v1.18.6

1、在master节点已经开启audit log并输出到后端：
[root@k8s-master policy]# tail -n 20 /var/log/kubernetes/audit/audit.log 
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"395fc91a-f9b8-4d1f-9169-909e1ba56a13","stage":"ResponseStarted","requestURI":"/api/v1/limitranges?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=5m39s\u0026timeoutSeconds=339\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"limitranges","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.134158Z","stageTimestamp":"2022-12-09T09:27:08.323495Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"395fc91a-f9b8-4d1f-9169-909e1ba56a13","stage":"ResponseComplete","requestURI":"/api/v1/limitranges?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=5m39s\u0026timeoutSeconds=339\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"limitranges","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.134158Z","stageTimestamp":"2022-12-09T09:27:08.323505Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"d59fc1b2-1420-4510-be78-6edf9ca94b3a","stage":"ResponseStarted","requestURI":"/api/v1/secrets?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=7m14s\u0026timeoutSeconds=434\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"secrets","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.135269Z","stageTimestamp":"2022-12-09T09:27:08.323527Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"d59fc1b2-1420-4510-be78-6edf9ca94b3a","stage":"ResponseComplete","requestURI":"/api/v1/secrets?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=7m14s\u0026timeoutSeconds=434\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"secrets","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.135269Z","stageTimestamp":"2022-12-09T09:27:08.323541Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}

2、根据“插件安装引导”的5个步骤进行配置，apiserver重启后，仍然显示未安装
![image](https://user-images.githubusercontent.com/37131199/206688087-668548ae-ad6f-4417-89f0-1d725a30bb56.png)

3、kubelet日志
Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.635989   22128 kubelet.go:1682] Unable to attach or mount volumes for pod "kube-apiserver-k8s-master_kube-system(6b85f2658963975952798b7a0c9d967d)": unmounted volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs], unattached volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs]: timed out waiting for the condition; skipping pod
Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.636027   22128 pod_workers.go:191] Error syncing pod 6b85f2658963975952798b7a0c9d967d ("kube-apiserver-k8s-master_kube-system(6b85f2658963975952798b7a0c9d967d)"), skipping: unmounted volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs], unattached volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs]: timed out waiting for the condition
Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.639342   22128 kubelet.go:1682] Unable to attach or mount volumes for pod "kube-apiserver-k8s-master_kube-system(aa90a386ac227d65ee93459091f86adf)": unmounted volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs], unattached volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs]: timed out waiting for the condition; skipping pod
Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.639369   22128 pod_workers.go:191] Error syncing pod aa90a386ac227d65ee93459091f86adf ("kube-apiserver-k8s-master_kube-system(aa90a386ac227d65ee93459091f86adf)"), skipping: unmounted volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs], unattached volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs]: timed out waiting for the condition

**Comment by bytecoss** [comment]
> 平台版本：Community Edition v1.9.1 k8s集群版本：v1.18.6
> 
> 1、在master节点已经开启audit log并输出到后端： [root@k8s-master policy]# tail -n 20 /var/log/kubernetes/audit/audit.log {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"395fc91a-f9b8-4d1f-9169-909e1ba56a13","stage":"ResponseStarted","requestURI":"/api/v1/limitranges?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=5m39s\u0026timeoutSeconds=339\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"limitranges","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.134158Z","stageTimestamp":"2022-12-09T09:27:08.323495Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}} {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"395fc91a-f9b8-4d1f-9169-909e1ba56a13","stage":"ResponseComplete","requestURI":"/api/v1/limitranges?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=5m39s\u0026timeoutSeconds=339\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"limitranges","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.134158Z","stageTimestamp":"2022-12-09T09:27:08.323505Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}} {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"d59fc1b2-1420-4510-be78-6edf9ca94b3a","stage":"ResponseStarted","requestURI":"/api/v1/secrets?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=7m14s\u0026timeoutSeconds=434\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"secrets","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.135269Z","stageTimestamp":"2022-12-09T09:27:08.323527Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}} {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"d59fc1b2-1420-4510-be78-6edf9ca94b3a","stage":"ResponseComplete","requestURI":"/api/v1/secrets?allowWatchBookmarks=true\u0026resourceVersion=8468\u0026timeout=7m14s\u0026timeoutSeconds=434\u0026watch=true","verb":"watch","user":{"username":"system:apiserver","uid":"0d380e87-bc76-4ff1-a20b-af64de5f3df6","groups":["system:masters"]},"sourceIPs":["127.0.0.1"],"userAgent":"kube-apiserver/v1.18.6 (linux/amd64) kubernetes/dff82dc","objectRef":{"resource":"secrets","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","message":"Connection closed early","code":200},"requestReceivedTimestamp":"2022-12-09T09:26:52.135269Z","stageTimestamp":"2022-12-09T09:27:08.323541Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
> 
> 2、根据“插件安装引导”的5个步骤进行配置，apiserver重启后，仍然显示未安装 ![image](https://user-images.githubusercontent.com/37131199/206688087-668548ae-ad6f-4417-89f0-1d725a30bb56.png)
> 
> 3、kubelet日志 Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.635989 22128 kubelet.go:1682] Unable to attach or mount volumes for pod "kube-apiserver-k8s-master_kube-system(6b85f2658963975952798b7a0c9d967d)": unmounted volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs], unattached volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs]: timed out waiting for the condition; skipping pod Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.636027 22128 pod_workers.go:191] Error syncing pod 6b85f2658963975952798b7a0c9d967d ("kube-apiserver-k8s-master_kube-system(6b85f2658963975952798b7a0c9d967d)"), skipping: unmounted volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs], unattached volumes=[elkeid-audit ca-certs etc-pki k8s-certs audit-policy audit-logs]: timed out waiting for the condition Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.639342 22128 kubelet.go:1682] Unable to attach or mount volumes for pod "kube-apiserver-k8s-master_kube-system(aa90a386ac227d65ee93459091f86adf)": unmounted volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs], unattached volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs]: timed out waiting for the condition; skipping pod Dec 09 18:46:25 k8s-master kubelet[22128]: E1209 18:46:25.639369 22128 pod_workers.go:191] Error syncing pod aa90a386ac227d65ee93459091f86adf ("kube-apiserver-k8s-master_kube-system(aa90a386ac227d65ee93459091f86adf)"), skipping: unmounted volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs], unattached volumes=[etc-pki k8s-certs audit-policy audit-logs elkeid-audit ca-certs]: timed out waiting for the condition


你将 audit logs 存放在本地（/var/log/kubernetes/audit/audit.log）了吗？当前 Elkeid 仅通过 webhook backend 接收 audit logs，不支持 Log backend。

可否提供一下你配置的 kube-apiserver.yaml

**Comment by UgOrange** [comment]
由于长期没有回复，关闭此issue，如仍有问题欢迎提issue
