### ISSUE TITLE
1.9.1部署hub失败

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#392]
部署过程中hub部署失败，查看hub显示服务已经启动，但是没有监听端口
![image](https://user-images.githubusercontent.com/99782519/206977898-76ead6ba-3062-4358-98dc-94237035bcf8.png)
![image](https://user-images.githubusercontent.com/99782519/206977924-99d6615f-6e80-43c8-a563-523514c801ee.png)

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/206984552-1c1655a0-514b-4d2c-bc88-150e1a15bb1a.png)

**Comment by UgOrange** [comment]
麻烦看下``/elkeid/log/hub.log``文件，看看有没有什么报错信息，目前看没有正常启动

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/206988349-5c1a7b64-0343-4bfb-ac82-c85dc54c116b.png)

**Comment by UgOrange** [comment]
好的感谢，麻烦还需要查看一下/elkeid/hub/plugin/output/plugin.stdout文件，我们确认下原因

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/207202370-ac151019-dc9c-49b4-b735-f157015f2611.png)

**Comment by UgOrange** [comment]
麻烦执行一下
``sha256sum /tmp/hub_plugin/zip/2d5d356f3e2e4f1675e1246538e8df17a42500d168cac70b29fbadb68301ba57.zip``，查看返回的结果是否与文件名一致为``2d5d356f3e2e4f1675e1246538e8df17a42500d168cac70b29fbadb68301ba57``，如果该文件不存在或者不一致，执行``rm -rf /tmp/hub_plugin``并且执行``systemctl restart elkeid_leader``重启leader。之后执行``elkeidup deploy``从失败的位置尝试继续进行安装。

**Comment by UgOrange** [comment]
在leader的机器上执行``wget "http://127.0.0.1:12310/static/plugin/plugin?sha256sum=2d5d356f3e2e4f1675e1246538e8df17a42500d168cac70b29fbadb68301ba57" -O 1.zip``是什么结果呢？

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/207279138-2ce09871-c974-45f5-a980-921c98f058fb.png)

**Comment by UgOrange** [comment]
这个命令没有执行成功，换个目录再试下

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/207305058-1b89e033-bb24-4ba0-98a7-9633214c44fe.png)

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/207305261-0d309372-a474-4fd9-ad0b-d1612b12a761.png)
我看我监听的是12311端口

**Comment by UgOrange** [comment]
这里应该程序出问题了，麻烦看下``/elkeid/log/leader.log``找到panic相关内容提供给我们，谢谢

**Comment by h253518892** [comment]
![image](https://user-images.githubusercontent.com/99782519/207563056-665ea03f-e812-417b-b48e-079ba8998ebd.png)

**Comment by h253518892** [comment]
[GIN] 2022/12/14 - 17:51:36 | 500 |    3.063341ms |   192.168.5.212 | GET      "/static/plugin/plugin?sha256sum=2d5d356f3e2e4f1675e1246538e8df17a42500d168cac70b29fbadb68301ba57"
{"level":"info","ts":1671011507.0201652,"msg":"newConnectionManager","info":"discovery hosts: [192.168.5.212:12311]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:76(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011507.0202987,"msg":"newConnectionManager","info":"connection 192.168.5.212:12311 ok","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:106(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011507.0203376,"msg":"newConnectionManager","info":"connMap: map[192.168.5.212:12311:0xc0001e2f00], clientMap: map[192.168.5.212:12311:0xc0004060a8]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:110(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
[GIN] 2022/12/14 - 17:51:53 | 200 |      70.656?s |   192.168.5.212 | GET      "/ping"
{"level":"info","ts":1671011522.018843,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllInputQPS-1671007742026737235 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0189703,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllInputQPS-1671007682026631362 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0190053,"msg":"newChannelMap","info":"channel chan-id-HUB_GetQPSInfo-1671007742026778967 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0190365,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007652026518127 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0190609,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007892026666150 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0190904,"msg":"newChannelMap","info":"channel chan-id-HUB_GetInputLag-1671007742026385780 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0191193,"msg":"newChannelMap","info":"channel chan-id-HUB_getStatus-1671007802027150581 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0191462,"msg":"newChannelMap","info":"channel chan-id-HUB_GetQPSInfo-1671007802027086557 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0191677,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007712026798622 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0191917,"msg":"newChannelMap","info":"channel chan-id-HUB_getStatus-1671007682026620285 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0192494,"msg":"newChannelMap","info":"channel chan-id-HUB_GetQPSInfo-1671007862027454537 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.01928,"msg":"newChannelMap","info":"channel chan-id-HUB_getStatus-1671007742026385797 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0193028,"msg":"newChannelMap","info":"channel chan-id-HUB_GetQPSInfo-1671007682026672461 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0193486,"msg":"newChannelMap","info":"channel chan-id-HUB_GetInputLag-1671007682026601062 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0193799,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007802027110956 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0194013,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007832026675445 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0194278,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllOutputQPS-1671007802027030514 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019454,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllInputQPS-1671007802027075142 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0194826,"msg":"newChannelMap","info":"channel chan-id-HUB_GetInputLag-1671007862027280282 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0195029,"msg":"newChannelMap","info":"channel chan-id-HUB_getStatus-1671007862027527647 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0195348,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007742026391520 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019556,"msg":"newChannelMap","info":"channel chan-id-HUB_GetQPSInfo-1671007622026337615 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019577,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllOutputQPS-1671007742026542095 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019636,"msg":"newChannelMap","info":"channel chan-id-HUB_GetInputLag-1671007802027038042 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0196667,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllOutputQPS-1671007622026312977 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019687,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007682026655981 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0197182,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllInputQPS-1671007862027189745 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0197453,"msg":"newChannelMap","info":"channel chan-id-HUB_getStatus-1671007622026296890 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019766,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007862027188304 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0197923,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllInputQPS-1671007622026387908 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0198123,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllOutputQPS-1671007862027194297 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.019858,"msg":"newChannelMap","info":"channel chan-id-HUB_GetInputLag-1671007622026322754 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0198786,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007772026196796 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0199049,"msg":"newChannelMap","info":"channel chan-id-HUB_GetAllOutputQPS-1671007682026608058 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0199263,"msg":"newChannelMap","info":"channel chan-id-HUB_getProjectStatus-1671007622026166909 expire and delete","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/pubsub.go:56(code.byted.org/security/leader/distribute/pubsub.newChannelMap.func1)"}
{"level":"info","ts":1671011522.0203934,"msg":"newConnectionManager","info":"discovery hosts: [192.168.5.212:12311]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:76(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011522.020482,"msg":"newConnectionManager","info":"connection 192.168.5.212:12311 ok","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:106(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011522.0205169,"msg":"newConnectionManager","info":"connMap: map[192.168.5.212:12311:0xc0001e2f00], clientMap: map[192.168.5.212:12311:0xc0004060a8]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:110(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011522.0295477,"msg":"jobManager","info":"informed new a job: id-HUB_GetInputLag-1671011522026933600","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.02962,"msg":"jobManager","info":"informed new a job: id-HUB_GetAllInputQPS-1671011522026901685","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.029671,"msg":"jobManager","info":"informed new a job: id-HUB_getProjectStatus-1671011522026919165","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0297365,"msg":"jobManager","info":"informed new a job: id-HUB_getStatus-1671011522026928746","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0295887,"msg":"jobManager","info":"informed new a job: id-HUB_GetAllOutputQPS-1671011522026925215","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0297203,"msg":"jobManager","info":"informed new a job: id-HUB_GetQPSInfo-1671011522026969695","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0295491,"msg":"jobManager","info":"informed new a job: id-HUB_GetProjectAlertCount-1671011522026899791","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0428019,"msg":"jobManager","info":"informed new a job: id-HUB_GetAllInputQPS-1671011522026901685","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
[GIN] 2022/12/14 - 17:52:02 | 200 |    10.96016ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
{"level":"info","ts":1671011522.0432823,"msg":"jobManager","info":"informed new a job: id-HUB_GetQPSInfo-1671011522026969695","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.043285,"msg":"jobManager","info":"informed new a job: id-HUB_getStatus-1671011522026928746","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0432951,"msg":"jobManager","info":"informed new a job: id-HUB_GetProjectAlertCount-1671011522026899791","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
[GIN] 2022/12/14 - 17:52:02 | 200 |   10.480861ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
[GIN] 2022/12/14 - 17:52:02 | 200 |    6.432557ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
{"level":"info","ts":1671011522.0434508,"msg":"jobManager","info":"informed new a job: id-HUB_GetInputLag-1671011522026933600","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
[GIN] 2022/12/14 - 17:52:02 | 200 |    11.34573ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
[GIN] 2022/12/14 - 17:52:02 | 200 |    6.269583ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
{"level":"info","ts":1671011522.0434663,"msg":"jobManager","info":"informed new a job: id-HUB_GetAllOutputQPS-1671011522026925215","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
{"level":"info","ts":1671011522.0434532,"msg":"jobManager","info":"informed new a job: id-HUB_getProjectStatus-1671011522026919165","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/manage.go:202(code.byted.org/security/leader/distribute/job.(*jobManager).inform)"}
[GIN] 2022/12/14 - 17:52:02 | 200 |    6.233555ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
[GIN] 2022/12/14 - 17:52:02 | 200 |    6.436735ms |   192.168.5.212 | POST     "/api/v0/inner/sync_job"
{"level":"info","ts":1671011522.1069138,"msg":"RenewRegistry","info":">>>>register elkeid.leader.psm 192.168.5.212 12310 0 to SD http://192.168.5.212:8088/registry/register","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/infra/discovery/svr_register_os.go:105(code.byted.org/security/leader/infra/discovery.(*ServerRegistry).renewRegistry)"}
{"level":"info","ts":1671011522.1076214,"msg":"RenewRegistry","info":">>>>register elkeid.leader.grpc 192.168.5.212 12311 0 to SD http://192.168.5.212:8088/registry/register","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/infra/discovery/svr_register_os.go:105(code.byted.org/security/leader/infra/discovery.(*ServerRegistry).renewRegistry)"}
{"level":"error","ts":1671011522.1291409,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getAllInputQPS\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_GetAllInputQPS-1671011522026901685","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.1291451,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getProjectStatus\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_getProjectStatus-1671011522026919165","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.1293337,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getStatus\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_getStatus-1671011522026928746","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.1293957,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getKafkaLag\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_GetInputLag-1671011522026933600","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.129411,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getProjectAlertCount\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_GetProjectAlertCount-1671011522026899791","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.1295524,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getQPSInfo\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_GetQPSInfo-1671011522026969695","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
{"level":"error","ts":1671011522.13344,"msg":"SimpleJob","info":"[job] do job error: Get \"https://192.168.5.212:8091/getAllOutputQPS\": dial tcp <nil>->192.168.5.212:8091: connect: connection refused,jid id-HUB_GetAllOutputQPS-1671011522026925215","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)","traces":["/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/job/job.go:383(code.byted.org/security/leader/distribute/job.(*SimpleJob).Run.func2)"]}
[GIN] 2022/12/14 - 17:52:14 | 200 |     182.568?s |   192.168.5.212 | POST     "/api/v1/user/login"
{"level":"info","ts":1671011537.0207288,"msg":"newConnectionManager","info":"discovery hosts: [192.168.5.212:12311]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:76(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011537.0208745,"msg":"newConnectionManager","info":"connection 192.168.5.212:12311 ok","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:106(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
{"level":"info","ts":1671011537.0209107,"msg":"newConnectionManager","info":"connMap: map[192.168.5.212:12311:0xc0001e2f00], clientMap: map[192.168.5.212:12311:0xc0004060a8]","location":"/opt/tiger/compile_path/src/code.byted.org/security/leader/distribute/pubsub/connection.go:110(code.byted.org/security/leader/distribute/pubsub.newConnectionManager.func2)"}
[GIN] 2022/12/14 - 17:52:18 | 200 |    1.624084ms |   192.168.5.212 | GET      "/api/v5/getPlugins?cluster=security.elkeid.hub"


2022/12/14 17:52:18 [Recovery] 2022/12/14 - 17:52:18 panic recovered:
Call of bsoncore.Value.Binary on embedded document type
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/x/bsonx/bsoncore/value.go:495 (0x845a33)
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/bson/raw_value.go:167 (0x893044)
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/mongo/gridfs/download_stream.go:263 (0x9e3bd9)
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/mongo/gridfs/download_stream.go:159 (0x9e338a)
/usr/local/go/src/bytes/buffer.go:202 (0x4fc897)
/usr/local/go/src/io/io.go:413 (0x4781ea)
/usr/local/go/src/io/io.go:386 (0x9e1c0b)
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/mongo/gridfs/bucket.go:406 (0x9e1beb)
/opt/tiger/compile_path/pkg/mod/go.mongodb.org/mongo-driver@v1.10.3/mongo/gridfs/bucket.go:237 (0x9e1347)
/opt/tiger/compile_path/src/code.byted.org/security/leader/biz/handler/v5/hub_py_plugin_util.go:57 (0xea979a)
/opt/tiger/compile_path/src/code.byted.org/security/leader/biz/handler/v5/hub_py_plugin.go:383 (0xea1f84)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xf55fa6)
/opt/tiger/compile_path/src/code.byted.org/security/leader/biz/router.go:387 (0xf55f8a)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xd3a421)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0xd3a40c)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xd39566)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0xd39549)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xd38630)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0xd38298)
/opt/tiger/compile_path/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0xd37dd1)
/usr/local/go/src/net/http/server.go:2947 (0x6e806b)
/usr/local/go/src/net/http/server.go:1991 (0x6e3286)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46be20)

**Comment by UgOrange** [comment]
您好，这边判断是db数据写入有问题，所以可以尝试进行重新安装，执行``elkeidup undeploy``进行完全卸载，然后重新执行安装流程。

**Comment by UgOrange** [comment]
如果还出现这个问题，麻烦在mongodb shell中执行``db.fs.chunks.find({"files_id" : ObjectId("637dd5b1d4ddd4ad1a801dda")})``，mongodb 的uri可以在``/elkeid/hub_leader/conf/svr.yaml``中找到

**Comment by h253518892** [comment]
重新安装好多次了，还是不行，重新下安装包安装也不行

**Comment by h253518892** [comment]
应该是操作系统Debian11不兼容，我这边使用docker部署也有问题，后来换Centos7 HAOLE

**Comment by UgOrange** [comment]
好的感谢，这个就先关闭了
