### ISSUE TITLE
容器集群中安全组件状态未启用

### ISSUE THREAD

**Issue by shigithubs** [bytedance/Elkeid#395]
你好，我这边搭建了一个测试集群并按照如下提示，修改了/etc/kubernetes/manifests/kube-apiserver.yaml，并重启了apiserver，但是仍然显示安全组件未安装

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/49743346/207785485-e86cdc12-ae3f-4711-9fea-88d95ffcf4e1.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/49743346/207787128-52b03a8b-1290-44f7-b947-0a4535252cc5.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/49743346/207788374-0fe6b520-65c7-4963-91ba-b1b4b65021b2.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/49743346/207788491-1f8cf4fa-979a-469e-8619-7167b60736ae.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/49743346/207788554-5fc673f5-8859-47c5-a518-3ebf2062cfd4.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/49743346/207788632-4c15cb52-a6e7-46a9-9bb0-174883be1bfd.png">

**Comment by bytecoss** [comment]
请问你是用什么方法重启的 apiserver pod？类似 docker restart 的重启方式不会使配置生效。你可以通过 ps 命令查看一下 apiserver 的容器进程命令行参数是否为修改后的参数，从而判断配置是否生效。

**Comment by shigithubs** [comment]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/49743346/207803736-ede7555a-a4ca-4db5-af78-26487bc02aec.png">
<img width="726" alt="image" src="https://user-images.githubusercontent.com/49743346/207804161-fc8af78f-9f40-4ff3-a9fc-d1659692b3dc.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/49743346/207804244-c77bfa44-1183-4a3f-a9db-28290df119d9.png">
额，我是是用kubeadm进行集群搭建的，修改kube-apiserver.yaml后，api-server会自动重启

**Comment by hugebomb** [comment]
麻烦分别帮忙贴下下面的输出，帮助我们确认下问题。
1）elkeid部署机器上执行 `/root/.elkeidup/elkeidup status`
2）agent center机器上执行 `journalctl -xu elkeid_ac.service | grep error`

**Comment by xjhonly** [comment]
您好，我遇到了类似的问题，1）elkeid部署机器上执行 /root/.elkeidup/elkeidup status 输出和上面一致
2）agent center机器上执行 journalctl -xu elkeid_ac.service | grep error 结果如下图，115这个ip是集群master节点ip。这个报错原因怎么解决呢
<img width="773" alt="0880c08b011093959227" src="https://user-images.githubusercontent.com/38718741/221101910-34e183f5-7962-47d7-8d3f-6c50ca9e342a.png">

**Comment by UgOrange** [comment]
麻烦确认下有修改audit webhook config file吗？麻烦查看一下cluster.server地址是否为https开头的

> 您好，我遇到了类似的问题，1）elkeid部署机器上执行 /root/.elkeidup/elkeidup status 输出和上面一致 2）agent center机器上执行 journalctl -xu elkeid_ac.service | grep error 结果如下图，115这个ip是集群master节点ip。这个报错原因怎么解决呢 <img alt="0880c08b011093959227" width="773" src="https://user-images.githubusercontent.com/38718741/221101910-34e183f5-7962-47d7-8d3f-6c50ca9e342a.png">

**Comment by xjhonly** [comment]
> 麻烦确认下有修改audit webhook config file吗？麻烦查看一下cluster.server地址是否为https开头的
> 
> > 您好，我遇到了类似的问题，1）elkeid部署机器上执行 /root/.elkeidup/elkeidup status 输出和上面一致 2）agent center机器上执行 journalctl -xu elkeid_ac.service | grep error 结果如下图，115这个ip是集群master节点ip。这个报错原因怎么解决呢 <img alt="0880c08b011093959227" width="773" src="https://user-images.githubusercontent.com/38718741/221101910-34e183f5-7962-47d7-8d3f-6c50ca9e342a.png">

![image](https://user-images.githubusercontent.com/38718741/221116685-241a4ef5-856f-4cd1-9b57-4afcb69e009b.png)

确认有修改audit webhook config file，集群内cluster.server如图
![image](https://user-images.githubusercontent.com/38718741/221117303-3ff32f9b-86f9-4ab3-a690-b1924540d588.png)

**Comment by bytecoss** [comment]
@xjhonly 麻烦确认一下修改完配置后，APIserver Pod 是否重建。

你可以使用下面两种方式：
1. 通过移动 kube-apiserver.yaml 来重建 Pod
```
mv /etc/kubernetes/manifests/kube-apiserver.yaml .
mv kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml
```
3. 通过 crictl 命令行工具来重建 Pod
```
POD_ID=$(sudo crictl ps | grep kube-apiserver | awk '{print $9}')
sudo crictl stopp $POD_ID
sudo crictl rmp $POD_ID
```

重启 API Server 后如果问题仍然存在，请提供一下 apiserver 的日志
```
kubectl logs -n kube-system kube-apiserver-XXXXXXXXXX > apiserver.log 
```

**Comment by xjhonly** [comment]
> @xjhonly 麻烦确认一下修改完配置后，APIserver Pod 是否重建。
> 
> 你可以使用下面两种方式：
> 
> 1. 通过移动 kube-apiserver.yaml 来重建 Pod
> 
> ```
> mv /etc/kubernetes/manifests/kube-apiserver.yaml .
> mv kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml
> ```
> 
> 3. 通过 crictl 命令行工具来重建 Pod
> 
> ```
> POD_ID=$(sudo crictl ps | grep kube-apiserver | awk '{print $9}')
> sudo crictl stopp $POD_ID
> sudo crictl rmp $POD_ID
> ```
> 
> 重启 API Server 后如果问题仍然存在，请提供一下 apiserver 的日志
> 
> ```
> kubectl logs -n kube-system kube-apiserver-XXXXXXXXXX > apiserver.log 
> ```

您好，用第一种方式重建pod后显示安装了，感谢

**Comment by UgOrange** [comment]
类似问题麻烦参考上面方法检查问题并且重建apiserver pod，先close该问题了
