### ISSUE TITLE
docker 部署失败

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#396]
docker exec -it elkeid_community bash  进入容器

./elkeidup public 主机IP

![image](https://user-images.githubusercontent.com/99782519/208006678-70bf7b3e-59f7-4721-ac6d-4a836e009c36.png)

执行./elkeidup agent init 
![image](https://user-images.githubusercontent.com/99782519/208006806-1bfc5acc-17e8-4eaf-a469-7a47e78e684a.png)

查看容器服务
![image](https://user-images.githubusercontent.com/99782519/208006868-50f18490-0ea6-4d4b-95d5-38cf20964a5a.png)
没有启动任何服务

**Comment by TaeRoen** [comment]
能看下docker run时的参数吗，感觉是容器里的systemd没起来。能帮忙提供下os版本和systemd版本吗？
同时麻烦容器外执行下 docker log elkeid_community 看下，容器内执行下 systemctl status elkeid_manager 看下。

**Comment by h253518892** [comment]
docker run -d --name elkeid_community --restart=unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8443:8071 -p 443:8072 -p 8080:8080 -p 8089:8080  -p 8090:8090 --privileged elkeid/all-in-one:v1.9.1

**Comment by TaeRoen** [comment]
Failed to get D-Bus 报错就是说明容器里systemd不正常。

容器里用的基础镜像是 centos:7.9.2009 ，宿主机是debian 11.5，怀疑是宿主机内外systemd版本差别过大的。不过制作容器的宿主机是debian 10.9，只差一个debian版本。虽然使用了docker，但是由于systemd依赖了cgroup，还是对宿主机有一定依赖性，我这几天搞个debian 11 虚拟机验证下这里的兼容性。

**Comment by TaeRoen** [comment]
我搞了个debian 11 测了下，确实是容器里 systemd 起不来。
我发现了一个类似的问题，但是没人回答： https://stackoverflow.com/questions/71000762/cant-run-systemd-in-docker-on-debian-11  
建议宿主机用一下debian 10 或 centos 7 试一下。

**Comment by h253518892** [comment]
用Centos 7 正常
