### ISSUE TITLE
用elkeidup装完之后， 如何动态扩容部分组件

### ISSUE THREAD

**Issue by ppd520** [bytedance/Elkeid#397]
**Describe the bug**
社区版本，在用elkeidup装完之后，如果想多加几个ac和sd的服务器，应该怎么操作？

**Comment by TaeRoen** [comment]
文档这两天会补充到 https://elkeid.bytedance.com/ 上面，补充好了后我再回复到这里

**Comment by TaeRoen** [comment]
参考这个文档吧
https://elkeid.bytedance.com/Chinese/ElkeidUp/expansion.html
