### ISSUE TITLE
Anolis系统下agent提示找不到collector插件

### ISSUE THREAD

**Issue by MrBe1ieVe** [bytedance/Elkeid#401]
**Describe the bug**

1. 资产指纹部分，点击采集数据页面返回正常，命令正常下发，但无数据显示

![image](https://user-images.githubusercontent.com/21039254/208250398-62af9c9d-ba2e-49c4-b59c-c78a2d81c5c2.png)

![image](https://user-images.githubusercontent.com/21039254/208250378-8daad1f5-1f79-47fb-8c5d-c418a3771090.png)

<img width="980" alt="image" src="https://user-images.githubusercontent.com/21039254/208250407-d04eee92-2c20-4e3f-a347-55cb23519a3f.png">

主机部分资产显示正常
![image](https://user-images.githubusercontent.com/21039254/208251145-d0488a77-3cc4-4dee-aa33-9fd0798b6cca.png)

2. 尝试执行反弹shell，无告警，hub无qps变化、无数据。

3. 尝试过根据[elkeid_console可以监测到agent的心跳并更新，但获取不到资产数据包#227](https://github.com/bytedance/Elkeid/issues/227)进行排查，发现无`/elkeid/hub/py/plugin.stdout`，执行`sh run.sh`后如下输出
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/21039254/208250733-0f06376b-c287-4cf9-8ff0-9e1f90c76457.png">。刷新后仍无记录。

4. 尝试按照[collector - Elkeid Docs](https://elkeid.bytedance.com/Chinese/elkeid/plugin/collector.html) 进行配置策略和同步配置，仍然提示`transport/transfer.go:213       can't find plugin: collector`
![image](https://user-images.githubusercontent.com/21039254/208250842-8dd192b4-b489-43be-8ed9-6ccf655d55ee.png)
![image](https://user-images.githubusercontent.com/21039254/208250891-daef557e-965c-4000-9636-1fa55795d868.png)

**To Reproduce**
1. 通过elkeidup，在[anolis OS 7.9](https://openanolis.cn/download)镜像中启动并部署
2. 在多个系统为anolis os 7.9的系统上安装splunk、webgoat，并执行默认安装命令等进行测试
4. 页面无输出

**OS information (please complete the following information):**
 - Distribution: anolis
 - Version: 7.9
 - Kernel info: Linux 3.10.0-1160.an7.x86_64 x86_64

**Comment by Serinalice** [comment]
确认主机详情——插件列表有无collector条目，如没有，请下发同步配置任务将组件策略同步至Agent。具体操作请参考：https://github.com/bytedance/Elkeid/blob/main/server/docs/console_tutorial/Elkeid_Console_manual.md#%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86

**Comment by EBWi11** [comment]
driver 插件目前暂不支持Anolis，具体支持列表：https://github.com/bytedance/Elkeid/tree/main/driver#about-the-compatibility-with-linux-distributions 数据无法采集因此入侵检测无告警
