### ISSUE TITLE
怎么手动删除告警？

### ISSUE THREAD

**Issue by PhuketIsland** [bytedance/Elkeid#408]
示例策略误报导致告警量过高然后后端整体负载过高了，需要手动删除告警

**Comment by UgOrange** [comment]
告警数据存放在``hub_alarm_v1``表中，可以通过删除该表的数据来删除告警：
- 首先使用mongo URI进入mongo shell ``/elkeid/mongodb/mongodb_4.2/bin/mongo 这里填uri``
- 进入shell后执行 ``use elkeid``和``db.hub_alarm_v1.deleteMany({})``删除数据

**Comment by PhuketIsland** [comment]
删除了，
![image](https://user-images.githubusercontent.com/28825226/210950354-ddad2a88-70bd-4faa-8989-64a48e492289.png)

**Comment by PhuketIsland** [comment]
问题已解决，感谢
