### ISSUE TITLE
下发任务之后agent还是显示1.7版本

### ISSUE THREAD

**Issue by PhuketIsland** [bytedance/Elkeid#410]
![a22d1cb7-47d1-4f43-871d-64913783513f](https://user-images.githubusercontent.com/28825226/211269873-05b4bd90-6b2f-4291-af1e-bf071be90346.jpeg)
![83b463d6-fbdb-4779-acc3-77d180fa2d0a](https://user-images.githubusercontent.com/28825226/211269912-e85ff947-bf7c-4d34-8268-e2d72c782314.jpeg)
按照文档操作 升级完的agent还是v1.7版本

**Comment by PhuketIsland** [comment]
没有什么报错

**Comment by PhuketIsland** [comment]
![企业微信截图_1673335558601](https://user-images.githubusercontent.com/28825226/211488463-35cffe3b-15ed-496d-9693-85bb9b542671.png)
没有什么报错

**Comment by Percivalll** [comment]
在组件策略页面截图看下呢

**Comment by Percivalll** [comment]
看你的日志截图，端上组件的确已经是升级后的了，请再确认下

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/211697037-005c5392-84e8-472a-b8cc-cdfb83bdc1b5.png)
但是版本还是显示1.7

**Comment by Percivalll** [comment]
这里的版本和Elkeid发布的大版本不是一个概念 这里只要和组件策略的版本保持一致就是符合预期的

**Comment by PhuketIsland** [comment]
好的 谢谢
