### ISSUE TITLE
[v1.9.1]使用elkeidup进行完整部署，./elkeidup init --host 192.168.1.1报错

### ISSUE THREAD

**Issue by lovepoem** [bytedance/Elkeid#413]
**Expected behavior**
使用elkeidup进行完整部署成功。 

**Screenshots**
使用elkeidup进行完整部署时候：  When I run `./elkeidup init --host 192.168.1.1`

It occurs error 
![image](https://user-images.githubusercontent.com/827112/211973269-61e5b0aa-95c6-491b-b8b6-6b0780fea14f.png)

![image](https://user-images.githubusercontent.com/827112/211973244-29c416d9-1900-4d64-a2a5-8217ce1e50d8.png)

**OS information (please complete the following information):**
 - Distribution: centos
 - Kernel info 4.18.0-147.5.1.el8_1.x86_64
elkeidup_package_v1.9.1.tar.gz

**Comment by lovepoem** [comment]
The second error
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/827112/212621660-b65a5cf2-e615-429d-aec8-e284e5f00d7c.png">

**Comment by TaeRoen** [comment]
没读到 config.yaml，确认下 elkeidup的执行目录和config.yaml都在 /root/.elkeidup 下

**Comment by lovepoem** [comment]
> 没读到 config.yaml，确认下 elkeidup的执行目录和config.yaml都在 /root/.elkeidup 下

<img width="666" alt="image" src="https://user-images.githubusercontent.com/827112/212623965-a2bcfea8-0514-4513-b3fc-6289a2c3654e.png">
目前在一个目录了。 文件读写权限和所属组都一样

**Comment by TaeRoen** [comment]
目前都是在root用户下运行和测试的，即使在容器里，也是root用户。

**Comment by lovepoem** [comment]
> 目前都是在root用户下运行和测试的，即使在容器里，也是root用户。

chown统一成 root:root 用户，755权限，还是报错：

	when deploying, an error occurred: Redis component load init faield: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 root@192.168.1.1  echo elkeid_$ failed, err: exit status 255, stderr: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by lovepoem** [comment]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/827112/216040757-3493fbde-5415-4c99-aa04-a5be5ab43da8.png">
[ERRO]	2023-02-01T20:13:12+08:00	when deploying, an error occurred: NodeExporter installed faield: exec install shell failed when install node_exporter, err: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 -i /root/.ssh/id_rsa root@xxxxxx /elkeid/node_exporter/install_node_exporter.sh failed, err: exit status 1, stderr: Failed to get D-Bus connection: Operation not permitted
Configuration file /etc/systemd/system/elkeid_node_exporter.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Configuration file /etc/systemd/system/elkeid_node_exporter.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Created symlink from /etc/systemd/system/multi-user.target.wants/elkeid_node_exporter.service to /etc/systemd/system/elkeid_node_exporter.service.
Failed to get D-Bus connection: Operation not permitted,  Failed to get D-Bus connection: Operation not permitted
Configuration file /etc/systemd/system/elkeid_node_exporter.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Configuration file /etc/systemd/system/elkeid_node_exporter.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Created symlink from /etc/systemd/system/multi-user.target.wants/elkeid_node_exporter.service to /etc/systemd/system/elkeid_node_exporter.service.
Failed to get D-Bus connection: Operation not permitted
