### ISSUE TITLE
hub内部错误

### ISSUE THREAD

**Issue by PhuketIsland** [bytedance/Elkeid#416]
![5b1762f1-4d52-4c1f-bf38-8704ba4d250a](https://user-images.githubusercontent.com/28825226/212027321-7c3bff2d-81f1-469c-bd10-83cf75c3dccd.jpeg)
![b13fe773-0a79-438b-9c51-25570a721c26](https://user-images.githubusercontent.com/28825226/212027335-e3fb39c0-2e5d-4919-95ec-e9fb7d6aab06.jpeg)
按照文档上给的nmap 进行测试 出现这个报错

**Comment by chiselX** [comment]
谢谢反馈,该问题已修复,随下个版本一起更新;对单条规则的测试可以点进规则集,对单条进行测试
![image](https://user-images.githubusercontent.com/22535169/212221848-25c2db4d-60bd-4730-a541-6de9c52cba9c.png)

**Comment by UgOrange** [comment]
最新版本已经fix，可以升级再测试下
