### ISSUE TITLE
使用示例给的nmap无法触发告警

### ISSUE THREAD

**Issue by PhuketIsland** [bytedance/Elkeid#417]
规则集里面的规则按照hub使用手册里面给的规则
![image](https://user-images.githubusercontent.com/28825226/212611833-e30f4522-c55b-4e34-b2ae-357b0e43450c.png)
输入源是默认的hids
![image](https://user-images.githubusercontent.com/28825226/212613108-3efa3795-5837-4285-9dc8-240cbc55131f.png)
项目就是输入源的hids--> 规则集配置好的nmap规则 然后发布项目启动项目，但就是无法触发告警

**Comment by EBWi11** [comment]
1. ”规则集配置好的nmap规则“ 是新的ruleset？那是否有配置action plugin将告警推送到console？若console上无法观察到对应告警
2. HUB是一个独立的系统，并不是在HUB中检出就会在Console上看到告警，这个是需要中间约定和具体推送流程的

**Comment by PhuketIsland** [comment]
那要怎么配置才能推送到console上呢？就是编写插件然后在rule的检测完成后添加action吗？具体推送到console插件怎么写？如果不使用HUB的话 console上的告警要怎么产生呢？

**Comment by EBWi11** [comment]
1. 调用方式参考：https://github.com/bytedance/Elkeid-HUB/blob/main/config/elkeid_hids/ruleset/push_hids_alert.xml
2. 不需要你自己实现，我们已经实现并且内置了，所以直接调用即可
3. 需要阅读manager代码然后调用manager api实现告警产生
整体流程相对复杂但实际不难理解，目前开源已经实属不易，文档确实比较匮乏但短时间也确实没有人力可以维护了，目前社区完全依赖Elkeid Team输入，已经不堪重负，希望可以提前阅读完大概逻辑和quickstart，阅读源码也是一个选择。

**Comment by EBWi11** [comment]
同样关于“如何编写插件”等相关文档已经有详细操作，建议先完整的完整的操作一遍 https://elkeid.bytedance.com/Chinese/hub/quick_start/quick_start.html 然后再去理解 https://github.com/bytedance/Elkeid-HUB/tree/main/config/elkeid_hids 这里的相关配置，应该可以顺利上手

**Comment by PhuketIsland** [comment]
好的谢谢
