### ISSUE TITLE
node_exporter安装失败

### ISSUE THREAD

**Issue by o0x1024** [bytedance/Elkeid#421]
node_exporter服务安装失败
环境：
```
centos 7   8C8G
内核：3.10.0-1160.el7.x86_64

```
```
when deploying, an error occurred: NodeExporter installed faield: node exporter check failed, err: retry with 0 times and still failed, error: get http://192.168.49.129:9990/metrics code is not 200 when test
```

![image](https://user-images.githubusercontent.com/53891640/216253438-3f7b3358-9570-4fd0-988d-7a19ba359377.png)

**Comment by TaeRoen** [comment]
@o0x1024 
是不是有科学上网的代理，这个503好像是代理软件返回的
可以在安装失败后，卸载前 curl -v 看下

**Comment by o0x1024** [comment]
> @o0x1024 是不是有科学上网的代理，这个503好像是代理软件返回的 可以在安装失败后，卸载前 curl -v 看下

看样子是代理的问题。

**Comment by fanjiarong2343** [comment]
怎么处理的呀
