### ISSUE TITLE
agent编译报错

### ISSUE THREAD

**Issue by leoriclee825** [bytedance/Elkeid#424]
我参考单机docker快速部署，在虚拟机上部署，控制台可以访问，但agent build报错，收集信息如下：
1.系统版本：centos7.5
![405715db-cdfd-40c2-add0-0f6a39c4440b](https://user-images.githubusercontent.com/33215637/217768897-cab73a6f-0afd-4c9c-8d72-99e704521eb2.jpeg)
2. ko列表里只有 hids_driver_1.7.0.9_3.10.0-862.el7.x86_64_amd64，我从github下载ko包改成hids_driver_1.7.0.9_3.10.0-862.el7.x86_64_x86_64放到容器目录：
![e5606a34-11c7-4277-a864-9898a01cc087](https://user-images.githubusercontent.com/33215637/217768993-0447e85c-e6ad-4028-8ebf-b3cbeb71ea80.jpeg)
3.编译agent报错：
![cabe583b-28e9-45cd-9903-226e1a261138](https://user-images.githubusercontent.com/33215637/217769085-b8c92cad-4e28-42a2-b524-0e46af737bd9.jpeg)
没有install.sh脚本
![cf131cba-b01c-4958-9402-6256afa0ddef](https://user-images.githubusercontent.com/33215637/217769146-4bfe347c-8442-46b3-bcd7-9f80fd6f0324.jpeg)
4.自检信息：
![f066537e-ba0e-447b-9283-799893204423](https://user-images.githubusercontent.com/33215637/217769204-bb0dc2ce-c491-4048-8283-8d00c01b34f3.jpeg)
后续：
![1bbcdcc2-ed79-43e5-831f-cd4e80320c62](https://user-images.githubusercontent.com/33215637/217769239-678c0286-1ff7-4306-8854-6555b3e64c95.jpeg)

**Comment by TaeRoen** [comment]
2. 先不用管ko，ko可以在release界面单独下载或者自动下载
4. 不影响，为了减少image文件打下，这个文件夹被清理了

可以重新按docker 部署的文档走成功后，再看ko部分。

**Comment by leoriclee825** [comment]
谢谢@TaeRoen，照官方文档重装，在询问自动下载缺失预编译ko服务开启时选q，后面还是在执行./elkeidup agent build 时报错，错误信息：exit status 2

**Comment by TaeRoen** [comment]
agent init成功了说明容器内后端服务起来了。
是先执行的 agent init，后执行的agent build 是吧。agent build 报错是只有 exit status 2 这一行吗？

**Comment by TaeRoen** [comment]
看下有无这个文件 /root/.elkeidup/.elkeidup_cmd.out  里面应该有执行build.sh 的报错

**Comment by UgOrange** [comment]
由于长期没有回复，关闭此issue，如仍有问题欢迎提issue
