### ISSUE TITLE
Hub发布规则失败

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#426]
发布规则失败，需要看什么日志排查问题，页面显示失败详情：Post "https://10.20.4.217:8091/api/v1/sync/rule": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
![image](https://user-images.githubusercontent.com/44428568/218251380-d7cdc0ff-030f-4d98-9db2-88b93f373329.png)

**Comment by TaeRoen** [comment]
通常是某一个output有问题，stop不掉。
比如说这前填错了一个output kafka的地址，写不进去。如果下次把kafka的地址改对了，发布规则。hub为了避免丢数据，就在等这个output把数据处理掉，然后就超时了。
如果现在的output和ruleset都是对的，建议直接重启hub。
