### ISSUE TITLE
如果像redis、mongo这些服务直接采用云上环境，是不是elkeidup就不能用了

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#427]

**Comment by TaeRoen** [comment]
可以用，但是费点事。
可以在elkeidup上临时填一个redis，mongo的机器，然后部署完成后把mongo，redis停掉，mongodb 数据导入到云上，然后改一下ac，manager，leader，sd的redis，mongo连接地址，全重启即可。
这个问题我实际部署时也遇见过，上述解决了一次，同时还多换了一个kafka。我们内部版本考虑过这个问题，但是社区版涉及到一些依赖，比如需要mongodb机器上的命令行工具导入数据，来不及在这个版本改了。
