### ISSUE TITLE
elkeidup部署时报错

### ISSUE THREAD

**Issue by NoviceMao** [bytedance/Elkeid#428]
**Describe the bug**
[ERRO]	2023-02-13T16:16:10+08:00	when deploying, an error occurred: Hub installed faield: retry with 0 times and still failed, error: Get "https://172.16.15.144:8091/getInputs": dial tcp 172.16.15.144:8091: connect: connection refused

**To Reproduce**
1. ./elkeidup deploy

**Expected behavior**
部署过程发生报错

**Screenshots**
![image](https://user-images.githubusercontent.com/65475570/218407470-e7c9d205-3af4-49f2-942d-f30526eded33.png)
![image](https://user-images.githubusercontent.com/65475570/218407564-bdf02c00-2ff5-4dde-9458-9725e5bc63cc.png)
![image](https://user-images.githubusercontent.com/65475570/218407924-a32316ce-3e6a-4398-89ca-ee439b7c4160.png)
![image](https://user-images.githubusercontent.com/65475570/218408210-f9061f90-6926-4a88-9583-dbccfd24dfa2.png)

**OS information (please complete the following information):**
 - Distribution: [Debain]
 - Version [5.10.0-21-amd64]
 - Kernel info [SMP Debian 5.10.162-1 (2023-01-21)]

**Additional context**

**Comment by UgOrange** [comment]
您好，请问系统是debian 11吗，可以查看下#392，看起来是一样的兼容性问题导致的

**Comment by UgOrange** [comment]
确认是elkeidup 安装mongodb的时候对debian11的支持有问题，下个版本会修复

**Comment by UgOrange** [comment]
目前debian11导致的部署问题已经fix

**Comment by fubuki8087** [comment]
> 目前debian11导致的部署问题已经fix

您好，Ubuntu 22.04又出现相同的问题了，可以介绍一下应该怎么诊断修复吗？谢谢！

**Comment by fubuki8087** [comment]
听说是跟MongoDB有关，这些信息可能对您有用
![image](https://github.com/user-attachments/assets/9dcb46c4-eae6-4ad9-a75b-d36e43a608d8)

**Comment by fubuki8087** [comment]
好像我当时是退回Ubuntu 20.04安装的，我印象中最后安装成功了。不过事情过去比较久了，可能记得不是太清楚
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年09月18日 20:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bytedance/Elkeid] elkeidup部署时报错 (Issue #428) |
mikawudi left a comment (bytedance/Elkeid#428)

听说是跟MongoDB有关，这些信息可能对您有用 image.png (view on web)

同样是ubuntu22.04撒,遇到相同问题,请问您那边后续处理成功了吗?

**Comment by mikawudi** [comment]
> 好像我当时是退回Ubuntu 20.04安装的，我印象中最后安装成功了。不过事情过去比较久了，可能记得不是太清楚
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2025年09月18日 20:00 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [bytedance/Elkeid] elkeidup部署时报错 (Issue [#428](https://github.com/bytedance/Elkeid/issues/428)) |
> mikawudi left a comment ([bytedance/Elkeid#428](https://github.com/bytedance/Elkeid/issues/428))
> 
> 听说是跟MongoDB有关，这些信息可能对您有用 image.png (view on web)
> 
> 同样是ubuntu22.04撒,遇到相同问题,请问您那边后续处理成功了吗?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

好吧,感谢,但是我这边基线不能用20了.......蛋疼ing
