### ISSUE TITLE
elkeidup deploy 部署报错

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#431]
![微信截图_20230214174253](https://user-images.githubusercontent.com/5724472/218698296-323ff47b-3af0-4c02-9158-915ce3e34694.png)

我单独运行了一下 /elkeid/nginx/nginx/nginx -c /elkeid/nginx/nginx/nginx.conf
![微信截图_20230214180023](https://user-images.githubusercontent.com/5724472/218702528-c54b8d62-c1e4-4201-b761-e875212578dc.png)

**Comment by TaeRoen** [comment]
图里单独运行的话是以root用户身份运行，这个报错是root用户运行的报错，其实不是真实错误。
可以贴下提示里的 systemctl status elkeid_nginx 看下报错。
或者 一个窗口 journalctl -fu elkeid_nginx , 另一个窗口 systemctl restart elkeid_nginx 看一下。

**Comment by anquanscan** [comment]
@TaeRoen 我分别执行了 
journalctl -fu elkeid_nginx
systemctl restart elkeid_nginx
systemctl status elkeid_nginx.service

并且我单独执行了  /elkeid/nginx/nginx/nginx -c /elkeid/nginx/nginx/nginx.conf ，来单独启动nginx 
提示报错如下
![微信截图_20230215103710](https://user-images.githubusercontent.com/5724472/218913317-90759933-396a-4943-a431-cf6702821d86.png)


getpwnam("nobody") disabled for static build (38: Function not implemented)
是不是静态编译的nginx有些功能受到了限制

我本机版本如下
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TaeRoen** [comment]
关键错误是这个 [::]:8071 family not supported by protocol 
是不是机器没开ipv6。

**Comment by anquanscan** [comment]
@TaeRoen 问题解决了，非常感谢。确实是没有开启ipv6的问题，希望后续可以增加一些错误提示。

**Comment by anquanscan** [comment]
完美解决
