### ISSUE TITLE
Hub的KAFKA INPUT能否自定义固定消费组

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#432]
如题，Hub的KAFKA INPUT能否自定义固定消费组，当前HUB的KAFKA消费组命名是【自定义前缀_INPUT ID_随机8位字符】，附加的随机8位字符导致消费组无法固定

**Comment by EBWi11** [comment]
该功能为社区版HUB限制无法取消，仅商业版HUB支持固定 Kafka Group ID
