### ISSUE TITLE
Hub v1.9.1.2 CEP功能无效

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#433]
Hub v1.9.1.2 CEP功能无效
配置CEP策略，无法正确检出：
![image](https://user-images.githubusercontent.com/44428568/218801832-a95a5b69-9350-46d7-bcf7-e033c0c02411.png)
![image](https://user-images.githubusercontent.com/44428568/218802023-50bafc59-07a5-4dfd-8867-ba1045238a5b.png)

无CEP策略，正常检出：
![image](https://user-images.githubusercontent.com/44428568/218802255-3331eb76-8374-4e8b-8d14-50d0918cc0ef.png)
![image](https://user-images.githubusercontent.com/44428568/218802437-ef3672c7-fcd0-47b7-9029-cd464c96436c.png)

**Comment by chiselX** [comment]
感谢反馈，会在下次更新中修复
