### ISSUE TITLE
elkeidup 卸载组件错误 

### ISSUE THREAD

**Issue by o0x1024** [bytedance/Elkeid#434]
第一次卸载组件的时候报错了，应该是免密登录出问题了
![image](https://user-images.githubusercontent.com/53891640/218907080-72f561e8-7abd-4949-ac55-f5a704aca682.png)

当配置好免密登录后，再次卸载时，显示已经卸载完成，但是实际上是没有卸载成功的
![image](https://user-images.githubusercontent.com/53891640/218906819-a41c7040-153f-4068-b2ca-52c119ab0e5c.png)

elkeidup是通过什么标志来判断是否卸载成功的呢？此种情况下有没有办法使用elkeidup重新全部卸载，感谢。

**Comment by EBWi11** [comment]
逐个登陆后段服务器 find /elkeid/ -name "uninstall.sh"，然后执行存在的uninstall脚本

**Comment by o0x1024** [comment]
好的，感谢
