### ISSUE TITLE
Elkeid Hub升级失败

### ISSUE THREAD

**Issue by xufengnian** [bytedance/Elkeid#435]
服务端CentOS 7.9 x86_64
从1.9.1版本升级到1.9.1.2时，根据教程https://elkeid.bytedance.com/Chinese/ElkeidUp/ElkeidUp.html#5-%E9%87%8D%E8%A3%85%E6%8C%87%E5%AE%9A%E7%BB%84%E4%BB%B6
下载解压对应tar.gz，使用教程步骤reinstall Hub时，出现如下报错
![image](https://user-images.githubusercontent.com/15324125/218911756-3c3b4691-0301-472e-9743-2078add1289c.png)

**Comment by TaeRoen** [comment]
Hub 启动异常，麻烦看下这些log。
systemctl status elkeid_hub 看下hub是否在反复重启，有没有什么输出。
/elkeid/hub/log/smith.log hub的log文件，重点看下重启前的输出。
/elkeid/log/hub.log hub的标准输出文件，同样重点看下重启前的输出。

**Comment by xufengnian** [comment]
systemctl status elkeid_hub 未见异常，/elkeid/log/hub.log和/elkeid/hub/log/smith.log内容如下，似乎有个panic的错误
![image](https://user-images.githubusercontent.com/15324125/218962706-85457952-9a50-4d75-afa8-27aaf840f3bb.png)
![Uploading image.png…]()

**Comment by xufengnian** [comment]
同时升级hub后出现了无法手机主机资产指纹和基线检查的问题，提示检测超时，baseline插件好像没有运行起来
![image](https://user-images.githubusercontent.com/15324125/218963740-f363da6e-745f-409e-a9de-d12deb3f6386.png)

**Comment by UgOrange** [comment]
上面是由于hub无法正常工作导致的，麻烦再看下``/elkeid/hub/plugin/output/plugin.stdout``

**Comment by xufengnian** [comment]
@UgOrange 目前/elkeid/hub/plugin/output/plugin.stdout是这个状态，同时页面也显示HUB及数据服务处理模块存在异常
![image](https://user-images.githubusercontent.com/15324125/219306541-fa142dc5-1387-4fbb-8b23-2aa262da60e8.png)
![image](https://user-images.githubusercontent.com/15324125/219306540-9eeb85fd-54df-47f7-9ed6-1c431b3642a6.png)
![image](https://user-images.githubusercontent.com/15324125/219306855-6d62c9b5-2cdf-4228-b426-dd0facd3d143.png)
![image](https://user-images.githubusercontent.com/15324125/219306865-a523f402-4225-45aa-8e8c-312fc829da7b.png)

**Comment by xufengnian** [comment]
@UgOrange 这里什么都没有，我理解还是有问题的
![image](https://user-images.githubusercontent.com/15324125/219327669-1aafc455-c58b-474a-9505-ac8c9e0f27df.png)

**Comment by UgOrange** [comment]
这里是有问题的，你这边升级重新安装了哪些组件？这边看没有策略数据

**Comment by xufengnian** [comment]
Hub
Hub Leader
Manager
AgentCenter

**Comment by UgOrange** [comment]
目前看策略数据有问题，建议依次重新安装如下组件
- MongoDB
- MongoDBLeaderData
- MongoDBManagerData
- HubLeader
- Manager
对后台数据进行重建，不过这一操作也会导致agent相关的组件数据丢失，所以也需要重新进行agent build相关操作

**Comment by xufengnian** [comment]
@UgOrange 感谢支持，我通过重装的方式，正常安装了1.9.1.2版本，过程中遇到Kafka,mongo,hub时超时的问题，我通过Ctrl-Z临时挂起安装程序，等待相应端口启动后，再fg恢复安装程序的方式解决此问题
