### ISSUE TITLE
agent 安装成功，并且没有报错，但是agent 安装目录没有找到组件目录

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#437]
执行完   bash -c "if (command -v curl); then (curl -sS http://127.0.0.1:8080/agent/install.sh | bash);else (wget -q -O - http://127.0.0.1:8080/agent/install.sh | bash); fi"

agent 安装成功，并且没有报错，但是agent 安装目录没有找到组件目录
也不采集基础信息，之前用docker 安装，看到agent目录下面有一个 plugin目录，请问这种问题怎么排查呢？ 
![微信截图_20230215165147](https://user-images.githubusercontent.com/5724472/218980490-f68a6450-096e-49b7-98b1-a342a104892e.png)
![微信截图_20230215165402](https://user-images.githubusercontent.com/5724472/218980500-2cc0ba78-4333-49f0-96e5-d9a738033270.png)

**Comment by TaeRoen** [comment]
elkeidup agent policy create 命令执行了吗？如果没有的话，重启agent 实施。

看一下 系统管理 - 组件策略 界面，这个界面有东西吗？

**Comment by anquanscan** [comment]
@TaeRoen 感谢，按照提示，现在好了
