### ISSUE TITLE
1.9.1.2 功能失效

### ISSUE THREAD

**Issue by o0x1024** [bytedance/Elkeid#438]
1.如下图，主机详情处，后退按钮失效，无网络请求
![image](https://user-images.githubusercontent.com/53891640/219297837-d596e8a3-d105-407f-83f9-43ec99e1d343.p.ng)
2.如下图，批量导致功能无数据返回
![image](https://user-images.githubusercontent.com/53891640/219298463-31350213-428a-431a-bd63-030d8a56b1dc.png)

**Comment by Smartuu** [comment]
你好，多谢你的反馈问题2已经修复，你可以拉取代码进行更新。
