### ISSUE TITLE
咨询一下数据的疑问

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#440]
想请问一下  后端服务状态 首页统计的原理是什么，部署完成之后，时而显示正常，时而显示服务不可用。
![微信截图_20230216164306](https://user-images.githubusercontent.com/5724472/219313504-0f3900cd-49b1-4d5a-9586-3e99dc1d1384.png)
![微信截图_20230216164737](https://user-images.githubusercontent.com/5724472/219314307-5b02f5bd-82bf-44b2-98eb-1d2d475fc442.png)

**Comment by TaeRoen** [comment]
@anquanscan 
这三部分的数据基于prometheus。
接入服务基于是agent center的qps和机器负载，存储服务是kafka的qps和机器负载，数据处理服务是hub input的qps和机器负载。
如果从prometheus拿到的qps为0或拿不到qps，会显示服务不可用。
qps不为0时，会计算该服务所在机器的cpu和内存情况，显示未低负载，中负载，或高负载。
