### ISSUE TITLE
[plugins] - collector - failed to get sversion for redis-server

### ISSUE THREAD

**Issue by chriskaliX** [bytedance/Elkeid#442]
**Describe the bug**
In apps.go, redis-server version is not collected correctly.

```bash
root@VM-4-11-ubuntu:~# redis-server -v
Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
```

While in Elkeid, the output like this
```golang
map[conf: container_id: container_name: exe:/usr/bin/redis-check-rdb name:redis package_seq:fc655de9 pid:12148 start_time:1676561986 sversion: type:database]
```

**To Reproduce**
1. Install the redis using apt/yum
2. Run the collector to get the output

**Expected behavior**
The version should be 6.0.16

**OS information (please complete the following information):**
 - Distribution: Ubuntu
 - Versio: 22.04
 - Kernel info: 5.15.0-56-generic

**Additional context**
The reason I think, the way that we execute the redis version command cause the problem. In my situation, `/usr/bin/redis-server` is an symbolic link to `/usr/bin/redis-check-rdb`

```bash
root@VM-4-11-ubuntu:~/Elkeid/plugins/collector# ls -la /usr/bin/redis-server 
lrwxrwxrwx 1 root root 15 Mar  4  2022 /usr/bin/redis-server -> redis-check-rdb
```

since we use the exe path, it will execute like this

```bash
root@VM-4-11-ubuntu:~/Elkeid/plugins/collector# /usr/bin/redis-check-rdb -v
[offset 0] Checking RDB file -v
```

**References**
- https://github.com/redis/redis/issues/7663

**Comment by askyLYZ** [comment]
bug已验证，感谢反馈，预计下一个版本修复该问题，

**Comment by askyLYZ** [comment]
> **Describe the bug** In apps.go, redis-server version is not collected correctly.
> 
> ```shell
> root@VM-4-11-ubuntu:~# redis-server -v
> Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
> ```
> 
> While in Elkeid, the output like this
> 
> ```go
> map[conf: container_id: container_name: exe:/usr/bin/redis-check-rdb name:redis package_seq:fc655de9 pid:12148 start_time:1676561986 sversion: type:database]
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install the redis using apt/yum
> 2. Run the collector to get the output
> 
> **Expected behavior** The version should be 6.0.16
> 
> **OS information (please complete the following information):**
> 
> * Distribution: Ubuntu
> * Versio: 22.04
> * Kernel info: 5.15.0-56-generic
> 
> **Additional context** The reason I think, the way that we execute the redis version command cause the problem. In my situation, `/usr/bin/redis-server` is an symbolic link to `/usr/bin/redis-check-rdb`
> 
> ```shell
> root@VM-4-11-ubuntu:~/Elkeid/plugins/collector# ls -la /usr/bin/redis-server 
> lrwxrwxrwx 1 root root 15 Mar  4  2022 /usr/bin/redis-server -> redis-check-rdb
> ```
> 
> since we use the exe path, it will execute like this
> 
> ```shell
> root@VM-4-11-ubuntu:~/Elkeid/plugins/collector# /usr/bin/redis-check-rdb -v
> [offset 0] Checking RDB file -v
> ```
> 
> **References**
> 
> * [[QUESTION] why `redis-server` is a symbolic link of `redis-check-rdb` in Redis server v=5.0.7 ? redis/redis#7663](https://github.com/redis/redis/issues/7663)

bug已验证，感谢反馈，预计下一个版本修复该问题。

**Comment by askyLYZ** [comment]
bug已验证，感谢反馈，预计下一个版本修复该问题。

**Comment by askyLYZ** [comment]
![image](https://user-images.githubusercontent.com/30401729/219613647-02ef05e0-d2e9-434c-b3c3-1ea7935a9463.png)

**Comment by askyLYZ** [comment]
因为redis-server和redis-check-rdb中有大部分逻辑是通用的，因此会在相同程序中，判断argv[0]来执行不同的逻辑：
[https://github.com/redis/redis/blob/5b61b0dc6d2579ee484fa6cf29bfac59513f84ab/src/server.c](url)
我们会在下一个版本对该问题进行修复。再次感谢反馈🤝
