### ISSUE TITLE
测试消费kafka失败

### ISSUE THREAD

**Issue by goldboy123** [bytedance/Elkeid#444]
使用测试文件kafka_comsumer.go 消费数据失败，提示：
[root@fcf287035a66 tmp]# ./kafka_comsumer 
NewClient error:kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
NewConsumer error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
测试文件：
package main

import (
  "fmt"
  "github.com/bytedance/Elkeid/server/agent_center/common/kafka"
)

func main() {
  p, err := kafka.NewConsumer([]string{"127.0.0.1:9092"}, "hids_svr")
  if err != nil {
        fmt.Printf("NewConsumer error: %v\n", err)
        return
  }

  p.StartConsume()
}

**Comment by EBWi11** [comment]
不要用127，用local ip试下

**Comment by goldboy123** [comment]
用局域网IP有测试过，也是不行，一样的错误，使用kafka客户端查看提示 broke out 什么的

**Comment by EBWi11** [comment]
elkeid kafka 有鉴权并且数据流是pb格式，可以试下这个工具 https://github.com/0xlwoe21k/elkeid_kafka_read
还有这个文档中：https://github.com/bytedance/Elkeid/blob/main/elkeidup/raw_data_usage_tutorial/raw_data_usage_tutorial-zh_CN.md

**Comment by goldboy123** [comment]
工具可以用，感谢
