### ISSUE TITLE
agent部署失败

### ISSUE THREAD

**Issue by la00gke** [bytedance/Elkeid#447]
![图片](https://user-images.githubusercontent.com/125958751/220285428-3a613741-040a-4fe5-9a7a-b87d14469661.png)

然后看来一下服务端状态
如下
#> ./elkeidup status
[INFO]	2023-02-21T08:10:17Z	Kafka:
[ERRO]	2023-02-21T08:10:17Z	127.0.0.1 elkeid_kafka SSH Connect Error: execute -o StrictHostKeyChecking no -o PasswordAuthentication no -p 22 -i /root/.ssh/id_rsa root@127.0.0.1 systemctl is-active elkeid_kafka failed, err: exit status 3, stderr: 
[WARN]	2023-02-21T08:10:17Z	kafka connect Err 127.0.0.1:9092 %!w(*fmt.wrapError=&{failed to dial: failed to open connection to 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused 0xc0002c6280})

**Comment by TaeRoen** [comment]
@la00gke 
我先介绍一下链路，agent首先连接nginx的8090端口，反向代理到sd，正常会返回一个agent center的地址，端口号是6701。报错是agent连接了nginx的8090端口，是个四层代理，直接代理到agent center。看报错猜测是agent center没起来，agent center大概率是kafka有问题。

麻烦先分别执行 
systemctl status elkeid_kafka
systemctl status elkeid_ac 
看下，看下报错信息。

**Comment by la00gke** [comment]
![图片](https://user-images.githubusercontent.com/125958751/220288263-554a1e4c-d0fb-4593-98b3-ac8233f2b0c1.png)

**Comment by UgOrange** [comment]
目前kafka没有起来，麻烦看下kafka的log：
``tail -f -n 100 /elkeid/kafka/kafka_2.13-3.2.3/logs/server.log``

**Comment by la00gke** [comment]
![图片](https://user-images.githubusercontent.com/125958751/220303334-33d7ca75-8f5d-4a23-9aaa-ad2e7a231461.png)

**Comment by la00gke** [comment]
{"level":"info","ts":1676971678.214938,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971678.2151654,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971678.2151778,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971678.2151823,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971678.2151945,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971678.2151983,"msg":"Sarama","info":["Closing Client"]}
{"level":"info","ts":1676971680.4655716,"msg":"Sarama","info":["Initializing new client"]}
{"level":"info","ts":1676971680.4656417,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971680.4665575,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.4665856,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.46659,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971680.4666026,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971680.4666078,"msg":"Sarama","info":"client/metadata retrying after 250ms... (3 attempts remaining)\n"}
{"level":"info","ts":1676971680.717703,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971680.7179325,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.7179465,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.7179515,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971680.717973,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971680.71798,"msg":"Sarama","info":"client/metadata retrying after 250ms... (2 attempts remaining)\n"}
{"level":"info","ts":1676971680.969042,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971680.9692502,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.969263,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971680.9692676,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971680.9692795,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971680.969284,"msg":"Sarama","info":"client/metadata retrying after 250ms... (1 attempts remaining)\n"}
{"level":"info","ts":1676971681.2198496,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971681.2200856,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971681.220098,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971681.2201023,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971681.2201138,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971681.2201173,"msg":"Sarama","info":["Closing Client"]}
{"level":"info","ts":1676971683.4680645,"msg":"Sarama","info":["Initializing new client"]}
{"level":"info","ts":1676971683.4681323,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971683.4684024,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.4684238,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.4684274,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971683.4684343,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971683.468439,"msg":"Sarama","info":"client/metadata retrying after 250ms... (3 attempts remaining)\n"}
{"level":"info","ts":1676971683.7196429,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971683.71992,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.7199457,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.7199502,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971683.7199724,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971683.719978,"msg":"Sarama","info":"client/metadata retrying after 250ms... (2 attempts remaining)\n"}
{"level":"info","ts":1676971683.970539,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971683.9707108,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.970736,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971683.970741,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971683.970752,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971683.9707556,"msg":"Sarama","info":"client/metadata retrying after 250ms... (1 attempts remaining)\n"}
{"level":"info","ts":1676971684.221747,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971684.2219987,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971684.2220113,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971684.222016,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971684.2220273,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971684.222035,"msg":"Sarama","info":["Closing Client"]}
{"level":"info","ts":1676971686.4572837,"msg":"Sarama","info":["Initializing new client"]}
{"level":"info","ts":1676971686.457362,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971686.4576688,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.4576974,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.4577017,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971686.4577086,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971686.4577134,"msg":"Sarama","info":"client/metadata retrying after 250ms... (3 attempts remaining)\n"}
{"level":"info","ts":1676971686.7081754,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971686.7084532,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.708476,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.7084808,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971686.7085226,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971686.7085283,"msg":"Sarama","info":"client/metadata retrying after 250ms... (2 attempts remaining)\n"}
{"level":"info","ts":1676971686.9593933,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971686.9595973,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.9596124,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971686.9596167,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971686.9596286,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971686.9596329,"msg":"Sarama","info":"client/metadata retrying after 250ms... (1 attempts remaining)\n"}
{"level":"info","ts":1676971687.2102273,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971687.2103784,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971687.2103932,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971687.210398,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971687.2104096,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971687.210414,"msg":"Sarama","info":["Closing Client"]}
{"level":"info","ts":1676971689.462154,"msg":"Sarama","info":["Initializing new client"]}
{"level":"info","ts":1676971689.4622679,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971689.4625766,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.4625995,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.4626074,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971689.4626155,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971689.462621,"msg":"Sarama","info":"client/metadata retrying after 250ms... (3 attempts remaining)\n"}
{"level":"info","ts":1676971689.7214363,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971689.721626,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.7216392,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.7216432,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971689.7216663,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971689.7216704,"msg":"Sarama","info":"client/metadata retrying after 250ms... (2 attempts remaining)\n"}
{"level":"info","ts":1676971689.972676,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971689.9729319,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.972949,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971689.972953,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971689.9729698,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971689.972974,"msg":"Sarama","info":"client/metadata retrying after 250ms... (1 attempts remaining)\n"}
{"level":"info","ts":1676971690.2240033,"msg":"Sarama","info":"client/metadata fetching metadata for all topics from broker 127.0.0.1:9092\n"}
{"level":"info","ts":1676971690.2242289,"msg":"Sarama","info":"Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971690.2242424,"msg":"Sarama","info":"client/metadata got error from broker -1 while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused\n"}
{"level":"info","ts":1676971690.2242475,"msg":"Sarama","info":["client/metadata no available broker to send metadata request to"]}
{"level":"info","ts":1676971690.2242591,"msg":"Sarama","info":"client/brokers resurrecting 1 dead seed brokers"}
{"level":"info","ts":1676971690.2242632,"msg":"Sarama","info":["Closing Client"]}

**Comment by la00gke** [comment]
Feb 21 09:59:43 cb5905290dc8 systemd[1]: Started Elkeid Apache Kafka server (broker).
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: #
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: # There is insufficient memory for the Java Runtime Environment to continue.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: # Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: # An error report file with more information is saved as:
Feb 21 09:59:43 cb5905290dc8 kafka-server-start.sh[52620]: # /elkeid/kafka/hs_err_pid52620.log
Feb 21 09:59:43 cb5905290dc8 systemd[1]: elkeid_kafka.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:59:43 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:43 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.
Feb 21 09:59:43 cb5905290dc8 systemd[1]: elkeid_kafka.service holdoff time over, scheduling restart.
Feb 21 09:59:43 cb5905290dc8 systemd[1]: Stopped Elkeid Apache Kafka server (broker).
Feb 21 09:59:43 cb5905290dc8 systemd[1]: Started Elkeid Apache Kafka server (broker).
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: [0.010s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: [0.010s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: [0.010s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: [0.010s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: #
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: # There is insufficient memory for the Java Runtime Environment to continue.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: # Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: # An error report file with more information is saved as:
Feb 21 09:59:44 cb5905290dc8 kafka-server-start.sh[52954]: # /elkeid/kafka/hs_err_pid52954.log
Feb 21 09:59:44 cb5905290dc8 systemd[1]: elkeid_kafka.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:59:44 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:44 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.
Feb 21 09:59:44 cb5905290dc8 systemd[1]: elkeid_kafka.service holdoff time over, scheduling restart.
Feb 21 09:59:44 cb5905290dc8 systemd[1]: Stopped Elkeid Apache Kafka server (broker).
Feb 21 09:59:44 cb5905290dc8 systemd[1]: Started Elkeid Apache Kafka server (broker).
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: [0.007s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: [0.007s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: [0.007s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: [0.007s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: #
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: # There is insufficient memory for the Java Runtime Environment to continue.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: # Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: # An error report file with more information is saved as:
Feb 21 09:59:45 cb5905290dc8 kafka-server-start.sh[53288]: # /elkeid/kafka/hs_err_pid53288.log
Feb 21 09:59:45 cb5905290dc8 systemd[1]: elkeid_kafka.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:59:45 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:45 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.
Feb 21 09:59:45 cb5905290dc8 systemd[1]: elkeid_kafka.service holdoff time over, scheduling restart.
Feb 21 09:59:45 cb5905290dc8 systemd[1]: Stopped Elkeid Apache Kafka server (broker).
Feb 21 09:59:45 cb5905290dc8 systemd[1]: Started Elkeid Apache Kafka server (broker).
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: #
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: # There is insufficient memory for the Java Runtime Environment to continue.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: # Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: # An error report file with more information is saved as:
Feb 21 09:59:46 cb5905290dc8 kafka-server-start.sh[53628]: # /elkeid/kafka/hs_err_pid53628.log
Feb 21 09:59:46 cb5905290dc8 systemd[1]: elkeid_kafka.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:59:46 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:46 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.
Feb 21 09:59:46 cb5905290dc8 systemd[1]: elkeid_kafka.service holdoff time over, scheduling restart.
Feb 21 09:59:46 cb5905290dc8 systemd[1]: Stopped Elkeid Apache Kafka server (broker).
Feb 21 09:59:46 cb5905290dc8 systemd[1]: Started Elkeid Apache Kafka server (broker).
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 2147483648, 0) failed; error='Not enough space' (errno=12)
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: #
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: # There is insufficient memory for the Java Runtime Environment to continue.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: # Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: # An error report file with more information is saved as:
Feb 21 09:59:47 cb5905290dc8 kafka-server-start.sh[53962]: # /elkeid/kafka/hs_err_pid53962.log
Feb 21 09:59:47 cb5905290dc8 systemd[1]: elkeid_kafka.service: main process exited, code=exited, status=1/FAILURE
Feb 21 09:59:47 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:47 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.
Feb 21 09:59:47 cb5905290dc8 systemd[1]: elkeid_kafka.service holdoff time over, scheduling restart.
Feb 21 09:59:47 cb5905290dc8 systemd[1]: Stopped Elkeid Apache Kafka server (broker).
Feb 21 09:59:47 cb5905290dc8 systemd[1]: start request repeated too quickly for elkeid_kafka.service
Feb 21 09:59:47 cb5905290dc8 systemd[1]: Failed to start Elkeid Apache Kafka server (broker).
Feb 21 09:59:47 cb5905290dc8 systemd[1]: Unit elkeid_kafka.service entered failed state.
Feb 21 09:59:47 cb5905290dc8 systemd[1]: elkeid_kafka.service failed.

**Comment by UgOrange** [comment]
看着是机器内存不足，单节点装全部组件至少要8G内存

**Comment by la00gke** [comment]
多谢，把内存扩大到8G，重启kafka，问题解决了。
