### ISSUE TITLE
开启 sandbox模式后，plugins/driver解析出错

### ISSUE THREAD

**Issue by thinkycx** [bytedance/Elkeid#449]
**Describe the bug**

问题： 编译lkm和 driver，非sandbox模式下 driver输出的数据一切正常。
开启sandbox模式后，重新编译lkm，driver输出的脏数据。

**To Reproduce**
https://gist.github.com/thinkycx/8facd6fdf9092e5859c21ab31c1c4c1c

**Expected behavior**
输出正常模式的sandbox日志

**Screenshots**
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/13138128/220950866-5223641a-0a2c-4994-9078-5e9223a51dd4.png">

**OS information**
- centos
- Linux xxx 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- 代码分支：最新的release版本 https://github.com/bytedance/Elkeid/releases/tag/v1.7.0.10-driver-ko-20230221_1

**Comment by EBWi11** [comment]
目前开源driver插件仅支持默认模式下的driver数据（由于schema存在差异），如果需要用driver插件进行消费解析sandbox模式下的数据，需要自行定制

**Comment by thinkycx** [comment]
本质上是write的schema（type为1）解析没有，其他的都有，直接更新一下schema应该就可以了？

**Comment by EBWi11** [comment]
应该不只，建议对照sandbox特有数据进行比对

**Comment by thinkycx** [comment]
确实，当前版本中没有的：
- schema.rs中仅确实了type为1的数据，
- plugin/driver的transformer.rs 所有sandbox模块的解析代码都没有

**Comment by thinkycx** [comment]
plusin的driver部分，是否可以考虑一下sandbox的兼容性呢？目前看这部分开发工作量不会很小，后续估计也会有人踩到类似的坑

**Comment by thinkycx** [comment]
当前解析代码缺失情况：
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body>

Hook | DataType | Note | Default | Transormer | schema
-- | -- | -- | -- | -- | --
write | 1 |   | OFF | ❌ | ❌
open | 2 |   | OFF | ❌ | ✅
mprotect | 10 | only PROT_EXEC | OFF | ❌ | ✅
nanosleep | 35 |   | OFF | ❌ | ✅
connect | 42 |   | ON | ✅ | ✅
accept | 43 |   | OFF | ❌ | ✅
bind | 49 |   | ON | ✅ | ✅
execve | 59 |   | ON | ✅ | ✅
process exit | 60 |   | OFF | ❌ | ✅
kill | 62 |   | OFF | ❌ | ✅
rename | 82 |   | ON | ✅ | ✅
link | 86 |   | ON | ✅ | ✅
ptrace | 101 | only PTRACE_POKETEXT or PTRACE_POKEDATA | ON | ✅ | ✅
setsid | 112 |   | ON | ✅ | ✅
prctl | 157 | only PR_SET_NAME | ON | ✅ | ✅
mount | 165 |   | ON | ✅ | ✅
tkill | 200 |   | OFF | ❌ | ✅
exit_group | 231 |   | OFF | ❌ | ✅
memfd_create | 356 |   | ON | ✅ | ✅
dns query | 601 |   | ON | ✅ | ✅
create_file | 602 |   | ON | ✅ | ✅
load_module | 603 |   | ON | ✅ | ✅
update_cred | 604 | only old uid ≠0 && new uid == 0 | ON | ✅ | ✅
unlink | 605 |   | OFF | ❌ | ✅
rmdir | 606 |   | OFF | ❌ | ✅
call_usermodehelper_exec | 607 |   | ON | ✅ | ✅
file_write | 608 |   | OFF | ✅ | ✅
file_read | 609 |   | OFF | ✅ | ✅
usb_device_event | 610 |   | ON | ✅ | ✅
privilege_escalation | 611 |   | ON | ✅ | ✅

</body></html>
