### ISSUE TITLE
rasp插件 产生得日志是否会自动删除

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#458]
rasp插件 产生得日志是否会自动删除

**Comment by Hackerl** [comment]
你指的是 "/tmp" 下面的日志还是 “/etc” 下面的插件日志

**Comment by anquanscan** [comment]
@Hackerl  /etc/elkeid/plugin/rasp   这个位置的日志

**Comment by Hackerl** [comment]
插件日志都是 rotate 的

**Comment by AlkenePan** [comment]
设定最多日志数：https://github.com/bytedance/Elkeid/blob/main/rasp/plugin/settings.toml#L73

日志初始化：
https://github.com/bytedance/Elkeid/blob/main/rasp/plugin/src/main.rs#L59

Elkeid rust 插件使用的日志库中的 rotate：

https://github.com/bytedance/Elkeid/blob/main/plugins/lib/rust/src/logger.rs#L109
