### ISSUE TITLE
scanner版本不统一问题

### ISSUE THREAD

**Issue by o0x1024** [bytedance/Elkeid#459]
官方包安装好后，scanner版本是【3.1.9.6】但是git仓库release发版的是【v2.2.0.0】，如果可以的话这块能否统一一下版本，或者说版本这一块不造成影响？
![image](https://user-images.githubusercontent.com/53891640/222624520-46243fd0-2a33-4fa9-83ca-d60fa24d6ac5.png)
![image](https://user-images.githubusercontent.com/53891640/222624685-6e2eea65-08d1-45e8-9b3c-f15ee2ac7f5c.png)

**Comment by kulukami** [comment]
reply to @o0x1024 
----
1.目前没有功能性影响
2.用户视角确实看起来会困惑

TODO:

* [ ] 下个版本统一
