### ISSUE TITLE
升级1.9.1.3以后，前端使用异常

### ISSUE THREAD

**Issue by xufengnian** [bytedance/Elkeid#460]
使用1.9.1.3的package包升级Manager以后，我的升级顺序为
HUB
HUB_Leader
Manager

升级后经常出现以下问题
登录超时
![image](https://user-images.githubusercontent.com/15324125/222626611-70fae49c-1c04-4ecb-a85c-58edd2b820de.png)
agent离线
![image](https://user-images.githubusercontent.com/15324125/222626634-3f39c099-3174-4752-9886-1e7fc3035c82.png)
页面加载失败
![image](https://user-images.githubusercontent.com/15324125/222626449-7c4cf57d-1044-4555-82bc-592c146639bc.png)
同时提示redis异常
![image](https://user-images.githubusercontent.com/15324125/222626761-328ac019-f104-4563-a798-2177b59adaaa.png)
![image](https://user-images.githubusercontent.com/15324125/222626930-3da5fe75-f62d-4380-b895-a0f18ea705ee.png)

推测redis出现了问题，请问如何处理？

**Comment by hugebomb** [comment]
可以到redis机器上，查看下redis服务日志和使用redis-cli验证下redis服务有没有问题

**Comment by xufengnian** [comment]
第二天服务器未出现该问题，非常感谢
