### ISSUE TITLE
通知管理企业微信通知功能不可用

### ISSUE THREAD

**Issue by anquanscan** [bytedance/Elkeid#462]
![image](https://user-images.githubusercontent.com/5724472/223303440-53608130-31f0-41dd-9974-dac4be7857e2.png)

我是创建了企业微信机器人

**Comment by UgOrange** [comment]
麻烦确认下是最新的1.9.1.3版本吗？该版本修复了测试功能不可用的问题

**Comment by anquanscan** [comment]
@UgOrange 是 v1.9.1，在哪里看小版本号呀

**Comment by UgOrange** [comment]
[1.9.1.3](https://github.com/bytedance/Elkeid/releases/tag/v1.9.1.3)是上周更新的，麻烦更新下即可解决

**Comment by anquanscan** [comment]
@UgOrange 如果我从1.9.1 升级到1.9.1.3  ，按照   https://elkeid.bytedance.com/Chinese/ElkeidUp/update.html 这个升级步骤能否行得通？目前主要是想解决告警通知的问题。

**Comment by hugebomb** [comment]
稍等下，我们会尽快更新1.9.1 到1.9.1.3的升级文档~

**Comment by anquanscan** [comment]
@hugebomb 收到

**Comment by UgOrange** [comment]
此问题已经修复，标记为已解决，如有问题欢迎重新提问。
