### ISSUE TITLE
docker部署模式1.9.1版本升级1.9.1.3

### ISSUE THREAD

**Issue by h253518892** [bytedance/Elkeid#464]
没有看到关于docker部署升级的相关文档，我现在是docker部署，1.9.1版本，如何升级到1.9.1.3

**Comment by TaeRoen** [comment]
docker 环境部署是一个集成测试环境，没有提供单独的升级方式。
如果要升级的话，升级操作于本机部署情况相同，只是需要提前用docker cp命令把对应的package文件拷贝到容器内，然后在容器内同样执行reinstall命令即可。
我们晚点给下验证过后的操作。

**Comment by TaeRoen** [comment]
下载并解压package包，cd 到 package 解压后的目录。具体是cd到package里，ls后会看见每个组件的文件夹。

根据要升级组件的不同，执行以下命令。
HUB:
docker cp hub elkeid_community:/root/.elkeidup/package
docker exec -it elkeid_community /root/.elkeidup/elkeidup reinstall --component Hub
HubLeader:
docker cp hub_leader elkeid_community:/root/.elkeidup/package
docker exec -it elkeid_community /root/.elkeidup/elkeidup reinstall --component HubLeader
Manager:
docker cp manager elkeid_community:/root/.elkeidup/package
docker exec -it elkeid_community /root/.elkeidup/elkeidup reinstall --component Manager
