### ISSUE TITLE
使用docker部署 V1.9.1.3出现问题，页面能正常访问，agent安装脚本不能下载

### ISSUE THREAD

**Issue by nohunt** [bytedance/Elkeid#466]
![deploy_1 9 1 3_docker_err_01](https://user-images.githubusercontent.com/19381274/223638169-f71f1526-b833-4ec3-bb84-1ea5f6079951.png)
![deploy_1 9 1 3_docker_err_02](https://user-images.githubusercontent.com/19381274/223638183-a5ee3fd1-8fba-489b-942f-e5c471bb5ed0.png)

按安装脚本安装 agent 如下 ：
bash -c "if (command -v curl); then (curl -sS http://192.168.220.177:8080/agent/install.sh | bash);else (wget -q -O - http://192.168.220.177:8080/agent/install.sh | bash); fi"

失败，发现直接访问http://192.168.220.177:8080/agent/install.sh 。报500错误

**Comment by TaeRoen** [comment]
很抱歉容器版本在更新rasp plugin版本时引入了问题。

可以按一下步骤操作。
首先删除容器重新执行 docker run 创建容器。
然后在执行 elkeid public {ip} 命令后在容器内执行下
cp /root/.elkeidup/package/agent/v1.9.1/rasp/rasp-default-x86_64-2.1.0.2.tar.gz /root/.elkeidup/package/agent/v1.9.1/rasp/rasp-default-x86_64-1.9.1.44.tar.gz

后续在继续执行 init，build ，应该是可以正常工作的。

**Comment by nohunt** [comment]
问题能正常解决！不过在agent运行过程中，又碰到到新的问题，过会我在发个issues

**Comment by UgOrange** [comment]
如有问题欢迎再次提问，这个先关掉了
