### ISSUE TITLE
agent无法正常安装

### ISSUE THREAD

**Issue by vana1s** [bytedance/Elkeid#468]
查看日志报错，我将8080端口修改为9680端口了。然后install.sh是浏览器下载后传到机器上手动执行安装的。 
![image](https://user-images.githubusercontent.com/104341632/224603421-42b25f65-aaca-4b52-9501-61fcd19f2191.png)

**Comment by EBWi11** [comment]
是否可以访问server的6751端口

**Comment by TaeRoen** [comment]
@vana1s 
agent 只会连接执行 elkeidup agent public {ip} 这个命令里的ip地址的8080 和 8090 端口。这两个端口号是写在agent的二进制里的，只修改服务端是不生效的。
“我将8080端口修改为9680端口”，请问下这个指什么，为什么要更改？

**Comment by vana1s** [comment]
> @vana1s agent 只会连接执行 elkeidup agent public {ip} 这个命令里的ip地址的8080 和 8090 端口。这两个端口号是写在agent的二进制里的，只修改服务端是不生效的。 “我将8080端口修改为9680端口”，请问下这个指什么，为什么要更改？

修改为9680的原因是我机器上还有个tomcat。看起来目前的最佳解是我还使用原来的端口，然后把我其他的端口修改了是吧
