### ISSUE TITLE
按照步骤安装elkeid的时候，无法安装redis

### ISSUE THREAD

**Issue by wavemomo** [bytedance/Elkeid#471]
**Describe the bug**
按照步骤安装elkeid的时候，无法安装redis
**To Reproduce**
按照完整步骤安装elkeid

**Screenshots**
![image](https://user-images.githubusercontent.com/86948535/225561691-16698f99-9277-4aa7-bd08-a4b904450667.png)

**OS information (please complete the following information):**
 - Distribution: Rocky
 - Version 8.7
 - Kernel info 4.18.0-425.13.1.el8_7.x86_64

**Comment by UgOrange** [comment]
先通过``systemctl status elkeid_redis`` 查看服务是否正常运行。如果不正常麻烦通过``journalctl -u elkeid_redis``来查看有无错误相关信息

**Comment by wavemomo** [comment]
> 先通过`systemctl status elkeid_redis` 查看服务是否正常运行。如果不正常麻烦通过`journalctl -u elkeid_redis`来查看有无错误相关信息
1. `systemctl status elkeid_redis` 查看服务不正常：
![image](https://user-images.githubusercontent.com/86948535/225835646-278a9beb-fdc6-471f-b1bc-81014e819b90.png)

2. `journalctl -u elkeid_redis`查看相关信息：
![image](https://user-images.githubusercontent.com/86948535/225835785-efa642b6-2021-488f-9442-6be25472c21e.png)

发现redis无法正常启动

**Comment by UgOrange** [comment]
status为chdir说明无法chdir到 ``/elkeid/redis``目录，这可能是目录不存在或者权限有问题。
请确认下安装提示错误的时候是否卸载已安装组件，如果没有麻烦检查下目录``/elkeid/redis``是否存在以及检查服务进程是否具有访问工作目录的权限

**Comment by TaeRoen** [comment]
长时间无新评论，暂时关闭这个issue了。

以下是redis 服务报 status=200/CHDIR 问题原因及解决方案：
redis的server文件中的以下部分，依赖了systemd 提供的 Sandboxing 特性来增强安全性，
PrivateTmp=yes
PrivateDevices=yes
ProtectHome=yes
CapabilityBoundingSet=~CAP_SYS_PTRACE
ProtectSystem=true
但是systemd的该特性对文件系统等系统组件有要求，导致systemd在启动server并开启相关特性时报错，redis启动失败。
可以通过删除 /etc/systemd/system/elkeid_redis.service 文件中的上述部分，然后执行 systemctl daemon-reload && systemctl restart elkeid_redis 来进行验证，如果redis能正常启动，就是此部分的问题。
后续可以在删除或注释 /root/.elkeidup/package/redis/redis.service中的上述部分后，重新执行elkeidup deploy命令进行安装。
