### ISSUE TITLE
磁盘信息和网卡信息数据没法手动触发获取

### ISSUE THREAD

**Issue by wavemomo** [bytedance/Elkeid#472]
在前端页面上，磁盘信息和网卡信息数据没法手动触发获取：
![image](https://user-images.githubusercontent.com/86948535/226240646-587dd7cf-a5e0-4ff1-9c06-0495b1813e44.png)

还有就是，资产指纹信息、磁盘信息以及网卡信息的数据更新频率是多久呢

**Comment by EBWi11** [comment]
目前这部分资产不支持手动更新，其他的应该均可。该部分更新频率为6小时，https://github.com/bytedance/Elkeid/blob/main/plugins/collector/main.go#L46
