### ISSUE TITLE
Kafka 负载高是什么原因？

### ISSUE THREAD

**Issue by aiwennba** [bytedance/Elkeid#476]
内存使用偏高
![image](https://user-images.githubusercontent.com/8187904/228405229-83529323-112a-4f91-a699-1572e4ed553b.png)
按照配置手册来安装部署的，8C16G 系统资源还不够吗？
![image](https://user-images.githubusercontent.com/8187904/228405429-9ffc6a66-1626-4769-b37d-b7c7f3ba5a70.png)
这个是HUB 消费不过来？
![image](https://user-images.githubusercontent.com/8187904/228405522-7bbbe2c3-82cf-4eb4-810f-9577ebf8c33b.png)

**Comment by UgOrange** [comment]
麻烦提供一下目前部署的agent数量以及后端的具体配置，如果所有组件都部署在单台的话，8C16G是最低配置，可以用于10台左右的agent用于最小化测试。
此处的服务告警为kafka的lag大于1000则报警，如果数据量较大，超过该值可能是正常现象，可以自行在``/elkeid/prometheus/prometheus_alert_kafka.yml``中进行配置.

**Comment by aiwennba** [comment]
> 如果数据量较大，超过该值可能是正常现象，可以

agent 数量在100个左右，那kafka的内存是不是需要加一点内存上去才行？

**Comment by UgOrange** [comment]
目前40%多，如果是单台安装了多个组件的话，是符合预期的，每个服务都是通过cgroup进行了一定的内存限制的

**Comment by aiwennba** [comment]
> 

目前是集群的方式部署的，按照配置手册的方式配置资源。感觉kafka有点太消耗内存资源了，还是配置哪里需要优化的？

**Comment by UgOrange** [comment]
可以修改``/etc/systemd/system/elkeid_kafka.service``中``KAFKA_HEAP_OPTS``的``-Xms``值，这边分配了4G，所以导致有一定的内存负载，如果数据量不高可以适当修改。

**Comment by UgOrange** [comment]
感谢您的反馈，我们将关闭此问题。如有其他疑问或需要进一步帮助，请再提issue。
