### ISSUE TITLE
rasp告警不上报

### ISSUE THREAD

**Issue by wylovejzj** [bytedance/Elkeid#477]
**rasp告警不上报**
配置rasp配置后，执行符合配置的操作，没有上报告警

**复现过程**
步骤:
1. 创建rasp配置，如下：
![image](https://user-images.githubusercontent.com/20904698/228749019-2a27473f-33cc-447a-963c-14a426fc9a9f.png)
2. 调用接口，接口逻辑会执行 ls -al 命令，如下：
代码逻辑：
![image](https://user-images.githubusercontent.com/20904698/228749493-2346da66-ed12-4c3b-85fe-7c949c69366d.png)

调用接口执行：
![image](https://user-images.githubusercontent.com/20904698/228749413-1528b998-86b0-4e60-adb6-32e557979303.png)
阻断结果：
![image](https://user-images.githubusercontent.com/20904698/228749523-d47636c0-4153-43f0-b61d-7534fc41629d.png)

可以看到，rasp已经阻断命令执行，但是在 Elkeid的界面上没有看到告警
![image](https://user-images.githubusercontent.com/20904698/228749686-b0350c3b-b757-4b61-a838-bdf18b8dd9d1.png)

**Comment by AlkenePan** [comment]
可以根据上报数据中:

```
{
...
"blocked": true,
...
}
```

编写规则产生告警。

**Comment by wylovejzj** [comment]
你好，这个具体是在哪里编写规则啊？

**Comment by AlkenePan** [comment]
> 你好，这个具体是在哪里编写规则啊？
在Readme架构图片的最右面有一个名为 `Elkeid-HUB` 的组建，此组建将会对端上各上报数据进行计算（包括规则匹配）。进而可以产生告警。

关于 `Elkeid-HUb`： https://elkeid.bytedance.com/Chinese/hub/handbook/handbook.html
