### ISSUE TITLE
baseline 官方配置中 file_permission 命令总是返回错误

### ISSUE THREAD

**Issue by nntp4** [bytedance/Elkeid#478]
**Describe the bug**
baseline 插件官方配置中 file_permission 命令总是返回`FilePermission param length need at least 2`错误
**To Reproduce**
1. add baseline plugin to Elkeid
2.  submit baseline task 
```json
{
    "baseline_id": 1200,
    "check_id_list":[16,17]
}
```
**Expected behavior**
更正 FilePermission 函数逻辑错误，使其与官方配置中的 file_permission 命令保持一致, 使用官方配置时不产生`FilePermission param length need at least 2`错误

https://github.com/bytedance/Elkeid/blob/854b57f4129f378d6904140f9a3825fca4c38bbd/plugins/baseline/src/check/rules.go#L133-L139

**Screenshots**
baseline.log
![image](https://user-images.githubusercontent.com/90622470/229029302-4abd41cf-64b8-4c71-a3fe-773325e6f4b6.png)

example configuration file
https://github.com/bytedance/Elkeid/blob/854b57f4129f378d6904140f9a3825fca4c38bbd/plugins/baseline/config/linux/1200.yaml#L296-L346

function called
https://github.com/bytedance/Elkeid/blob/854b57f4129f378d6904140f9a3825fca4c38bbd/plugins/baseline/src/check/rules.go#L133-L159
**OS**
Centos 7

**Comment by askyLYZ** [comment]
非常感谢问题反馈，具体问题已经定位到。是因为插件和配置没有更新到同一个版本导致的，已经对分支进行了更新，对应的commit为：https://github.com/bytedance/Elkeid/commit/ea4ec479d865295dd7cebe46bd79c1c232ddbb71
修复方法如下：将修改的3个配置文件替换到基线插件的配置目录下即可
