### ISSUE TITLE
Console控制台中能看到主机上线状态和基线扫描结果，但无法触发显示任何告警。

### ISSUE THREAD

**Issue by XNW0W** [bytedance/Elkeid#479]
Elkeid服务端已部署完成，具体配置参数如下图：
![a289225f-d293-45a3-b6f7-7239ed945cbd](https://user-images.githubusercontent.com/60835114/229045544-9cc779ba-2281-4d54-81ae-4b211a26887c.jpeg)
Console控制台中能看到主机上线状态和基线扫描结果，但无法触发显示任何告警。
![image](https://user-images.githubusercontent.com/60835114/229047238-04c70601-d207-4fa2-8b0f-ed3d35be1e45.png)
![image](https://user-images.githubusercontent.com/60835114/229047373-18f70a49-746a-4f12-b8d1-082f5d3ed1f7.png)

Agent端操作系统版本centos 7.9（3.10.0-1160.el7.x86_64）
通过console控制台返回的安装命令安装的agent客户端
![image](https://user-images.githubusercontent.com/60835114/229046400-8bdb9517-3c87-498b-937d-dc0054d199af.png)
安装agent并启动后，执行lsmod | grep hids未返回hids drives进程
![image](https://user-images.githubusercontent.com/60835114/229046949-29215a97-9821-42e2-b853-a1d984f29e13.png)
以下为/etc/elkeid/plugin/driver/driver.log日志内容
![e90d5d0c-10db-4ac8-ad74-00fd2dab6344](https://user-images.githubusercontent.com/60835114/229046919-9983228b-4246-4394-aa02-1278a6cc4b26.jpeg)
于是通过导入（服务端已导入），agent端加载（insmod）预编译KO文件的方式，再次尝试，报错insmod: ERROR: could not insert module hids_driver_1.7.0.4_3.10.0-1160.el7.x86_64.ko: Invalid module format
![image](https://user-images.githubusercontent.com/60835114/229047928-34e16b6f-b4a6-4f27-8c3e-4d78ff3e83d7.png)

**Comment by TaeRoen** [comment]
@XNW0W 先确认下部署的是哪个版本？ 是按照文档‘单机docker快速部署’里面下载的，还是在github release中选择的最新的版本，v1.9.1.3 ？

**Comment by XNW0W** [comment]
@TaeRoen Elkeid 完整部署-单机docker快速部署 Community Edition v1.9.1

**Comment by TaeRoen** [comment]
@XNW0W 
这个版本的ko版本号是 1.7.0.9 而不是 1.7.0.10。可以把 ko 所在目录的 1.7.0.10 的ko和sign文件重命名成对应的 1.7.0.9。

之后忽略insmod的部分，手动insmod 和 driver plugin 从nginx下载ko的逻辑有冲突。

重命名后重启两遍elkeid-agent，然后lsmod | grep hids 看下，能否加载ko。

**Comment by XNW0W** [comment]
@TaeRoen 这是服务端ko和sign文件重命名后的截图
![image](https://user-images.githubusercontent.com/60835114/229058411-75594171-505e-41b1-8eda-b3c4a1ec46fc.png)
这是Agent端操作系统重启agent后的截图，还是未加载ko
![image](https://user-images.githubusercontent.com/60835114/229058663-eb0ad4db-8f10-4cbe-b0e5-06f5c0297430.png)

**Comment by TaeRoen** [comment]
@XNW0W 帮忙 看下 /etc/elkeid/plugin/driver.log 的内容。
以及 nginx的access log。 在容器里的 /elkeid/nginx/nginx/logs 目录下的log，看下实际下载的路径。

**Comment by XNW0W** [comment]
@TaeRoen 问题原因找到了，是因为官方指导文档中的命令存在错误导致下载后的ko文件有问题
curl -O "http://lf26-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.7.0.10_$(uname -r).ko
ko文件中是一段error报错内容
![image](https://user-images.githubusercontent.com/60835114/229063264-1e369e73-9046-474b-b45d-d9183c713490.png)

**Comment by XNW0W** [comment]
@TaeRoen 可以了，能够检测到告警了。并且解决了我的另一个”关于自行编译KO文件无法启动hids_drives“的问题，建议在docker完全部署文档中标注下，dokcer部署需要把 ko 所在目录的 1.7.0.10 的ko和sign文件重命名成的1.7.0.9

**Comment by TaeRoen** [comment]
@XNW0W 好的，感谢，文档已更新，后续文档均以github为准，我们会优先更新github的文档
