### ISSUE TITLE
补充一个实现system守护进程防止agent停止服务的办法

### ISSUE THREAD

**Issue by shen771** [bytedance/Elkeid#48]
================
为了防止hids的agent进程因为网络或server端重启而停止服务，agent批量重启也很麻烦，故需要额外添加守护进程。同时出于运维考虑需要对agent进程的内存和cpu使用量进行限制，虽然实测agent使用系统资源很少很稳定，但是还是要设置阈值防一手。
================
# cd /etc/elkeid/                 //进入elkeid目录
# ls
agent-id elkeid-agent log nohup.out plugin.sock
# vi elkeid-agentd.service                       //新建service配置文件，内容如下，另外注意service文件权限给x
#chmod 777 elkeid-agentd.service
# cat elkeid-agentd.service

# /etc/elkeid/elkeid-agentd.service
[Unit]
Description=elkeid-agent

[Service]
WorkingDirectory=/etc/elkeid/
ExecStart=/etc/elkeid/elkeid-agent &
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
Restart=always
CPUAccounting=true
systemctl set-property elkeid-agentd CPUShares=500
MemoryAccounting=true
MemoryLimit=200M

[Install]
WantedBy=default.target

# ln -s /etc/elkeid/elkeid-agent /usr/local/bin/elkeid-agent                      //创建启动脚本快捷方式链接

# ln -s /etc/elkeid/elkeid-agentd.service /usr/lib/systemd/system/elkeid-agentd.service            //创建启动脚本service文件的快捷方式链接， 放systemd目录下意思是会开机自启的脚本
# ll /usr/lib/systemd/system/ | grep elkeid-agentd.service                      //查看快捷方式链接是否生效
lrwxrwxrwx 1 root root 33 Apr 27 18:27 elkeid-agentd.service -> /etc/elkeid/elkeid-agentd.service

root@st-arch-sec-tool-1 (14:33:21) elkeid # systemctl daemon-reload                                   //重新装载systemctl守护进程配置
root@st-arch-sec-scan-1 (18:28:01) elkeid # systemctl cat elkeid-agentd.service                   //查看system守护进程是否添加生效

# /etc/elkeid/elkeid-agentd.service
[Unit]
Description=elkeid-agent

[Service]
WorkingDirectory=/etc/elkeid/
ExecStart=/etc/elkeid/elkeid-agent &
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
Restart=always
CPUAccounting=true
systemctl set-property elkeid-agentd CPUShares=500
MemoryAccounting=true
MemoryLimit=200M

[Install]
WantedBy=default.target

# systemctl start elkeid-agentd.service                //使用守护进程启动agent    start/stop/status   也可以-l参数展示报错
# ps -ef | grep elkeid                                            //看到有driver和collector插件一起启动（example中未使用Journal Wacher插件）

root 451 1 3 14:33 ? 00:00:00 /etc/elkeid/elkeid-agent &
root 463 451 0 14:33 ? 00:00:00 /etc/elkeid/plugin/driver/driver
root 468 451 0 14:33 ? 00:00:00 /etc/elkeid/plugin/collector/collector
root 480 29690 0 14:33 pts/0 00:00:00 grep --color=auto elkeid

# cat /etc/elkeid/log/elkeid-agent.log               //查看elkeid-agent的自身日志，验证结束进程后会自动启动，说明守护进程生效
===================================

**Comment by ZhangLei-cn** [comment]
because of invalid issue format, this issue will be closed.
Maybe submit a new pr?
