### ISSUE TITLE
NodeExporter installed faield: process exporter check failed

### ISSUE THREAD

**Issue by Reconss** [bytedance/Elkeid#482]
![WX20230401-183840@2x](https://user-images.githubusercontent.com/55997634/229282388-639ec5af-2188-4bc1-a030-666fd27e4829.png)
![WX20230401-184125@2x](https://user-images.githubusercontent.com/55997634/229282860-28798319-decc-460d-b5f5-aa5f88d06da6.png)

**Comment by fanjiarong2343** [comment]
怎么解决的呀

**Comment by fanjiarong2343** [comment]
急急急
