### ISSUE TITLE
agent安装时报错

### ISSUE THREAD

**Issue by o0x1024** [bytedance/Elkeid#483]
环境信息如下：
```
OS：CentOS Linux release 7.1.1503 (Core)
kernel:  3.10.0-229.el7.x86_64 
```

报错信息如下
```
[root@test ~]# rpm -ivh elkeid-agent-rhel-x86_64-1.7.0.24.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:elkeid-agent-3:1.7.0.24-1        ################################# [100%]
2023-04-03 16:12:55.634 [INFO]  enable agent's service
Failed to issue method call: Unit /etc/elkeid/elkeid-agent.service does not exist.
Error: exit status 1
2023-04-03 16:12:55.647 [ERRO]  when exec /etc/elkeid/elkeidctl enable, an unexpected error occurred, code: 1
warning: %post(elkeid-agent-3:1.7.0.24-1.x86_64) scriptlet failed, exit status 1
```

**Comment by TaeRoen** [comment]
先确认一下，在其他机器上安装的rpm包，和这个rpm包是同一个吧，sha256也想通吧。

可能是系统镜像版本有些早，我新建个centos 7.1.1503 的机器试试。

**Comment by o0x1024** [comment]
rpm包是一样的，是直接复制的后台命令安装的，这个是命令下载的包。

**Comment by TaeRoen** [comment]
确认是 agent 安装包的兼容性问题，和systemd版本有关
在 centos 7.1 systemd 208 这个版本下 执行 systemctl enable /etc/elkeid/elkeid-agent.service 这个命令会报错，报错就是 Failed to issue method call: Unit /etc/elkeid/elkeid-agent.service does not exist.。
作为对比 在 systemd 219 的环境中，这个命令可以正常执行，结果如下
Created symlink from /etc/systemd/system/multi-user.target.wants/elkeid-agent.service to /etc/elkeid/elkeid-agent.service.
Created symlink from /etc/systemd/system/elkeid-agent.service to /etc/elkeid/elkeid-agent.service.

暂时不能直接改 enable service 这个逻辑，改成 cp service 文件到 /etc/systemd/system 可能会和rpm update操作有冲突，我先测一下再给下方案。

**Comment by o0x1024** [comment]
好的，感谢

**Comment by TaeRoen** [comment]
经过验证，目前必须重新编译agent才能在 systemd <= 208 的环境中安装agent。
当前版本安装中执行的 systemctl enable /etc/elkeid/elkeid-agent.service  一定会报错，暂时无法绕过。

具体原因：
systemd 在209版本中修改了语法定义，将 systemctl {subcmd} name中的name部分修改为 _should be the full name of the
unit file, or the absolute path to the unit file_ 。<= 208 版本中 name 必须为Service名字，不能是绝对路径。所以enble命令执行失败。change log具体见这一行，208及以前版本是没有这一部分的。
https://github.com/systemd/systemd/blob/v209/man/systemctl.xml#L1453

解决方案:
我们在两周内会再次更新一个社区版的小版本，同步修复这个问题。如有需要，可以使用相同的证书和配置重新编译一次agent，在，使用新的rpm包进行安装。
