### ISSUE TITLE
v1.7.3升级v1.9.1.3问题

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#485]
**1、文档内容有误**
三个目录和三个文件？
![image](https://user-images.githubusercontent.com/44428568/229860340-ecf58df6-1cd4-4943-b8df-c7a2b9cb088e.png)

**2、v1.9.1.3 /elkeid/agent_center/conf证书与v1.7.3一致，但依旧提示证书问题**
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/44428568/229861284-c2f80f90-2cee-43ad-89ee-4368a7b7f1ad.png">

```
# v1.9.1.3 服务器
root@ip-10-20-4-221:/elkeid/agent_center/conf# md5sum *
b1b5d871d91e988d880d6d588a205925  ca.crt
aeded5414e96cbd0e4cc2aa581cb7661  ca.key
a0f334cbb6e4f8fce0843c60ec37da30  client.crt
ca5d6957f21c3042a36680154abb7eb8  client.key
72cd66fa86d0e8e366fb02a8e24163b7  rd_server.crt
967ba4702d4785e6f9491ab43916ae86  rd_server.key
d4888f43aaf425fb8f6a38a4391e9cbf  server.crt
e420ea0e5f6e0a1746855777ffab6c64  server.key
```

```
# v1.7.3 服务器
root@ip-10-20-4-248:/elkeid/agent_center/conf# md5sum *
b1b5d871d91e988d880d6d588a205925  ca.crt
aeded5414e96cbd0e4cc2aa581cb7661  ca.key
a0f334cbb6e4f8fce0843c60ec37da30  client.crt
ca5d6957f21c3042a36680154abb7eb8  client.key
d4888f43aaf425fb8f6a38a4391e9cbf  server.crt
e420ea0e5f6e0a1746855777ffab6c64  server.key
836c9927094cac78ee12a14f45d5b3d5  svr.yml
```

**Comment by bigbrobro** [comment]
升级方式：新建一台主机，部署v1.9.1.3版本，保持与v1.7.3通讯证书一致，agent主机通过绑定hosts指定通讯域名指向v1.9.1.3主机

**Comment by TaeRoen** [comment]
按理说没有新生成证书这一步，只存在 171 旧版本的证书，不应该出现x509相关错误。

先确认下 191 版本的cert目录是在执行deploy前就从171目录拷贝来的吗？还是后续覆盖的？编译agent时如果用的不是 171 的老证书，后续再替换是没有用的。

可以用以下方式确认cert文件是否真实一致。
1. 重启 191 版本的ac，确保ac使用的是 /elkeid/agent_center/conf 目录下的cert。
2. 用二进制编辑工具打开 /etc/elkeid/elkeid-agent 文件，搜索 `BEGIN CERTIFICATE` 和  `BEGIN RSA PRIVATE KEY`关键字，能搜到三段，分别对应 ca.crt，client.key，client.crt，这三个文件，可以对照下和ac使用的是 /elkeid/agent_center/conf 目录下的这三个文件是否一致。

**Comment by TaeRoen** [comment]
暂时关闭，还有问题麻烦再打开issue。
