### ISSUE TITLE
hub 测试插件问题，按照例子在真实环境中无法检出什么问题？

### ISSUE THREAD

**Issue by aiwennba** [bytedance/Elkeid#487]
**问题描述**
按照例子 https://elkeid.bytedance.com/Chinese/hub/quick_start/quick_start.html
 配置规则 和项目，然后测试可以正常看到检测数据，然后在机器上执行nmap 无法检测出来
1， nmap测试样例 -配置规则：

![image](https://user-images.githubusercontent.com/8187904/231951241-42b09d8a-df5d-406b-9489-494969389400.png)
![image](https://user-images.githubusercontent.com/8187904/231951318-ecbae793-fe76-4799-8d59-fe01ad8fcf43.png)

2， nmap测试样例 -配置项目：
![image](https://user-images.githubusercontent.com/8187904/231951428-b5871ee0-9f61-4b63-af73-36747bd27f58.png)
![image](https://user-images.githubusercontent.com/8187904/231951451-834abdd1-5e32-4092-8dd1-c9dd0c9d1c9f.png)
项目状态
![image](https://user-images.githubusercontent.com/8187904/231951505-5df652f7-13aa-4406-b3ae-437a6f5f50a5.png)

3， nmap测试样例 -测试数据：
![image](https://user-images.githubusercontent.com/8187904/231951666-965849ac-878a-40f5-b0bf-13cac52fc796.png)

{
    "data_type":"59",
    "exe":"/usr/bin/nmap",
    "uid":"0"
}
4， nmap测试样例 -console 告警：
      
![image](https://user-images.githubusercontent.com/8187904/231951854-8d7ed994-9cd6-44f5-be74-ce2989b93551.png)
![image](https://user-images.githubusercontent.com/8187904/231952365-bafd9fbb-a300-456d-9664-1e54d05dd62c.png)

问题：
 然后在一台agent 机器上安装好了nmap 后执行 nmap -v -sn 192.168.1.0/24 命令后，console 上没有告警出现是规则配置上面有问题，还是哪里有问题？

**Comment by chiselX** [comment]
机器上的driver 插件是正常运行的吗 lsmod | grep hids 看下呢

**Comment by chiselX** [comment]
> **问题描述** 按照例子 https://elkeid.bytedance.com/Chinese/hub/quick_start/quick_start.html 配置规则 和项目，然后测试可以正常看到检测数据，然后在机器上执行nmap 无法检测出来 1， nmap测试样例 -配置规则：
> 
> ![image](https://user-images.githubusercontent.com/8187904/231951241-42b09d8a-df5d-406b-9489-494969389400.png) ![image](https://user-images.githubusercontent.com/8187904/231951318-ecbae793-fe76-4799-8d59-fe01ad8fcf43.png)
> 
> 2， nmap测试样例 -配置项目： ![image](https://user-images.githubusercontent.com/8187904/231951428-b5871ee0-9f61-4b63-af73-36747bd27f58.png) ![image](https://user-images.githubusercontent.com/8187904/231951451-834abdd1-5e32-4092-8dd1-c9dd0c9d1c9f.png) 项目状态 ![image](https://user-images.githubusercontent.com/8187904/231951505-5df652f7-13aa-4406-b3ae-437a6f5f50a5.png)
> 
> 3， nmap测试样例 -测试数据： ![image](https://user-images.githubusercontent.com/8187904/231951666-965849ac-878a-40f5-b0bf-13cac52fc796.png)
> 
> { "data_type":"59", "exe":"/usr/bin/nmap", "uid":"0" } 4， nmap测试样例 -console 告警：
> 
> ![image](https://user-images.githubusercontent.com/8187904/231951854-8d7ed994-9cd6-44f5-be74-ce2989b93551.png) ![image](https://user-images.githubusercontent.com/8187904/231952365-bafd9fbb-a300-456d-9664-1e54d05dd62c.png)
> 
> 问题： 然后在一台agent 机器上安装好了nmap 后执行 nmap -v -sn 192.168.1.0/24 命令后，console 上没有告警出现是规则配置上面有问题，还是哪里有问题？
机器上的driver 插件是正常运行的吗 lsmod | grep hids 看下呢

**Comment by aiwennba** [comment]
> 机器上的driver 插件是正常运行的吗 lsmod | grep hids 看下呢

![image](https://user-images.githubusercontent.com/8187904/231970042-9069149c-64a2-4774-9a67-e5e6d8e25ca9.png)
正常运行的

**Comment by EBWi11** [comment]
请问测试服务器的 nmap 是真实执行成功了吗？可以看下 strace nmap -v -sn 192.168.1.0/24 和 which nmap 的结果不

**Comment by EBWi11** [comment]
同时建议配置一个output到自己的es，然后先通过es查看数据是否采集正常（driver->agent->ac->kafka->hub），如果有这个nmap的59原始数据，再看下是否是hub问题或者推送问题

**Comment by UgOrange** [comment]
除此之外，内置的钉钉插件不能直接在hub这里调用，建议先生成符合规则的告警后在console中配置推送。
可以参考[快速上手指南](https://elkeid.bytedance.com/Chinese/hub/quick_start/quick_start.html)中的方式进行编写。

**Comment by EBWi11** [comment]
看起来是正常执行了 execve 的：execve("/usr/bin/nmap"，理论上driver插件应该能采集到，怀疑可能是链路存在问题，console前端显示该服务器agent正常在线是吗？

**Comment by aiwennba** [comment]
> 同时建议配置一个output到自己的es，然后先通过es查看数据是否采集正常（driver->agent->ac->kafka->hub），如果有这个nmap的59原始数据，再看下是否是hub问题或者推送问题

好的，我在部署一个es 推送数据看看

**Comment by aiwennba** [comment]
> 看起来是正常执行了 execve 的：execve("/usr/bin/nmap"，理论上driver插件应该能采集到，怀疑可能是链路存在问题，console前端显示该服务器agent正常在线是吗？

都是正常的，agent 都是正常在线

**Comment by aiwennba** [comment]
> > 同时建议配置一个output到自己的es，然后先通过es查看数据是否采集正常（driver->agent->ac->kafka->hub），如果有这个nmap的59原始数据，再看下是否是hub问题或者推送问题
> 
> 好的，我在部署一个es 推送数据看看

我部署了ES环境推送数据一比一环境还是没有检测出来数据，ES也没有数据推过来agent 都是在线的，nmap&sqlmap 样例都不行，不知道什么原因了？

**Comment by hugebomb** [comment]
似乎是数据链路有问题，建议先在HUB前端 **日志/转态 --> HUB状态**  上看下有没有相关的错误日志。

**Comment by chiselX** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/8187904/240517275-0bee8b3f-6932-4d14-8de5-d4ca64e7b996.png) 没有看见有错误日志输出

尝试整体重启一下HUB服务呢

**Comment by aiwennba** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8187904/240517275-0bee8b3f-6932-4d14-8de5-d4ca64e7b996.png) 没有看见有错误日志输出
> 
> 尝试整体重启一下HUB服务呢

我重启了，测试环境重新部署了一遍也不行
