### ISSUE TITLE
Elkeid 单机docker快速部署 - ko 始终无法加载成功

### ISSUE THREAD

**Issue by wywwzjj** [bytedance/Elkeid#488]
根据文档：https://elkeid.bytedance.com/Chinese/ElkeidUp/ElkeidUp.html 进行单机测试部署，使用 elkeidup_image_v1.9.1.tar.gz 镜像

无论是在 Elkeid Server 机器下运行运行 agent，还是另外开一台同内核版本的机器，ko 始终无法加载成功

![image](https://user-images.githubusercontent.com/35456892/233142179-ca59a209-45ac-4bd2-8cc8-d1a3b4602ea0.png)

插件均正常运行
![image](https://user-images.githubusercontent.com/35456892/233141230-7512aeac-f82c-45a5-8202-af060da0b58e.png)

![image](https://user-images.githubusercontent.com/35456892/233143131-3ceb9cb9-92e2-47d4-a6cd-3dd2de4c918d.png)

**Comment by TaeRoen** [comment]
@wywwzjj 
确认两件事，安装时是否选择同意自动下载ko，Server所在的机器是否有公网连接？

**Comment by TaeRoen** [comment]
给下纯离线加载ko的方案。
1. 先确认下需求ko的版本。
分别执行下 
`
strings /etc/elkeid/plugin/driver/driver | grep 1.7.0.9
`
`
strings /etc/elkeid/plugin/driver/driver | grep 1.7.0.10
`
哪个命令有输出，需求的ko就是相应的版本。

2. 下载离线ko.tar.xz

1.7.0.9 https://github.com/bytedance/Elkeid/releases/download/v1.9.1/ko_1.7.0.9.tar.xz
1.7.0.10 https://github.com/bytedance/Elkeid/releases/download/v1.9.1.3/ko.tar.xz 

3. 解压到 server 的对应文件夹，如果是容器，先使用docker cp 命令cp 进去。
目标路径 /elkeid/nginx_dir_agent/agent/component/driver
解压后期待的路径  `/elkeid/nginx_dir_agent/agent/component/driver/ko/hids_driver_1.7.0.10_4.8.0-39-generic_amd64.ko`
解压后执行 chown -R nginx:nginx /elkeid/nginx_dir_agent

4. 重启对应的agent

`systemctl restart elkeid-agent`

**Comment by wywwzjj** [comment]
感谢 @TaeRoen  ，是 ko 版本的问题，内核版本过新，不在预编译列表中
另外在 https://github.com/bytedance/Elkeid/blob/main/driver/README-zh_CN.md 中，driver 已经改为 1.7.0.10，所以手动下载的版本不匹配
![image](https://user-images.githubusercontent.com/35456892/233301069-ee7ebf2f-6a9f-44e9-9ddc-ddfa48fa11fe.png)
实际 [部署文档](https://elkeid.bytedance.com/Chinese/ElkeidUp/ElkeidUp.html#3agent-install-remark) 的镜像中用的还是 1.7.0.9，所以一直没启动起来。

补充：nginx 日志在 `/elkeid/nginx/nginx/logs`，如遇到类似问题，可先看 ko 有没有下载成功
