### ISSUE TITLE
[rasp] java.io.File.list

### ISSUE THREAD

**Issue by turn1tup** [bytedance/Elkeid#492]
**Is your feature request related to a problem? Please describe.**
java.io.File#list 是不是修改为 normalizedList 更好 ，存在攻击场景使用 java.io.File#listFiles  

![image](https://user-images.githubusercontent.com/41148379/234162725-4877bff4-9a1f-4f41-8ed9-03b21a2ab924.png)
![image](https://user-images.githubusercontent.com/41148379/234163096-f694b6f4-b720-4f6d-b27f-5ad94bf0bff4.png)
![image](https://user-images.githubusercontent.com/41148379/234163163-7bab2b9e-7eef-44c6-9e2d-f4ac605a086a.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AlkenePan** [comment]
你说的对，你可以在这里修正：

```
https://github.com/bytedance/Elkeid/blob/main/rasp/jvm/JVMProbe/src/main/resources/class.yaml
```

欢迎提交pull request！

**Comment by Hackerl** [comment]
有些版本并没有 `normalizedList` 这个 `API`，这属于内部实现的接口，`JDK` 各个版本可以任意改动。

**Comment by Hackerl** [comment]
例如 `OpenJDK 8` 的实现中 [`listFiles`](https://github.com/bpupadhyaya/openjdk-8/blob/master/jdk/src/share/classes/java/io/File.java#L1206) 也会调用 `list`，如果单纯地增加一个 `normalizedList` 的 `hook` 点并保留 `list`，那么在某些高版本中一次调用将会产生两份数据，如果去除 `list` 又无法兼容低版本。

**Comment by turn1tup** [comment]
沟通下来，这个问题不简单，暂时不处理。
