### ISSUE TITLE
 请教下Elkeid内核模块的实现与sysdig的区别

### ISSUE THREAD

**Issue by vito11** [bytedance/Elkeid#496]
我是内核小白，最近正在对比Elkeid和falco/sysdig在内核hook实现方面的区别，知道Elkeid是基于kprobe，falco/sysdig是基于tracepoint，然后仔细对比后发现两个项目在内核态和用户态通信的方式也存在区别，Elkeid的实现似乎借鉴了ftrace，是内核态维护了一个ringbuffer,  然后用户态通过读取管道文件拿到数据；sysdig则是利用mmap实现了一个共享的ringbuffer，那我在这方面有三点疑问想请教：
1. Elkeid用户态需要调用open系统调用来读取数据，是否sysdig的共享内存的实现方式对比Elkeid会减少一次内核态到用户态的内存拷贝，以及减少了用户态和内核态的切换开销？
2. 是否有sysdig和Elkeid的性能测试数据对比？
3. sysdig支持了ebpf，Elkeid未来也会支持ebpf吗？

**Comment by shenping-bd** [comment]
Elkeid v1.7的监控机制是kprobe及kretprobe，v1.8则是以tracepoint为主，kprobe及kretprobe为辅。
1.  共享内存方案确实可以更大地降低CPU占用，不过具体收益则取决数据量。Elkeid也有zero-copy/zero-syscall的方案，但并没有切换，主要牵扯到代码审计、版本迭代及部署问题
2. 没有做二者的比较，性能问题完全取决于应用场景，在场景中做全局的性能评估才有意义，毕竟二者的监控点选择及各自的处理均不同
3. Elkeid EBPF版本已开发完成，但还没有集成部署，可参阅v1.8-rc分支
