### ISSUE TITLE
AgentID由uuid方式生成且写入agent-id文件中，如果agent-id文件被删除该主机的唯一标识是不是就改变了？

### ISSUE THREAD

**Issue by zuoanyingxue** [bytedance/Elkeid#53]
**Is your feature request related to a problem? Please describe.**
主机唯一标志ID如何保证在机器重启或agent-id文件不小心删除后，主机的唯一标志仍旧不变更？

**Describe the solution you'd like**
1. AgentID的计算方式更改为使用主机名+ip计算hash值的方式，MD5（主机名+ip），可以一定程度上保证agent-id文件被删除之后，重新生成的id仍旧相同（除非主机名或ip有变更）。
2. 生成的AgentID值双写文件，在agent进程重启时，只要有一个文件内容符合，可使用文件内容作为AgentID，并检查另一个文件是否一致，不一致则进行内容同步。

**Describe alternatives you've considered**
1.AgentID值需要保证无论是主机重启还是agent-id文件被篡改或者意外被删除，都能保证该机器的id值不变，否则管理后台将出现离线agent记录；
2.AgentID的生成方式依赖主机上不经常变更的属性，可以一定程度上减少再次生成AgentID时产生的变化。

**Additional context**
1. 镜像组同学在制作镜像的时候可能把agent-id文件放入镜像中，导致后续新启用主机的AgentID值均相同，需要提前和内核组同学沟通镜像制作脚本中增加删除某些目录的命令；
2. 通过统计agent上报心跳信息，检测是否一个AgentID对应很多的主机名和ip，如果出现此类情况，说明AgentID值已经被复用。

**Comment by ZhangLei-cn** [comment]
目前我们已经有了一个比较完善的技术方案，会在下个版本上线，感谢您提供的宝贵建议。
方案特点：
* 依赖硬件或者系统的唯一标识符，在不换主板或者不重装系统的情况下agent id不会有变更
* 上述标识符兼容常见虚拟化环境，不会因为镜像拷贝而导致id重复
* 上述标识符由内核托管&确定，无法被用户态修改
* 在上述标识符不可用情况下会降级到目前所用方案
* agent id重复检测已经在当前版本的server实现，会有id conflict相关报错

**Comment by zuoanyingxue** [comment]
期待下个版本的上线~
