### ISSUE TITLE
driver插件手动编译问题

### ISSUE THREAD

**Issue by Hua102125** [bytedance/Elkeid#536]
代码分支：master
环境配置：centos7  rust-1.72.0
执行命令：BUILD_VERSION=1.0.0.15 bash build.sh
编译结果异常如下：
![联想截图_20230912172307](https://github.com/bytedance/Elkeid/assets/102858903/bcd76976-aa9c-4728-aaf6-8c371c6af699)

**Comment by kulukami** [comment]
build readme 未更新问题
*  x64 编译正常
*  arm64 交叉编译报错，编译链问题，arm64 需要 单独配置GCC，并指定 CC=aarch64-linux-musl-gcc

建议 先区分 架构环境 单独编译，如果 只需要 x64 的 先 注释掉 arm64 部分

**Comment by kulukami** [comment]
#
