### ISSUE TITLE
PHP注入问题

### ISSUE THREAD

**Issue by pandaluocheng** [bytedance/Elkeid#537]
我用elkeid_rasp -p pid 来对php拉起来的进程动态注入提示：
[2023-09-14T09:23:22Z ERROR elkeid_rasp] can not inspect process runtime
Error:

我看文档里面只有介绍通过php -d 'extension=$(pwd)/lib/libphp_probe.so' -r "shell_exec('ls'); sleep(60);"来进行启动时候的注入，启动时候注入socat UNIX-LISTEN:"/var/run/smith_agent.sock" -能收到消息的
，如何对php进程动态注入呢？支持动态注入吗？有单独命令吗？

我看了rust代码，看到源码是php-fpm注入代码？

**Comment by yoloyyh** [comment]
多进程下注入时，只需要在php.ini文件里添加上extension=$(pwd)/lib/libphp_probe.so（这里的目录替换为实际的libphp_probe.so的路径），添加后记得重启php-fpm，重启后可以执行php-fpm -m，看输出结果是否有php_probe确认是否注入成功。
