### ISSUE TITLE
RASP运行时类型没有python，怎么添加

### ISSUE THREAD

**Issue by IATF** [bytedance/Elkeid#546]
RASP前台界面里面下拉选择无法选择Python和nodejs，只有java、go、php，怎么添加python？

<img width="999" alt="image" src="https://github.com/bytedance/Elkeid/assets/20454721/d20c2a46-a62f-414f-bac6-3943eec16e11">

**Comment by yoloyyh** [comment]
前端未实现该功能，但后端是支持的，可以通过postman调用manager的api/v6/rasp/EditConfig接口，使用POST请求，在body里只需要把"runtime"的值添加上CPython即可，参考body内容：`{
            "name": "rasp-test-all",
            "user": "root",
            "if_protect": true,
            "ip_list": [],
            "tag": "",
            "cmd": "",
            "env_list": [],
            "alive_time": 10,
            "runtime": [
                "CPython",
                "Java",
                "Golang"
            ],
            "block": null,
            "filter": null,
            "block_uuid": "",
            "filter_uuid": "",
            "create_time": 1703593397
        }`

**Comment by IATF** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
