### ISSUE TITLE
rasp jvm版本支持问题

### ISSUE THREAD

**Issue by pandaluocheng** [bytedance/Elkeid#558]
对于JVM 21情况，升级asm到最新9.6情况下，最终有一个hook点报错：
![img_v3_025s_5a89dd81-8a16-424f-a89b-f3fcac1585dg](https://github.com/bytedance/Elkeid/assets/30709813/496bacd3-233c-4235-87cb-358d4ae860fe)

**Comment by yoloyyh** [comment]
最新版本已修复：https://github.com/bytedance/Elkeid/commit/3b9a75722898957fe71199b1e88ddb34de80ce31
