### ISSUE TITLE
怎么理解 agent 和 server/agent_center 下面的grpc.proto 风格不一样

### ISSUE THREAD

**Issue by raoqining** [bytedance/Elkeid#584]
我对grpc不是很熟悉, 看待两边看起来相同message 定义时, 一个用下划线小写, 一个用 驼峰, 这里为什么存在差异

message PackagedData {
  repeated EncodedRecord records = 1;
  string agent_id = 2;
  repeated string intranet_ipv4 = 3;
  repeated string extranet_ipv4 = 4;
  repeated string intranet_ipv6 = 5;
  repeated string extranet_ipv6 = 6;
  string hostname = 7;
  string version = 8;
  string product = 9;
}

message RawData{
  repeated Record Data = 1;
  string AgentID = 2;
  repeated string IntranetIPv4 = 3;
  repeated string ExtranetIPv4 = 4;
  repeated string IntranetIPv6 = 5;
  repeated string ExtranetIPv6 = 6;
  string Hostname = 7;
  string Version = 8;
  string Product = 9;
}

**Comment by Hackerl** [comment]
客户端和服务端开发人员使用的命名规范不同而已，grpc 序列化后的结构数据没有字段名，只要类型排布相同即可。
另外官方推荐 snake case。

**Comment by Hackerl** [comment]
客户端和服务端开发人员使用的命名规范不同而已，grpc 序列化后的结构数据没有字段名，只要类型排布相同即可。
另外官方推荐 snake case。

**Comment by raoqining** [comment]
> 客户端和服务端开发人员使用的命名规范不同而已，grpc 序列化后的结构数据没有字段名，只要类型排布相同即可。 另外官方推荐 snake case。

感谢解答疑问, 已经编译调试通过
