### ISSUE TITLE
Elkeid/blob/main/agent/README-zh_CN.md 中可能误删了某段说明，会导致demo跑不通

### ISSUE THREAD

**Issue by xie4ever** [bytedance/Elkeid#63]
问题文件：https://github.com/bytedance/Elkeid/blob/main/agent/README-zh_CN.md

我注意到开发者在某次提交中，删除了这么一段说明：

```
// 注意首次使用时，需要设置agent默认配置，可以设置为空(为空意味着新接入的agent不会自动开启任何插件):
curl --location --request POST 'http://127.0.0.1:6701/api/v1/agent/updateDefaultConfig' -H "token:your token" \
--data-raw '{
    "type": "agent_config",
    "version": 0,
    "config": []
}'
```

首次使用时，如果不进行这样一次请求配置，后面通过manager和agent-center进行插件下发，agent不会有任何反应，很容易让刚接触的同学感到迷惑。而且看日志是看不出这个问题的，

个人认为这个设计可能不是很合理，就算不进行默认配置，只要下发插件，agent也应该接受才对。

**Comment by hugebomb** [comment]
现在的版本中已经优化掉这个步骤，可以不再需要执行这个。
