### ISSUE TITLE
请问collector插件收集到的数据在哪里查看？

### ISSUE THREAD

**Issue by destinysz** [bytedance/Elkeid#69]
kafka topic里看了，仿佛没找到。

**Comment by xie4ever** [comment]
可能要确认一下部署是否成功，使用agent-center下test包的工具确认能否正确消费

**Comment by Serinalice** [comment]
collector插件里面的数据大部分都是定时采集的，一般会在10min后开始第一次采集，在数据采集前消费数据是找不到的。
另外，collector的数据data_type格式为50xx，可以利用这个特征快速找到相应类型的数据。

**Comment by destinysz** [comment]
> 收集工具插件里面的这些定时收集的数据，一般会在 10 分钟后第一次收集，在收集前的消费数据都是找不到的。另外
> ，收集器的数据类型格式为 50xx，可以利用特征找到快速对应的数据。

感谢，看到了。
