### ISSUE TITLE
执行node inspector.js 报错Error: Cannot find module './smith'\n

### ISSUE THREAD

**Issue by nwanglu** [bytedance/Elkeid#74]
Node RASP按照说明执行
# in shell 1
$ socat UNIX-LISTEN:"/var/run/smith_agent.sock" -
# in shell 2
$ node test.js
# in shell 3
$ node injector.js $(pidof node) "require('./smith')"

报错
root➜Elkeid/rasp/node(main✗)» node injector.js 11517 "require('./smith')"                                                                                                                                                                         [22:20:01]
pid => 11517
expression => require('./smith')
after process._debugProcess(11517)
{
  result: {
    type: 'object',
    subtype: 'error',
    className: 'Error',
    description: "Error: Cannot find module './smith'\n" +
      'Require stack:\n' +
      '- <inspector console>\n' +
      '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)\n' +
      '    at Function.Module._load (internal/modules/cjs/loader.js:730:27)\n' +
      '    at Module.require (internal/modules/cjs/loader.js:957:19)\n' +
      '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
      '    at <anonymous>:1:1',
    objectId: '{"injectedScriptId":1,"id":1}'
  },
  exceptionDetails: {
    exceptionId: 5,
    text: 'Uncaught',
    lineNumber: 887,
    columnNumber: 2,
    scriptId: '80',
    stackTrace: { callFrames: [Array] },
    exception: {
      type: 'object',
      subtype: 'error',
      className: 'Error',
      description: "Error: Cannot find module './smith'\n" +
        'Require stack:\n' +
        '- <inspector console>\n' +
        '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)\n' +
        '    at Function.Module._load (internal/modules/cjs/loader.js:730:27)\n' +
        '    at Module.require (internal/modules/cjs/loader.js:957:19)\n' +
        '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
        '    at <anonymous>:1:1',
      objectId: '{"injectedScriptId":1,"id":2}'
    }
  }
}

**Comment by AlkenePan** [comment]
node injector.js $(pidof node) "require('/root/Elkeid/rasp/node/smith')"
