### ISSUE TITLE
scanner 插件报错：ind: Other, error: "creation time is not available on this platform currently"

### ISSUE THREAD

**Issue by 297242448** [bytedance/Elkeid#75]
{"plugin":"scanner","level":"error","version":"1.6.0.0","time_pkg":"1626319733","in_ipv6_list":"","source":"scanner::detector","timestamp":"1626319733","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","ex_ipv6_list":"","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }"}
{"in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","plugin":"scanner","source":"scanner::detector","time_pkg":"1626319735","hostname":"host-10-170-203-15","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","in_ipv6_list":"","ex_ipv6_list":"","timestamp":"1626319735","level":"error","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","version":"1.6.0.0"}
{"in_ipv6_list":"","ex_ipv4_list":"","data_type":"1002","timestamp":"1626319737","plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","level":"error","time_pkg":"1626319737","ex_ipv6_list":"","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"level":"error","source":"scanner::detector","timestamp":"1626319739","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","in_ipv6_list":"","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","ex_ipv6_list":"","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","data_type":"1002","plugin":"scanner","time_pkg":"1626319739","hostname":"host-10-170-203-15","version":"1.6.0.0"}
{"data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","plugin":"scanner","source":"scanner::detector","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","timestamp":"1626319741","version":"1.6.0.0","ex_ipv6_list":"","level":"error","time_pkg":"1626319741","in_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }"}
{"hostname":"host-10-170-203-15","in_ipv6_list":"","ex_ipv6_list":"","level":"error","source":"scanner::detector","data_type":"1002","time_pkg":"1626319743","ex_ipv4_list":"","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","timestamp":"1626319743","version":"1.6.0.0"}
{"data_type":"1000","net_type":"ac","ex_ipv6_list":"","kernel_version":"3.10.0-1160.6.1.el7.x86_64","plugins":"[{\"rss\":3477504,\"io\":0,\"cpu\":0.00033451808488604867,\"name\":\"journal_watcher\",\"version\":\"1.6.0.0\",\"pid\":146828,\"qps\":0},{\"rss\":53628928,\"io\":8192,\"cpu\":0.0006690361697720825,\"name\":\"scanner\",\"version\":\"0.0.0.1\",\"pid\":147132,\"qps\":0.5},{\"rss\":9437184,\"io\":0,\"cpu\":0.0010035542546581535,\"name\":\"driver\",\"version\":\"1.6.0.0\",\"pid\":146820,\"qps\":12.866666666666667},{\"rss\":12058624,\"io\":0,\"cpu\":0.00033451808488604867,\"name\":\"collector\",\"version\":\"1.6.0.0\",\"pid\":146832,\"qps\":0}]","time_pkg":"1626319743","platform_version":"7.9.2009","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","slab":"2293104","platform":"centos","io":"0","timestamp":"1626319743","in_ipv6_list":"","cpu":"0.00368","memory":"19562496","hostname":"host-10-170-203-15","version":"1.6.0.0"}
{"level":"error","source":"scanner::detector","hostname":"host-10-170-203-15","timestamp":"1626319745","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319745","ex_ipv6_list":"","in_ipv6_list":"","ex_ipv4_list":"","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","data_type":"1002","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"hostname":"host-10-170-203-15","version":"1.6.0.0","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","level":"error","plugin":"scanner","data_type":"1002","ex_ipv4_list":"","timestamp":"1626319747","time_pkg":"1626319747","in_ipv6_list":"","ex_ipv6_list":""}
{"level":"error","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319749","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","hostname":"host-10-170-203-15","source":"scanner::detector","time_pkg":"1626319749","version":"1.6.0.0","ex_ipv4_list":"","ex_ipv6_list":""}
{"ex_ipv4_list":"","level":"error","plugin":"scanner","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv6_list":"","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319751","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","timestamp":"1626319751","ex_ipv6_list":""}
{"timestamp":"1626319753","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319753","version":"1.6.0.0","source":"scanner::detector","data_type":"1002","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","level":"error","ex_ipv4_list":"","in_ipv6_list":"","hostname":"host-10-170-203-15","ex_ipv6_list":""}
{"level":"error","ex_ipv4_list":"","ex_ipv6_list":"","timestamp":"1626319755","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","time_pkg":"1626319755","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","data_type":"1002"}
{"ex_ipv4_list":"","plugin":"scanner","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","ex_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","source":"scanner::detector","level":"error","time_pkg":"1626319757","in_ipv6_list":"","timestamp":"1626319757","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"plugin":"scanner","timestamp":"1626319759","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","ex_ipv4_list":"","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319759","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","level":"error","hostname":"host-10-170-203-15","in_ipv6_list":""}
{"source":"scanner::detector","timestamp":"1626319761","hostname":"host-10-170-203-15","level":"error","data_type":"1002","time_pkg":"1626319761","ex_ipv4_list":"","ex_ipv6_list":"","plugin":"scanner","in_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","plugin":"scanner","version":"1.6.0.0","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","level":"error","data_type":"1002","source":"scanner::detector","timestamp":"1626319763","time_pkg":"1626319763","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","ex_ipv6_list":""}
{"plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","source":"scanner::detector","in_ipv6_list":"","level":"error","data_type":"1002","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","timestamp":"1626319765","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319765","hostname":"host-10-170-203-15","ex_ipv6_list":""}
{"source":"scanner::detector","level":"error","version":"1.6.0.0","timestamp":"1626319767","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319767","hostname":"host-10-170-203-15","ex_ipv4_list":"","ex_ipv6_list":"","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":""}
{"data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","ex_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","level":"error","time_pkg":"1626319769","source":"scanner::detector","hostname":"host-10-170-203-15","version":"1.6.0.0","plugin":"scanner","timestamp":"1626319769","ex_ipv4_list":""}
{"ex_ipv4_list":"","plugin":"scanner","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv6_list":"","ex_ipv6_list":"","level":"error","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319771","timestamp":"1626319771"}
{"level":"error","version":"1.6.0.0","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","ex_ipv4_list":"","source":"scanner::detector","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","data_type":"1002","timestamp":"1626319773","time_pkg":"1626319773"}
{"ex_ipv4_list":"","data_type":"1000","memory":"20025344","time_pkg":"1626319773","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","io":"4096","cpu":"0.00402","timestamp":"1626319773","ex_ipv6_list":"","kernel_version":"3.10.0-1160.6.1.el7.x86_64","net_type":"ac","platform":"centos","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv6_list":"","slab":"2293548","platform_version":"7.9.2009","plugins":"[{\"rss\":12058624,\"io\":0,\"cpu\":0.0003346300246772439,\"name\":\"collector\",\"version\":\"1.6.0.0\",\"pid\":146832,\"qps\":0},{\"rss\":9437184,\"io\":0,\"cpu\":0.000669260049354473,\"name\":\"driver\",\"version\":\"1.6.0.0\",\"pid\":146820,\"qps\":13.1},{\"rss\":53628928,\"io\":8192,\"cpu\":0.001003890074031739,\"name\":\"scanner\",\"version\":\"0.0.0.1\",\"pid\":147132,\"qps\":0.5},{\"rss\":3477504,\"io\":0,\"cpu\":0,\"name\":\"journal_watcher\",\"version\":\"1.6.0.0\",\"pid\":146828,\"qps\":0}]","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2"}
{"data_type":"1002","source":"scanner::detector","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","ex_ipv6_list":"","version":"1.6.0.0","timestamp":"1626319775","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319775","plugin":"scanner","level":"error","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","hostname":"host-10-170-203-15","in_ipv6_list":""}
{"msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","data_type":"1002","time_pkg":"1626319777","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","ex_ipv6_list":"","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","timestamp":"1626319777","source":"scanner::detector","hostname":"host-10-170-203-15","level":"error","plugin":"scanner","version":"1.6.0.0"}
{"time_pkg":"1626319779","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","plugin":"scanner","timestamp":"1626319779","hostname":"host-10-170-203-15","level":"error","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","version":"1.6.0.0","in_ipv6_list":"","source":"scanner::detector"}
{"data_type":"1002","version":"1.6.0.0","in_ipv6_list":"","ex_ipv6_list":"","timestamp":"1626319781","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319781","level":"error","source":"scanner::detector","ex_ipv4_list":"","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","plugin":"scanner","hostname":"host-10-170-203-15"}
{"data_type":"1002","version":"1.6.0.0","in_ipv6_list":"","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319783","ex_ipv4_list":"","timestamp":"1626319783","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","level":"error","ex_ipv6_list":""}
{"plugin":"scanner","version":"1.6.0.0","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","ex_ipv4_list":"","ex_ipv6_list":"","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319785","hostname":"host-10-170-203-15","level":"error","timestamp":"1626319785","data_type":"1002"}
{"plugin":"scanner","time_pkg":"1626319787","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","data_type":"1002","ex_ipv4_list":"","ex_ipv6_list":"","timestamp":"1626319787","level":"error","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","hostname":"host-10-170-203-15","version":"1.6.0.0"}
{"time_pkg":"1626319789","hostname":"host-10-170-203-15","in_ipv6_list":"","data_type":"1002","level":"error","source":"scanner::detector","timestamp":"1626319789","plugin":"scanner","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","ex_ipv6_list":""}
{"version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","ex_ipv6_list":"","timestamp":"1626319791","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319791","plugin":"scanner","ex_ipv4_list":"","data_type":"1002","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","level":"error","hostname":"host-10-170-203-15"}
{"agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","timestamp":"1626319793","time_pkg":"1626319793","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","source":"scanner::detector","data_type":"1002","plugin":"scanner","ex_ipv4_list":"","ex_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","level":"error","in_ipv6_list":""}
{"data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","source":"scanner::detector","hostname":"host-10-170-203-15","in_ipv6_list":"","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","timestamp":"1626319795","level":"error","plugin":"scanner","time_pkg":"1626319795","ex_ipv4_list":""}
{"ex_ipv6_list":"","data_type":"1002","timestamp":"1626319797","time_pkg":"1626319797","version":"1.6.0.0","level":"error","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","in_ipv6_list":"","ex_ipv4_list":"","plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"in_ipv6_list":"","ex_ipv4_list":"","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","version":"1.6.0.0","time_pkg":"1626319799","data_type":"1002","level":"error","plugin":"scanner","timestamp":"1626319799","hostname":"host-10-170-203-15","ex_ipv6_list":""}
{"source":"scanner::detector","plugin":"scanner","ex_ipv6_list":"","time_pkg":"1626319801","level":"error","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","timestamp":"1626319801","in_ipv6_list":"","ex_ipv4_list":"","data_type":"1002"}
{"timestamp":"1626319803","version":"1.6.0.0","in_ipv6_list":"","level":"error","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","plugin":"scanner","source":"scanner::detector","time_pkg":"1626319803","ex_ipv4_list":"","ex_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }"}
{"in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","plugins":"[{\"rss\":3477504,\"io\":0,\"cpu\":0,\"name\":\"journal_watcher\",\"version\":\"1.6.0.0\",\"pid\":146828,\"qps\":0},{\"rss\":53628928,\"io\":12288,\"cpu\":0.0006692320562178769,\"name\":\"scanner\",\"version\":\"0.0.0.1\",\"pid\":147132,\"qps\":0.5},{\"rss\":9437184,\"io\":0,\"cpu\":0.001003848084326845,\"name\":\"driver\",\"version\":\"1.6.0.0\",\"pid\":146820,\"qps\":19.3},{\"rss\":12058624,\"io\":0,\"cpu\":0,\"name\":\"collector\",\"version\":\"1.6.0.0\",\"pid\":146832,\"qps\":0}]","net_type":"ac","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","cpu":"0.00402","timestamp":"1626319803","hostname":"host-10-170-203-15","memory":"19582976","platform":"centos","in_ipv6_list":"","ex_ipv6_list":"","platform_version":"7.9.2009","time_pkg":"1626319803","ex_ipv4_list":"","data_type":"1000","kernel_version":"3.10.0-1160.6.1.el7.x86_64","io":"8192","slab":"2293648"}
{"source":"scanner::detector","plugin":"scanner","hostname":"host-10-170-203-15","in_ipv6_list":"","ex_ipv4_list":"","ex_ipv6_list":"","level":"error","time_pkg":"1626319805","version":"1.6.0.0","timestamp":"1626319805","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }"}
{"in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","timestamp":"1626319807","source":"scanner::detector","ex_ipv4_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","data_type":"1002","plugin":"scanner","version":"1.6.0.0","in_ipv6_list":"","level":"error","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319807","hostname":"host-10-170-203-15"}
{"in_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319809","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","hostname":"host-10-170-203-15","ex_ipv4_list":"","ex_ipv6_list":"","plugin":"scanner","source":"scanner::detector","data_type":"1002","time_pkg":"1626319809","level":"error","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2"}
{"in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv6_list":"","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319811","hostname":"host-10-170-203-15","in_ipv6_list":"","source":"scanner::detector","plugin":"scanner","timestamp":"1626319811","version":"1.6.0.0","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","level":"error","ex_ipv4_list":""}
{"hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319813","ex_ipv4_list":"","timestamp":"1626319813","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","ex_ipv6_list":"","data_type":"1002","plugin":"scanner","version":"1.6.0.0","level":"error","source":"scanner::detector"}
{"time_pkg":"1626319815","version":"1.6.0.0","plugin":"scanner","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","ex_ipv4_list":"","timestamp":"1626319815","level":"error","data_type":"1002","ex_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2"}
{"source":"scanner::detector","time_pkg":"1626319817","in_ipv6_list":"","ex_ipv6_list":"","timestamp":"1626319817","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","version":"1.6.0.0","data_type":"1002","level":"error","plugin":"scanner","ex_ipv4_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"ex_ipv6_list":"","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","time_pkg":"1626319819","in_ipv6_list":"","ex_ipv4_list":"","data_type":"1002","level":"error","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","plugin":"scanner","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319819","hostname":"host-10-170-203-15"}
{"agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319821","ex_ipv6_list":"","ex_ipv4_list":"","level":"error","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","source":"scanner::detector","in_ipv6_list":"","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319821","plugin":"scanner","version":"1.6.0.0"}
{"ex_ipv6_list":"","source":"scanner::detector","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319823","hostname":"host-10-170-203-15","data_type":"1002","in_ipv6_list":"","plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","timestamp":"1626319823","level":"error","version":"1.6.0.0","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"source":"scanner::detector","hostname":"host-10-170-203-15","version":"1.6.0.0","data_type":"1002","plugin":"scanner","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319825","level":"error","timestamp":"1626319825","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","in_ipv6_list":"","ex_ipv4_list":"","ex_ipv6_list":""}
{"agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":"","plugin":"scanner","source":"scanner::detector","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","hostname":"host-10-170-203-15","version":"1.6.0.0","timestamp":"1626319827","time_pkg":"1626319827","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","level":"error","in_ipv6_list":"","ex_ipv6_list":""}
{"timestamp":"1626319829","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","time_pkg":"1626319829","version":"1.6.0.0","in_ipv6_list":"","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","plugin":"scanner","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","level":"error","hostname":"host-10-170-203-15","ex_ipv4_list":"","ex_ipv6_list":"","source":"scanner::detector"}
{"hostname":"host-10-170-203-15","ex_ipv6_list":"","data_type":"1002","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319833","level":"error","time_pkg":"1626319833","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","plugin":"scanner","source":"scanner::detector","version":"1.6.0.0","in_ipv6_list":"","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","ex_ipv4_list":""}
{"plugins":"[{\"rss\":12058624,\"io\":0,\"cpu\":0,\"name\":\"collector\",\"version\":\"1.6.0.0\",\"pid\":146832,\"qps\":0},{\"rss\":9437184,\"io\":0,\"cpu\":0.0010038480843229346,\"name\":\"driver\",\"version\":\"1.6.0.0\",\"pid\":146820,\"qps\":13.666666666666666},{\"rss\":53628928,\"io\":8192,\"cpu\":0.0006692320562152996,\"name\":\"scanner\",\"version\":\"0.0.0.1\",\"pid\":147132,\"qps\":0.4666666666666667},{\"rss\":3477504,\"io\":0,\"cpu\":0.0003346160281076424,\"name\":\"journal_watcher\",\"version\":\"1.6.0.0\",\"pid\":146828,\"qps\":0}]","time_pkg":"1626319833","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","platform":"centos","net_type":"ac","data_type":"1000","cpu":"0.00402","memory":"19382272","ex_ipv6_list":"","platform_version":"7.9.2009","kernel_version":"3.10.0-1160.6.1.el7.x86_64","timestamp":"1626319833","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","version":"1.6.0.0","in_ipv6_list":"","ex_ipv4_list":"","io":"4096","slab":"2293584"}
{"timestamp":"1626319835","plugin":"scanner","time_pkg":"1626319835","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","ex_ipv4_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","data_type":"1002","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","version":"1.6.0.0","in_ipv6_list":"","level":"error","hostname":"host-10-170-203-15","ex_ipv6_list":""}
{"msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","timestamp":"1626319837","hostname":"host-10-170-203-15","version":"1.6.0.0","time_pkg":"1626319837","in_ipv6_list":"","level":"error","ex_ipv4_list":"","ex_ipv6_list":"","source":"scanner::detector","plugin":"scanner","data_type":"1002","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"timestamp":"1626319839","version":"1.6.0.0","ex_ipv4_list":"","level":"error","data_type":"1002","plugin":"scanner","in_ipv6_list":"","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","time_pkg":"1626319839","ex_ipv6_list":"","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1"}
{"plugin":"scanner","hostname":"host-10-170-203-15","in_ipv4_list":"10.170.203.15,172.18.0.1,172.19.0.1","version":"1.6.0.0","data_type":"1002","timestamp":"1626319841","time_pkg":"1626319841","ex_ipv6_list":"","level":"error","msg":"Custom { kind: Other, error: \"creation time is not available on this platform currently\" }","source":"scanner::detector","agent_id":"7d415041-789d-47cf-bb89-77b4ed958ad2","in_ipv6_list":"","ex_ipv4_list":""}
^CProcessed a total of 244687 messages
![image](https://user-images.githubusercontent.com/10005695/125910778-69d2a3db-ba0c-4f01-a4e1-b74261536a93.png)

**Comment by kulukami** [comment]
# Where is it
**known-errors--bugs** Seen at [scanner/README.md](https://github.com/bytedance/Elkeid/tree/main/agent/scanner#known-errors--bugs)
# Why 
creation time is not available for the filesystem
# What happened 
* creation time will be set to 0
* print a err log
* nothing more

Reply to @297242448

**Comment by kulukami** [comment]
This error log will be removed in future.

**Comment by 297242448** [comment]
creation time will be set to 0，有指引吗，在哪里设置
