### ISSUE TITLE
scanner插件编译有报错提示error: failed to run custom build command for `yara-sys v0.6.2

### ISSUE THREAD

**Issue by shen771** [bytedance/Elkeid#97]
**Describe the bug**
scanner插件编译有报错

**To Reproduce**

root@st-lb-2 (16:35:27) scanner # chmod +x build.sh && ./build.sh
    Updating crates.io index
  Downloaded parking_lot_core v0.8.3
  Downloaded cc v1.0.69
  Downloaded coarsetime v0.1.19
  Downloaded procfs v0.9.1
  Downloaded lazy_static v1.4.0
  Downloaded termcolor v1.1.2
  Downloaded time v0.1.43
  Downloaded hashbrown v0.11.2
  Downloaded parking_lot v0.11.1
  Downloaded ansi_term v0.11.0
  Downloaded block-buffer v0.9.0
  Downloaded byteorder v1.4.3
  Downloaded autocfg v1.0.1
  Downloaded vec_map v0.8.2
  Downloaded thiserror-impl v1.0.26
  Downloaded atty v0.2.14
  Downloaded cfg-if v1.0.0
  Downloaded itoa v0.4.7
  Downloaded memchr v2.4.0
  Downloaded scopeguard v1.1.0
  Downloaded ahash v0.7.4
  Downloaded bindgen v0.58.1
  Downloaded crossbeam-channel v0.5.1
  Downloaded env_logger v0.8.4
  Downloaded lru v0.6.6
  Downloaded nom v5.1.2
  Downloaded rmp v0.8.10
  Downloaded rmp-serde v0.14.4
  Downloaded smallvec v1.6.1
  Downloaded yansi v0.5.0
  Downloaded adler v1.0.2
  Downloaded once_cell v1.8.0
  Downloaded clang-sys v1.2.0
  Downloaded cexpr v0.4.0
  Downloaded crossbeam-utils v0.8.5
  Downloaded humantime v2.1.0
  Downloaded unicode-xid v0.2.2
  Downloaded proc-macro2 v1.0.28
  Downloaded textwrap v0.11.0
  Downloaded quote v1.0.9
  Downloaded serde_derive v1.0.127
  Downloaded typenum v1.13.0
  Downloaded anyhow v1.0.42
  Downloaded bitflags v1.2.1
  Downloaded ryu v1.0.5
  Downloaded syn v1.0.74
  Downloaded generic-array v0.14.4
  Downloaded clap v2.33.3
  Downloaded chrono v0.4.19
  Downloaded serde v1.0.127
  Downloaded cpufeatures v0.1.5
  Downloaded unicode-width v0.1.8
  Downloaded lock_api v0.4.4
  Downloaded walkdir v2.3.2
  Downloaded num-integer v0.1.44
  Downloaded same-file v1.0.6
  Downloaded crc32fast v1.2.1
  Downloaded which v3.1.1
  Downloaded libloading v0.7.0
  Downloaded regex v1.5.4
  Downloaded libc v0.2.98
  Downloaded log v0.4.14
  Downloaded glob v0.3.0
  Downloaded getrandom v0.2.3
  Downloaded aho-corasick v0.7.18
  Downloaded serde_json v1.0.66
  Downloaded opaque-debug v0.3.0
  Downloaded num-traits v0.2.14
  Downloaded lazycell v1.3.0
  Downloaded instant v0.1.10
  Downloaded hex v0.4.3
  Downloaded digest v0.9.0
  Downloaded miniz_oxide v0.4.4
  Downloaded peeking_take_while v0.1.2
  Downloaded rustc-hash v1.1.0
  Downloaded version_check v0.9.3
  Downloaded thiserror v1.0.26
  Downloaded flate2 v1.0.20
  Downloaded strsim v0.8.0
  Downloaded shlex v1.0.0
  Downloaded sha2 v0.9.5
  Downloaded yara v0.6.1
  Downloaded regex-syntax v0.6.25
  Downloaded yara-sys v0.6.2
  Downloaded 84 crates (5.1 MB) in 3.46s
   Compiling libc v0.2.98
   Compiling version_check v0.9.3
   Compiling memchr v2.4.0
   Compiling proc-macro2 v1.0.28
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling unicode-xid v0.2.2
   Compiling log v0.4.14
   Compiling syn v1.0.74
   Compiling bitflags v1.2.1
   Compiling glob v0.3.0
   Compiling serde_derive v1.0.127
   Compiling regex-syntax v0.6.25
   Compiling unicode-width v0.1.8
   Compiling serde v1.0.127
   Compiling vec_map v0.8.2
   Compiling bindgen v0.58.1
   Compiling crc32fast v1.2.1
   Compiling strsim v0.8.0
   Compiling termcolor v1.1.2
   Compiling byteorder v1.4.3
   Compiling ansi_term v0.11.0
   Compiling lazy_static v1.4.0
   Compiling typenum v1.13.0
   Compiling humantime v2.1.0
   Compiling rustc-hash v1.1.0
   Compiling smallvec v1.6.1
   Compiling anyhow v1.0.42
   Compiling scopeguard v1.1.0
   Compiling shlex v1.0.0
   Compiling peeking_take_while v0.1.2
   Compiling adler v1.0.2
   Compiling lazycell v1.3.0
   Compiling cc v1.0.69
   Compiling once_cell v1.8.0
   Compiling ryu v1.0.5
   Compiling crossbeam-utils v0.8.5
   Compiling serde_json v1.0.66
   Compiling yansi v0.5.0
   Compiling cpufeatures v0.1.5
   Compiling opaque-debug v0.3.0
   Compiling hex v0.4.3
   Compiling same-file v1.0.6
   Compiling itoa v0.4.7
   Compiling instant v0.1.10
   Compiling libloading v0.7.0
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.4
   Compiling num-integer v0.1.44
   Compiling nom v5.1.2
   Compiling generic-array v0.14.4
   Compiling ahash v0.7.4
   Compiling textwrap v0.11.0
   Compiling clang-sys v1.2.0
   Compiling lock_api v0.4.4
   Compiling walkdir v2.3.2
   Compiling aho-corasick v0.7.18
   Compiling time v0.1.43
   Compiling parking_lot_core v0.8.3
   Compiling getrandom v0.2.3
   Compiling atty v0.2.14
   Compiling coarsetime v0.1.19
   Compiling which v3.1.1
   Compiling quote v1.0.9
   Compiling crossbeam-channel v0.5.1
   Compiling parking_lot v0.11.1
   Compiling clap v2.33.3
   Compiling regex v1.5.4
   Compiling flate2 v1.0.20
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling rmp v0.8.10
   Compiling hashbrown v0.11.2
   Compiling cexpr v0.4.0
   Compiling env_logger v0.8.4
   Compiling sha2 v0.9.5
   Compiling chrono v0.4.19
   Compiling lru v0.6.6
   Compiling procfs v0.9.1
   Compiling thiserror-impl v1.0.26
   Compiling thiserror v1.0.26
   Compiling yara-sys v0.6.2
The following warnings were emitted during compilation:

warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: In function ‘_yr_ac_print_automaton_state’:
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:658:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:    for (int i = 0; i < state->depth; i++) printf(" ");
warning:    ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:658:3: note: use option -std=c99 or -std=gnu99 to compile your code
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:682:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:      for (int i = 0; i < state->depth + 1; i++) printf(" ");
warning:      ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:690:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:        for (int i = 0; i < yr_min(match->string->length, 10); i++)
warning:        ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:699:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:        for (int i = 0; i < yr_min(match->string->length, 10); i++)
warning:        ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:708:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:        for (int i = 0; i < yr_min(match->string->length, 10); i++)
warning:        ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: In function ‘yr_ac_add_string’:
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:792:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
warning:      for (int i = 0; i < atom->atom.length; i++)
warning:      ^
warning: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: At top level:
warning: cc1: warning: unrecognized command line option "-Wno-tautological-constant-out-of-range-compare" [enabled by default]
warning: cc1: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]

error: failed to run custom build command for `yara-sys v0.6.2`

Caused by:
  process didn't exit successfully: `/tmp/Elkeid/agent/scanner/target/release/build/yara-sys-241059ba85d8c3d4/build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara" "-I" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/include" "-Wall" "-Wextra" "-Wno-deprecated-declarations" "-Wno-unused-parameter" "-Wno-unused-function" "-Wno-cast-function-type" "-Wno-type-limits" "-Wno-tautological-constant-out-of-range-compare" "-Wno-sign-compare" "-DDEX_MODULE=" "-DDOTNET_MODULE=" "-DMACHO_MODULE=" "-DNDEBUG=1" "-DUSE_LINUX_PROC=" "-DPOSIX=" "-o" "/tmp/Elkeid/agent/scanner/target/x86_64-unknown-linux-gnu/release/build/yara-sys-56e1c8c802d2d0f1/out/ahocorasick.o" "-c" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c"
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: In function ‘_yr_ac_print_automaton_state’:
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:658:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=   for (int i = 0; i < state->depth; i++) printf(" ");
  cargo:warning=   ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:658:3: note: use option -std=c99 or -std=gnu99 to compile your code
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:682:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=     for (int i = 0; i < state->depth + 1; i++) printf(" ");
  cargo:warning=     ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:690:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=       for (int i = 0; i < yr_min(match->string->length, 10); i++)
  cargo:warning=       ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:699:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=       for (int i = 0; i < yr_min(match->string->length, 10); i++)
  cargo:warning=       ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:708:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=       for (int i = 0; i < yr_min(match->string->length, 10); i++)
  cargo:warning=       ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: In function ‘yr_ac_add_string’:
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c:792:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
  cargo:warning=     for (int i = 0; i < atom->atom.length; i++)
  cargo:warning=     ^
  cargo:warning=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c: At top level:
  cargo:warning=cc1: warning: unrecognized command line option "-Wno-tautological-constant-out-of-range-compare" [enabled by default]
  cargo:warning=cc1: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]
  exit code: 1

  --- stderr

  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara" "-I" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/include" "-Wall" "-Wextra" "-Wno-deprecated-declarations" "-Wno-unused-parameter" "-Wno-unused-function" "-Wno-cast-function-type" "-Wno-type-limits" "-Wno-tautological-constant-out-of-range-compare" "-Wno-sign-compare" "-DDEX_MODULE=" "-DDOTNET_MODULE=" "-DMACHO_MODULE=" "-DNDEBUG=1" "-DUSE_LINUX_PROC=" "-DPOSIX=" "-o" "/tmp/Elkeid/agent/scanner/target/x86_64-unknown-linux-gnu/release/build/yara-sys-56e1c8c802d2d0f1/out/ahocorasick.o" "-c" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.6.2/yara/libyara/ahocorasick.c" with args "cc" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed
Elkeid plugin build failed

**Comment by kulukami** [comment]
checkout the build essential / tool-chain
ref : #87

**Comment by shen771** [comment]
感谢支持，需要安装gcc clang llvm
gcc version >=6.3 clang >= 3.9，需要centos8以上的源才有这个版本，centos7不支持
